### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by bkj** [keras-team/autokeras#10]
Hi --

Do you have any information about the expected performance of this project on standard benchmarks, eg MNIST or CIFAR10?

Thanks

**Comment by jhfjhfj1** [comment]
@bkj We are fine tuning and running the experiments on several benchmark datasets. The results should be ready in one month.

**Comment by karandwivedi42** [comment]
@jhfjhfj1 any updates?

Thanks :)

**Comment by TPFLegionaire** [comment]
Hi

Unlikely...i am just learning how to use github.... 😉

cheers!



Manuel Boissiere





________________________________

**Comment by bkj** [comment]
Any updates here? I think it'd be good to add some rough performance numbers to the README so people can see expected results for debugging/comparison purposes.

**Comment by ashaw596** [comment]
There's some results in their paper I think. https://arxiv.org/pdf/1806.10282.pdf

**Comment by wardnath** [comment]
Benchmarks would be nice, particularly w.r.t. text classification, which isn't in the original paper.
