### ISSUE TITLE
Json Format data

### ISSUE THREAD

**Issue by hanotrahul** [keras-team/autokeras#1015]
### Feature Description
How can I load data that is in  JSON and start trainig of a model in object detection 
Code Example
>>> import autokeras as ak
>>> (x_train, y_train), (x_test, y_test) = mnist.load_data()
>>> clf = ak.ImageClassifier(max_trials=2)
>>> clf.fit(x_train, y_train, epochs=5)

```

### Reason

Most of the data is in stored in JSON format so it is more convenient if AutoKeras support training JSON format

**Comment by haifeng-jin** [comment]
Currently, we are not supporting JSON format, you have to write your own python program to convert JSON to a compatible format (numpy.ndarray, tf.data.Dataset).
We also do not support object detection for now.
Thanks.

**Comment by hanotrahul** [comment]
@haifeng-jin  when will autoKeras support object detection and prediction for custom models ??

**Comment by haifeng-jin** [comment]
@yufei-12 Is working on this. Hopefully will have some update soon. However, we don't have a timeline for when we can deliver this module for now.
