### ISSUE TITLE
how the auto one-hot encoded result map to the source label?

### ISSUE THREAD

**Issue by yesuu** [keras-team/autokeras#1032]
Assume use the `StructuredDataClassifier`, expected prediction result is three classifications of `0 5 10`.
After exporting the model, the `StatefulPartitionedCall` output is the one-hot encoded result, such as `[0,1,0]`.
But `StructuredDataClassifier.predict` outputs the source label, such as `0` or `5` or `10`.
How to map them both?

In order to know the answer, I looked at the code and found that the mapping is actually random.
it will cause the exported model to be unusable, ~and it will also can't run the model repeatedly.~
~I'm not sure `_label_to_vec` and `_int_to_label` are persistence.~

https://github.com/keras-team/autokeras/blob/df737b1acf2b2abf861ece431039bc13156ec881/autokeras/encoders.py#L37

In fact `set()` is just out of order, but the result is the same every time run, such as run `set([5,0,10])` will return `[0,10,5]` every time.

**Comment by haifeng-jin** [comment]
Hi,
If you want to use the export model, you will need to do the one hour encoding yourself. The structured data classifier accept both raw labels and encoded labels.

**Comment by ciberger** [comment]
you might use

```python
CLASS_NAMES = ['roses', 'sunflowers', 'daisy', 'dandelion', 'tulips']
y_train = [CLASS_NAMES[i] for i in ohe_predict.argmax(1)]
```
