### ISSUE TITLE
How do I freeze the model

### ISSUE THREAD

**Issue by Mrzhang3389** [keras-team/autokeras#1038]
I want to freeze the model to pb format...

**Comment by haifeng-jin** [comment]
I am not sure what is pb format. Is it possible to do it after exporting the model?

**Comment by Mrzhang3389** [comment]
The Pb format model can be deployed by tensorflow serving. Both the *. CKPT weight of tensorflow and the *. H5 of keras can be converted into Pb format files. The Pb format files are convenient for the environment configuration of the client and the server, so we hope to have a Pb format export interface
The following is an example of the directory structure of a Pb file
```
.
└── 0
    ├── saved_model.pb
    └── variables
        ├── variables.data-00000-of-00001
        └── variables.index
```

**Comment by haifeng-jin** [comment]
Thank you for the clarification! If my understanding is correct, you are able to do it with the current AutoKeras, right? You can just export the model as a Keras Model and convert it to on. So what you want is a convenient interface.

**Comment by Mrzhang3389** [comment]
Thank you for your reply. There is no mistake in your understanding. It would be better if you could have a convenient interface

1. The current problem is that the model export in *. H5 format of keras failed. I see in the issues that you are solving

2. Another problem is that some layers in autokeras are customized by you. They do not exist in the built-in layer of tensorflow, so they cannot be saved as *. Pb. I want to know what kind of data I should consult to solve this knowledge
