### ISSUE TITLE
Image classifier using keras.utils.Sequence

### ISSUE THREAD

**Issue by lamba92** [keras-team/autokeras#1043]
Is there a way to feed examples using a `keras.preprocessing.image.ImageDataGenerator().flow()`?
I was foolishly trying to convert the `Sequence` to a `tf.data.Dataset` with:
```python
data_generator = keras.preprocessing.image.ImageDataGenerator()
train_data_sequence = data_generator.flow_from_dataframe(
    # ...
)
train_data_tf_iterator = tf.data.Dataset.from_generator(
    train_data_sequence.__iter__,
    (tf.float32, tf.float32),
    (tf.TensorShape([]), tf.TensorShape([]))
)
```
but failed miserably. The output shape of the sequence is `[(300, 225, 3), (3)]` where the first tuple is the shape of the image while the other one is the one hot encoding of the 3 possible classes.

**Comment by haifeng-jin** [comment]
Currently, we did not test fort this feature. If you succeed, please let us know. Thanks

**Comment by lamba92** [comment]
Ok so then how do you feed a big dataset with images without `keras.utils.Sequence`s? It's implausible to load it all in memory as you do in examples. It's fine for small Fashion-MNIST like datasets, what the huge ones?

**Comment by haifeng-jin** [comment]
We don't have an example right now. I believe there is a way to put them into a tf.data.Dataset. Do you think so?
