### ISSUE TITLE
Update the greedy tuner to consider the conditional search space

### ISSUE THREAD

**Issue by ghost** [keras-team/autokeras#1045]
I just started using Autokeras ver 1.0.2 in anaconda with Python 3.7 and tensorflow-gpu ver. 2.1.0 on Windows 10. I have a dual RTX Titan (NVlinked) setup and using Spyder ver. 4.0.1

I wanted to do some simple binary classification for RGB images:

clf = ak.ImageClassifier()
clf.fit(x_train, y_train, epochs=10)

Training starts ok but after 3 trials, this happens:
INFO:tensorflow:Oracle triggered exit

I have tried different image datasets, including the MNIST example dataset but the exit trigger still happens after 3 trials, regardless of the val_acc. I can't figure out what is stopping Autokeras from continue to train beyond 3 trials (default is 100 trials?).

Looks like similar issue to https://github.com/keras-team/autokeras/issues/997
but problem is it is happening for version 1.0.2

**Comment by haifeng-jin** [comment]
This might because of the greedy tuning algorithms have some bugs. You can try to use the AutoModel API and use random search as tuner.

**Comment by WilliamJudge94** [comment]
I am having the same problem. I downgraded my AutoKeras from 1.0.2 to 1.0.1, set my **max_trials=10**, epochs=1 (for testing purposes) and I was still getting the Oracle error. **BUT** if I set the **max_trials=12** then it would complete all 12 trials without any issues. **This was also with kernel restarts in-between each max_trial test**. I am unsure what this means, but hopefully, it helps in the debugging process.
