### ISSUE TITLE
Provide an example for using tfrecord with AutoKeras

### ISSUE THREAD

**Issue by adsharanya** [keras-team/autokeras#1060]
### Feature Description

To make autokeras really useful it is important to be able to use it with datagenerators. Are we able to call the fit_generator method like in keras?

### Code Example

```python
```

**Comment by haifeng-jin** [comment]
Currently, we don't have plans for implementing this. Do you have some use cases that have to be done with a fit_generator?

**Comment by adsharanya** [comment]
Yes, I have very big datasets that will not fit in memory.

**Comment by haifeng-jin** [comment]
https://www.tensorflow.org/guide/data#consuming_tfrecord_data
This is a tutorial on using tf.data.Dataset to load large datasets, which doesn't fit in memory.
It is the most recommended way to load data to TF as well.

**Comment by TizianSchneiderZeMA** [comment]
Hi, is there a similar solution for the StructuredDataRegressor? I have large numerical, structured data and the StructuredDataRegressor does not seem to support tf.data.Dataset with numerical data yet.

**Comment by naitslup** [comment]
Hi, is there an example how to feed TFRecord files to autokeras i tried this:

# read TFRecord file
feature_description = {
    'data_x': tf.io.FixedLenFeature([500,], tf.float32),
    'data_y': tf.io.FixedLenFeature([1], tf.float32)
    }

def _parse_function(example_proto):
    return tf.io.parse_single_example(example_proto, feature_description)

def sample(iterator):
    return next(iterator)

dataset = tf.data.TFRecordDataset(filenames=[filename])
dataset = dataset.map(_parse_function)#, num_parallel_calls=8)
dataset = dataset.repeat().shuffle(buffer_size=50).batch(2)

#feed to Structured Data Regressor
model = ak.StructuredDataRegressor(max_trials=2)
model.fit(dataset)

but that gives me an error:

File "[...]autokeras\auto_model.py", line 297, in _process_xy
  x = dataset.map(lambda a, b: a)

  TypeError: <lambda>() missing 1 required positional argument: 'b'

**Comment by haifeng-jin** [comment]
Let's use #984 to track all the generator related issues. Thanks.

**Comment by torronen** [comment]
@haifeng-jin Would it be possible to ask for addition of example on how to use make_csv_dataset to https://autokeras.com/tutorial/load/ ?

Link above ( https://www.tensorflow.org/guide/data#consuming_tfrecord_data ) suggests make_csv_dataset. However consuming it in Autokeras does not seem intuitive.
