### ISSUE TITLE
Interface inspired by Ludwig

### ISSUE THREAD

**Issue by flozi00** [keras-team/autokeras#1076]
### Feature Description
An interface inspired by [Ubers ludwig](https://github.com/uber/ludwig).
Giving a .yaml definition file and CSV file to autokeras and data preprocessing + architecture search is done without any code.

### Reason
Anyone can train neural networks without any knowledge or coding skills.
Prototyping would become very fast.

### Solution
Is it possible to copy the interface and data pipeline from Ludwig and pass it to automodel API ?

**Comment by haifeng-jin** [comment]
@flozi00 Thank you for the request! We are interested in pairing with third-party Softwares to provide more features to the users. Are you from the Ludwig team?

We may consider doing this after the next stable release of AutoKeras on TF 2.2.

Thanks.

**Comment by haifeng-jin** [comment]
@tonyabracadabra Would you provide your thoughts on Ludwig? Thanks.

**Comment by flozi00** [comment]
> @flozi00 Thank you for the request! We are interested in pairing with third-party Softwares to provide more features to the users. Are you from the Ludwig team?
> 
> We may consider doing this after the next stable release of AutoKeras on TF 2.2.
> 
> Thanks.

I am not from Ludwig team.
Actually Ludwig is running on tf 1, but they are working on tf 2 version

**Comment by tonyabracadabra** [comment]
I think this is a good to have feature.

**Comment by flozi00** [comment]
Any news here ? @haifeng-jin @tonyabracadabra

**Comment by haifeng-jin** [comment]
We don't have enough people to work on this feature for now. But we welcome people to build a third-party package to do the job.
