### ISSUE TITLE
Enable limiting model size based on Keras Tuner

### ISSUE THREAD

**Issue by Pythonatheart** [keras-team/autokeras#1078]
### Bug Description
ImageRegressor training stops at random when training on dual RTX Titan GPUs. Error Message:

ResourceExhaustedError:  OOM when allocating tensor with shape[32,1280,64,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node model/separable_conv2d_15/separable_conv2d (defined at C:\Anaconda3\envs\automl\lib\site-packages\autokeras\engine\tuner.py:71) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_distributed_function_169665]

Function call stack:
distributed_function

### Bug Reproduction
Code for reproducing the bug:
model = ak.ImageRegressor(metrics=['mae', 'mape'],
                          max_trials=20)
model.fit(x_train, y_train, epochs=200)

Data used by the code:
custom image dataset. 
x.shape = (715, 128, 128, 3)
y.shape = (715,)
Did a 80:20 train-test-split: 
x_train = (572, 128, 128, 3).
y_train = (572,)

### Expected Behavior
Training to continue until 20 trials completed.

### Setup Details
Include the details about the versions of:
 - OS type and version: Windows 10 Pro 64-bit
 - Python: 3.7.6
 - autokeras: 1.0.2
 - keras-tuner: 1.0.1
 - scikit-learn: 0.22.1
 - numpy: 1.18.1
 - pandas: 1.0.1
 - tensorflow-gpu: 2.1.0 

### Additional context
Tried AutoModel as well but same OOM message appears. I have not been able to train beyond 5 trials without running into error either on ImageRegressor or AutoModel at this stage. Is there a way to limit AK from fitting networks too large to fit in GPU memory?

**Comment by Pythonatheart** [comment]
haifeng-jin, any time frame this will be implemented? I really like AK and want to use it in some of my papers. Thanks.

**Comment by haifeng-jin** [comment]
@Pythonatheart After #1093 is merged, you should be able to use it in the master branch. You can pass the `max_model_size` to any AutoKeras model you use.
You can find the description of `max_model_size` here:
https://keras-team.github.io/keras-tuner/documentation/tuners/#tuner-class

**Comment by Pythonatheart** [comment]
@haifeng-jin  Thank you for the response. However, can you provide an example of how to specify this in AutoKeras? The documentation for keras-tuner is not very useful:

max_model_size: Int. Maximum size of weights (in floating point coefficients) for a valid models. Models larger than this are rejected.

For example, how can I limit model size to fit my GPU, in this case a RTX Titan (24 GB memory)? What would be the "floating point coefficients" integer value as per documentation above? An example pseudocode will be helpful e.g. model.fit(x, y, max_model_size=value) or it is model = ImageRegressor(max_model_size=value)?

Thank you once again for your time and help.

**Comment by haifeng-jin** [comment]
@Pythonatheart I am not sure either.
This is the code I found how KT is using this max_model_size.
https://github.com/keras-team/keras-tuner/blob/d2d69cba21a0b482a85ce2a38893e2322e139c01/kerastuner/engine/hypermodel.py#L155

It seems like it is the number of values in the params.

**Comment by Pythonatheart** [comment]
@haifeng-jin  Thank you for your reply. 
It is hard to determine the total parameters for max_model_size.
If using AlexNet as an example, total params is ~62M, and GPU memory consumed is ~1.0 GB.
So for 24GB GPU memory, does that mean max_model_size = 62M x 24 = 1.5Billion?
Probably not, and I don't know whether GPU mem is freed up after each trial (i.e. clear session?). 
So, it's at best a trial and error approach until I get some idea of max_model_size? 
What are your thoughts? Any good pointers? What would you set as a max_model_size for a RTX Titan? 
Thank you once again. I appreciate your time and thoughts on this.

**Comment by haifeng-jin** [comment]
@Pythonatheart I really don't know the answer. You may submit an issue to Keras Tuner to ask. 
Actually, I have never exceeded the memory limit with our search space.
I have around 11GB of GPU memory.
Thanks.

**Comment by Pythonatheart** [comment]
@haifeng-jin Thank you for your reply again.
The master branch of AutoKeras incorporating this argument for max_model_size uses tensorflow 2.2? I have been receiving errors relating to methods apparently only exists in tensorflow 2.2 nightly.
I will test this out when tensorflow 2.2 stable is released.
