### ISSUE TITLE
Loading saved model causes Unknown layer: Normalization

### ISSUE THREAD

**Issue by dadebulba** [keras-team/autokeras#1105]
### Bug Description

When I load a saved model with `tf.keras.models.load_model(model_dir, custom_objects=custom)` I get the following error: "Unknown layer: Normalization".
If I try to add the `ak.Normalization` layer to `custom_objects` I get the following error:
"TypeError: __init__() got an unexpected keyword argument 'trainable'"
### Bug Reproduction
Code for reproducing the bug:

```
from tensorflow.keras.models import load_model
import tensorflow as tf
import autokeras as ak

custom = ak.CUSTOM_OBJECTS
# custom['Normalization'] = ak.Normalization
model = load_model(model_dir, custom_objects=custom)

```
### Setup Details
Include the details about the versions of:
 - OS type and version: Ubuntu 18.04
 - Python: 3.6
 - autokeras:  1.0.2
 - tensorflow: 2.1.0

### Additional context
I'm running the code on a PyCharm environment

Thank you

**Comment by GuileCyclone** [comment]
@dadebulba I also met this problem，and I fixed this by adding 

> 'Normalization': tensorflow.keras.layers.experimental.preprocessing.Normalization

to CUSTOM_OBJECTS.This bug has fixed in master branch（not release now,with tf 2.2.0rc3）.

**Comment by dadebulba** [comment]
Thanks, it works
