### ISSUE TITLE
Is the child modal's information extractable?

### ISSUE THREAD

**Issue by AronWater** [keras-team/autokeras#1118]
If I set the max trail to be 10. How could I get the architecture of all the 10 child models(I know that the architecture will be printed but I would like to get it by code)?  Thanks!

**Comment by haifeng-jin** [comment]
You need to use AutoModel.tuner to get the tuner. Then use Keras Tuner's methods to get the models. Please refer to https://keras-team.github.io/keras-tuner/documentation/tuners/#get_best_models-method
