### ISSUE TITLE
TextClassifier does not allow embedding size to be larger than 20000

### ISSUE THREAD

**Issue by qingquansong** [keras-team/autokeras#1121]
### Bug Description

The bug appears when the number of distinct tokens in the text dataset is larger than 20000 (default).

### Bug Reproduction

https://github.com/datamllab/automl-in-action-notebooks/blob/master/3.3.1-Task-API-TextClassifier-20newsgroup.ipynb

### Setup Details
Include the details about the versions of:
 - OS type and version:
 - Python: 
 - autokeras: 1.0.2
 - keras-tuner:
 - scikit-learn:
 - numpy:
 - pandas:
 - tensorflow: 2.1.0

**Comment by haifeng-jin** [comment]
The bug is fixed by https://github.com/keras-team/autokeras/pull/1087
