### ISSUE TITLE
Model `summary()` method does not work for some of the exported best Keras models

### ISSUE THREAD

**Issue by qingquansong** [keras-team/autokeras#1125]
### Bug Description

Model `summary()` method does not work for some of the exported best Keras models found by the task APIs (have tried text and structured classifier)

### Bug Reproduction
It seems only ImageClassifier API example works well.

### Setup Details
Include the details about the versions of:
 - OS type and version:
 - Python: 
 - autokeras: 1.0.2
 - keras-tuner:
 - scikit-learn:
 - numpy:
 - pandas:
 - tensorflow: 2.1.0

**Comment by haifeng-jin** [comment]
This bug is fixed in the master branch.
