### ISSUE TITLE
Out of memory, process killed when running on CPUs

### ISSUE THREAD

**Issue by gladomat** [keras-team/autokeras#1128]
### Bug Description
When I run `ak.StructuredDataRegressor` on 16 CPUs I get an out of memory error:

`[Mo Mai 11 10:40:26 2020] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-c2.scope,task=python,pid=9246,uid=1000
[Mo Mai 11 10:40:26 2020] Out of memory: Killed process 9246 (python) total-vm:41532112kB, anon-rss:28066312kB, file-rss:0kB, shmem-rss:0kB
[Mo Mai 11 10:40:26 2020] oom_reaper: reaped process 9246 (python), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
[Mo Mai 11 10:40:50 2020] mce: CPU9: Package temperature above threshold, cpu clock throttled (total events = 2704986)
[Mo Mai 11 10:40:50 2020] mce: CPU7: Package temperature above threshold, cpu clock throttled (total events = 2704982)
`

### Bug Reproduction
Code for reproducing the bug:

`regressor = ak.StructuredDataRegressor(max_trials=100, 
                                       column_types=data_type)

regressor.fit(x=X_train, 
              y=y_train,
              validation_data=(X_val, y_val))`

Data used by the code:

A structued dataset with 50000 entries, `test_size=0.1`.

### Expected Behavior
I expect the model search to be complete without the out of memory error. That would be nice :-).

### Setup Details
Include the details about the versions of:
 - OS type and version: Ubuntu 19.10
 - Python: 3.7.6
 - autokeras: 1.0.2
 - keras-tuner: 1.0.1
 - scikit-learn: 0.22.1
 - numpy: 1.18.1
 - pandas: 1.0.2
 - tensorflow: 2.1.0

**Comment by garar** [comment]
Memory leak can be reproduced using titanic example from documentation:

```python
import autokeras as ak

# Initialize the structured data classifier.
clf = ak.StructuredDataClassifier(max_trials=1000)
# Feed the structured data classifier with training data.
clf.fit(
    # The path to the train.csv file.
    'titanic-train.csv',
    # The name of the label column.
    'survived',
    verbose=False)
# Predict with the best model.
# predicted_y = clf.predict('titanic-eval.csv')
# Evaluate the best model with testing data.
print('\n\n\n')
print(clf.evaluate('titanic-eval.csv', 'survived'))
print('\n\n\n')
```


It doesn't happen if I used keras-tuner on its own.

**Comment by haifeng-jin** [comment]
How much is your memory please? I cannot reproduce the error on my machine.

**Comment by gladomat** [comment]
I have 32 GB of memory and I'm running it on the CPUs not on the video card.
