### ISSUE TITLE
AutoKeras is super limited without fit_generator

### ISSUE THREAD

**Issue by cibic89** [keras-team/autokeras#1152]
### Reason
AutoKeras is awesome and incredibly powerful. I feel it is limited to toy problems as I cannot find practical methods to use it with augmented images

### Question
Any ideas how to extract data from Keras data generators if they can fit in memory that is?

**Comment by PascalSchimmler** [comment]
Have a look at the last answer in this issue: https://github.com/keras-team/autokeras/issues/984

**Comment by cibic89** [comment]
> 
> 
> Have a look at the last answer in this issue: #984

Thank you!
