### ISSUE TITLE
Unable to select tuner for StructuredDataClassifier

### ISSUE THREAD

**Issue by garar** [keras-team/autokeras#1154]
### Bug Description

StructuredDataClassifier constructor doesn't allow to choose different tuner than Greedy tuner.

I'm not sure if it is intentional.

### Bug Reproduction

https://github.com/keras-team/autokeras/blob/master/autokeras/tasks/structured_data.py#L200

### Expected Behavior

StructuredDataClassifier should allow selecting different tuners.

### Setup Details
Include the details about the versions of:
 - OS type and version: Ubuntu 16.04
 - Python: 3.7.7
 - autokeras: 1.0.2
 - keras-tuner: 1.0.1
 - scikit-learn: 0.23.1
 - numpy: 1.18.4
 - pandas: 1.0.3
 - tensorflow: 2.1.0

**Comment by haifeng-jin** [comment]
We just open up this arg in every API. Please try AutoKeras 1.0.3. Thanks.
