### ISSUE TITLE
Does ImageClassifier support tf.data ?

### ISSUE THREAD

**Issue by lsrock1** [keras-team/autokeras#1158]
### Bug Description
Does ImageClassifier support tf.data ?
When I run fit function with tf.Data, it occurs an error.

### Bug Reproduction
Code for reproducing the bug:
```
# dataset and validation_data are tf.data
model.fit(x=dataset, y=None,
                          epochs=epochs,
                          callbacks=callbacks,
                          validation_data=validation_data,
                          fit_on_val_data=False,
                          **kwargs)

  File "/home/ocrusr/miniconda3/envs/tf_2.1/lib/python3.7/site-packages/autokeras/auto_model.py", line 239, in fit
    validation_split=validation_split)
  File "/home/ocrusr/miniconda3/envs/tf_2.1/lib/python3.7/site-packages/autokeras/auto_model.py", line 316, in _prepare_data
    val_x, val_y = validation_data
ValueError: too many values to unpack (expected 2)
```
Data used by the code:

### Setup Details
Include the details about the versions of:
 - OS type and version:
 - Python: 3.7.6
 - autokeras: 1.0.2 master
 - keras-tuner: 1.0.1
 - scikit-learn: 0.23.1
 - numpy: 1.16.4
 - pandas: 1.0.3
 - tensorflow: 2.2.0

**Comment by cibic89** [comment]
Can you include the code for generating the train and validation sets? I suspect that you are trying to unpack data from the generator prematurely (for AutoKeras)

**Comment by lsrock1** [comment]
@cibic89 Thanks for your kindly answer. I tried without the evaluation data, I failed for some reason related to #984 .

**Comment by cibic89** [comment]
> 
> 
> @cibic89 Thanks for your kindly answer. I tried without the evaluation data, I failed for some reason related to #984 .

Did you resolve thisw @lsrock1 ?
