### ISSUE TITLE
Inconsistent solutions to previous issues: WARNING:tensorflow:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.

### ISSUE THREAD

**Issue by castrovictor** [keras-team/autokeras#1162]
### Bug Description
In order to use ImageClassifier, it's necessary to use tensorflow 2.1.0 as discussed on [issue 1141](https://github.com/keras-team/autokeras/issues/1141) 

Now, if we want to save the model in a .h5 file and load it later, it's necessary to use tf-nightly as disccused on [issue 929](https://github.com/keras-team/autokeras/issues/929)

But the problem is when I load the model with `tensorflow.keras.models.load_model`, I get a warning saying basically that the weights could not be loaded. 
`WARNING:tensorflow:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
`

After some research, it seems this bug was solved with tensorflow 2.2.0, [issue 37968 ](https://github.com/tensorflow/tensorflow/issues/37968)from tensorflow repository describes it. 

So, to solve this last problem, we would have to use tensorflow 2.2.0 (apparently), but then I am in conflict with the first problem described in this post, I need to use tensorflow 2.1.0 to make it work. What can I do? Suggestions?

I quote the developer because I think it's an interesting issue he would like to know. @haifeng-jin

**Comment by castrovictor** [comment]
Update: the issue is not that the weights cannot be loaded, but the optimizer. In fact, the problem is that you get a warning saying the optimizer could not be saved whe you try to export the model to a file.

**Comment by haifeng-jin** [comment]
We just had a new release 1.0.3. It runs fine with tf 2.2.0. You may have a try. Thanks.

**Comment by castrovictor** [comment]
Thanks. Just tried and works with tf 2.2.0, but the warning persists. Anyway, I did some research and the warning states that the state of the optimizer can't be saved, i.e we could not continue the training from the same point it finished. So it's not a problem at all.

**Comment by castrovictor** [comment]
By they way, I think we can close this issue.
