### ISSUE TITLE
Why are the example/mnist.py accuracy different 1.0.2 and 1.0.3 ?

### ISSUE THREAD

**Issue by zmqp111** [keras-team/autokeras#1167]
Hi, 

I tested 1.0.2 and 1.0.3 example/mnist.py, and the results of the two acuracy are different.

autokeras version 1.0.2's accuracy is more than 0.9.
but 1.0.3's accuracy is less then 0.4.

Why are the example/mnist.py accuracy different 1.0.2 and 1.0.3 ?

**I am not sure of the accuracy predicted and best model in autokeras.**

Because my project uses the tensorflow 2.2.0 version, so, I have to use autokeras version 1.0.3. but problem with accuracy, my project fails.
(tf 2.2.0, autokeras 1.0.2 have AttributeError: 'tuple' object has no attribute 'shape' error.)

What should I ?

**Comment by haifeng-jin** [comment]
Would you provide your code and dataset? It would be great if they are in a colab notebook. I can take a look to see why.
