### ISSUE TITLE
Loading saved model causes Unknown layer: Normalization

### ISSUE THREAD

**Issue by zmqp111** [keras-team/autokeras#1169]
I try to saved best model, and load. 

but i have 
Loading saved model causes Unknown layer: Normalization error

autokeras : 1.0.2
tf : 2.1.0

* i cannot upgrade autokeras version, because autokeras 1.0.3's accuracy is not good.

**Comment by haifeng-jin** [comment]
You can pass the normalization layer as a custom object while you load the model.
Would you please provide your dataset? So that we can tune our algorithm to see why it doesn't perform good. Thanks.
