### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by hello10242048** [keras-team/autokeras#1193]
TypeError                                 Traceback (most recent call last)

<ipython-input-13-1d3b99aa0089> in <module>()
     16         #outputs=[ak.ClassificationHead()],
     17         max_trials=global_max_trials,
---> 18         objective = 'val_loss',
     19         #overwrite=global_overwrite,
     20         #tuner='bayesian'

2 frames

/usr/local/lib/python3.6/dist-packages/autokeras/engine/tuner.py in __init__(self, oracle, hypermodel, preprocessors, **kwargs)
     36                  preprocessors=None,
     37                  **kwargs):
---> 38         super().__init__(oracle, hypermodel, **kwargs)
     39         self.preprocessors = nest.flatten(preprocessors)
     40         self._finished = False

TypeError: __init__() got an unexpected keyword argument 'name'

**Comment by haifeng-jin** [comment]
This is because your are using a different version of Keras Tuner. Please follow this guide to install the correct version.
https://autokeras.com/#installation
