### ISSUE TITLE
Can LSTM network be applied?

### ISSUE THREAD

**Issue by Lay4U** [keras-team/autokeras#1196]
This is my model, and I am wondering how I can optimize it by applying autokeras.

```
model = tf.keras.Sequential([

        tf.keras.layers.LSTM(64, return_sequences=True),
        tf.keras.layers.LSTM(128, return_sequences=False),
        tf.keras.layers.Dense(20)
])

model.compile(optimizer='adam', loss='mae')

hist = model.fit(x_train, y_train, epochs=50, batch_size=32, verbose=0)
```

**Comment by castrovictor** [comment]
If you read the docs or the paper, you will find out that autokeras finds an architecture using a variation of bayesian modification. Not sure  if you can just improve an actual model with autokeras

**Comment by haifeng-jin** [comment]
Yes, we can although I haven't tested. You can use RNNBlock to do it with AutoModel.
https://autokeras.com/block/#rnnblock-class
https://autokeras.com/tutorial/customized/
