### ISSUE TITLE
ImageDataGenerator for autokeras

### ISSUE THREAD

**Issue by sademakn** [keras-team/autokeras#1198]
### Code Example

```python
```

**Comment by telyn** [comment]
I'm also struggling with this. I've seen rumours of people managing to get it to work.

[This post](https://github.com/keras-team/autokeras/issues/984#issuecomment-629828148) is the main thing I've been cribbing from.
[#1075](https://github.com/keras-team/autokeras/issues/1075#issuecomment-636543611) is also an important read I think.

Putting them together I built myself a docker image:

```dockerfile
RUN apt update && apt install -y git \                                                                                                                 
 && python3 -m pip install git+https://github.com/keras-team/keras-tuner.git@master \                                                                  
 && python3 -m pip install git+https://github.com/keras-team/autokeras.git \                                                                               
 && python3 -m pip install Pillow  
```

And I've been trying to get it working since then using code like this:
```python
from os import listdir
from os.path import isfile, join
import tensorflow as tf
import numpy
import random
import PIL
import autokeras

BATCH_SIZE = 1
IMG_HEIGHT = 128
IMG_WIDTH = 128

image_generator = tf.keras.preprocessing.image.ImageDataGenerator(
                                              horizontal_flip=True,
                                              validation_split=0.2)

train_generator = image_generator.flow_from_directory('training-data',
                                                      batch_size=BATCH_SIZE,
                                                      target_size=(IMG_HEIGHT, IMG_WIDTH),
                                                      class_mode="categorical",
                                                      shuffle=True)
test_generator = image_generator.flow_from_directory('test-data',
                                               batch_size=BATCH_SIZE,
                                               target_size=(IMG_HEIGHT, IMG_WIDTH),
                                               class_mode="categorical",
                                               shuffle=True)

batch_num = 0

def callable_iterator(generator):
    global batch_num
    for img_batch, targets_batch in generator:
        batch_num = batch_num + 1
        if batch_num == 20000:
            # have to break otherwise fit will run forever???
            break
        yield img_batch, targets_batch

print("Beginning set generation")
training_set = tf.data.Dataset.from_generator(lambda: callable_iterator(train_generator), output_types=(tf.float32, tf.float32), output_shapes=(tf.TensorShape([BATCH_SIZE, IMG_HEIGHT, IMG_WIDTH, 3]), tf.TensorShape([BATCH_SIZE, 3])))
test_set = tf.data.Dataset.from_generator(lambda: callable_iterator(test_generator), output_types=(tf.float32, tf.float32))

classifier = autokeras.ImageClassifier(project_name='classifier',
                                       objective='val_accuracy',
                                       max_trials=10)
print("beginning fit")
classifier.fit(training_set,
               steps_per_epoch=100,
               callbacks=[
                   tf.keras.callbacks.EarlyStopping(patience=2),
                   tf.keras.callbacks.ModelCheckpoint(filepath="models/{epoch:02d}-{val_loss:.2f}.h5"),
                   tf.keras.callbacks.CSVLogger("ak-classifier.csv"),
                   tf.keras.callbacks.ProgbarLogger()
               ],
               epochs=200)
```

But I still haven't got it working. By tweaking various bits (tensorflow version, steps_per_epoch, batch_size, epochs) I've managed to shift the errors around, but never eradicate them. Because I'm running it in a docker container modifying tensorflow/autokeras itself is super painful. I'm currently following a lead (noticed my autokeras install line didn't have the full git URL) and if that fails my next step is going to be starting to modify tensorflow to get some debug logging in there.

**Comment by sademakn** [comment]
> I'm also struggling with this. I've seen rumours of people managing to get it to work.
> 
> [This post](https://github.com/keras-team/autokeras/issues/984#issuecomment-629828148) is the main thing I've been cribbing from.
> [#1075](https://github.com/keras-team/autokeras/issues/1075#issuecomment-636543611) is also an important read I think.
> 
> Putting them together I built myself a docker image:
> 
> ```dockerfile
> RUN apt update && apt install -y git \                                                                                                                 
>  && python3 -m pip install git+https://github.com/keras-team/keras-tuner.git@master \                                                                  
>  && python3 -m pip install git+https://github.com/keras-team/autokeras.git \                                                                               
>  && python3 -m pip install Pillow  
> ```
> 
> And I've been trying to get it working since then using code like this:
> 
> ```python
> # yes I realise my imports are a mess, leave me alone
> from os import listdir
> from os.path import isfile, join
> import tensorflow as tf
> import numpy
> import random
> import PIL
> import autokeras
> 
> BATCH_SIZE = 1
> IMG_HEIGHT = 128
> IMG_WIDTH = 128
> 
> image_generator = tf.keras.preprocessing.image.ImageDataGenerator(
>                                               horizontal_flip=True,
>                                               validation_split=0.2)
> 
> train_generator = image_generator.flow_from_directory('training-data',
>                                                       batch_size=BATCH_SIZE,
>                                                       target_size=(IMG_HEIGHT, IMG_WIDTH),
>                                                       class_mode="categorical",
>                                                       shuffle=True)
> test_generator = image_generator.flow_from_directory('test-data',
>                                                batch_size=BATCH_SIZE,
>                                                target_size=(IMG_HEIGHT, IMG_WIDTH),
>                                                class_mode="categorical",
>                                                shuffle=True)
> 
> batch_num = 0
> 
> def callable_iterator(generator):
>     global batch_num
>     for img_batch, targets_batch in generator:
>         batch_num = batch_num + 1
>         if batch_num == 20000:
>             # have to break otherwise fit will run forever???
>             break
>         yield img_batch, targets_batch
> 
> print("Beginning set generation")
> training_set = tf.data.Dataset.from_generator(lambda: callable_iterator(train_generator), output_types=(tf.float32, tf.float32), output_shapes=(tf.TensorShape([BATCH_SIZE, IMG_HEIGHT, IMG_WIDTH, 3]), tf.TensorShape([BATCH_SIZE, 3])))
> test_set = tf.data.Dataset.from_generator(lambda: callable_iterator(test_generator), output_types=(tf.float32, tf.float32))
> 
> classifier = autokeras.ImageClassifier(project_name='classifier',
>                                        objective='val_accuracy',
>                                        max_trials=10)
> print("beginning fit")
> classifier.fit(training_set,
>                steps_per_epoch=100,
>                callbacks=[
>                    tf.keras.callbacks.EarlyStopping(patience=2),
>                    tf.keras.callbacks.ModelCheckpoint(filepath="models/{epoch:02d}-{val_loss:.2f}.h5"),
>                    tf.keras.callbacks.CSVLogger("ak-classifier.csv"),
>                    tf.keras.callbacks.ProgbarLogger()
>                ],
>                epochs=200)
> ```
> 
> But I still haven't got it working. By tweaking various bits (tensorflow version, steps_per_epoch, batch_size, epochs) I've managed to shift the errors around, but never eradicate them. Because I'm running it in a docker container modifying tensorflow/autokeras itself is super painful. I'm currently following a lead (noticed my autokeras install line didn't have the full git URL) and if that fails my next step is going to be starting to modify tensorflow to get some debug logging in there.

I gave autokeras up and returned to keras-tuner!!!

**Comment by haifeng-jin** [comment]
Currently AutoKeras is not supporting data generator. You may only use tf.data.Dataset with tf record as an alternative. Thanks.

**Comment by haifeng-jin** [comment]
Let's use #984 to track all the generator related questions.
