### ISSUE TITLE
ModuleNotFoundError: No module named 'kerastuner' -- Autokeras==1.0.3

### ISSUE THREAD

**Issue by leandroimail** [keras-team/autokeras#1202]
### Bug Reproduction
Code for reproducing the bug:

>>> import autokeras
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leandro/.local/share/virtualenvs/Moira-jyrwulee/lib/python3.7/site-packages/autokeras/__init__.py", line 1, in <module>
    from autokeras.auto_model import AutoModel
  File "/home/leandro/.local/share/virtualenvs/Moira-jyrwulee/lib/python3.7/site-packages/autokeras/auto_model.py", line 11, in <module>
    from autokeras import blocks
  File "/home/leandro/.local/share/virtualenvs/Moira-jyrwulee/lib/python3.7/site-packages/autokeras/blocks/__init__.py", line 3, in <module>
    from autokeras.blocks.basic import ConvBlock
  File "/home/leandro/.local/share/virtualenvs/Moira-jyrwulee/lib/python3.7/site-packages/autokeras/blocks/basic.py", line 3, in <module>
    from kerastuner.applications import resnet
ModuleNotFoundError: No module named 'kerastuner'

Data used by the code: 

### Setup Details
Include the details about the versions of:
 - OS type and version:
 - Python: 3.7
 - autokeras: 
 - keras-tuner: --
 - scikit-learn:
 - numpy:
 - pandas:
 - tensorflow: 2.2.0

**Comment by leandroimail** [comment]
When I install manually keras-tuner (pip install keras-tuner) the following error is thrown

>>> import autokeras
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leandro/.local/share/virtualenvs/Moira-jyrwulee/lib/python3.7/site-packages/autokeras/__init__.py", line 48, in <module>
    check_kt_version()
  File "/home/leandro/.local/share/virtualenvs/Moira-jyrwulee/lib/python3.7/site-packages/autokeras/utils/utils.py", line 67, in check_kt_version
    'ok.'.format(version=kerastuner.__version__)
ImportError: The Keras Tuner package version needs to be at least 1.0.2rc0
for AutoKeras to run. Currently, your Keras Tuner version is
1.0.1. Please upgrade with
`$ pip install git+https://github.com/keras-team/keras-tuner.git@1.0.2rc0#egg=keras-tuner-1.0.2rc0`.
You can use `pip freeze` to check afterwards that everything is ok. 



Sorry if it was boring, I just want to help.

**Comment by haifeng-jin** [comment]
Please uninstall it and install it with this command. `pip install git+https://github.com/keras-team/keras-tuner.git@1.0.2rc0#egg=keras-tuner-1.0.2rc0`

**Comment by leandroimail** [comment]
> Please uninstall it and install it with this command. `pip install git+https://github.com/keras-team/keras-tuner.git@1.0.2rc0#egg=keras-tuner-1.0.2rc0`

I tried and it worked. Thks!

**Comment by AliMassoud** [comment]
> Please uninstall it and install it with this command. `pip install git+https://github.com/keras-team/keras-tuner.git@1.0.2rc0#egg=keras-tuner-1.0.2rc0`

I am facing the same issue and this one didn't work out for me,
it threw an error saying:
"ERROR: Could not find a version that satisfies the requirement keras-tuner-1-0-2rc0 (unavailable) (from versions: none)
ERROR: No matching distribution found for keras-tuner-1-0-2rc0 (unavailable)
"

**Comment by RenuPatel1** [comment]
Please use below code in Anaconda cmd prompt
pip install keras
pip install keras-tuner

**Comment by AliMassoud** [comment]
> Please use below code in Anaconda cmd prompt
> pip install keras
> pip install keras-tuner

I did, it did not work, even if I pipped it on an anaconda cmd and launched Pycharm from Anaconda. but I copied the code to a jupyter notebook and everything worked fine!
One more question if you I may ask,
I uploaded the jupyter notebook to an Azure notebook to train my model there, however, the keras-tuner kept giving an error states the following:
"AttributeError: module 'tensorflow.keras.layers.experimental.preprocessing' has no attribute 'RandomRotation'"
(even though I have the latest version of TensorFlow.
any idea, please?

**Comment by Gudusxx** [comment]
> Please use below code in Anaconda cmd prompt pip install keras pip install keras-tuner

thanks man
