### ISSUE TITLE
hypermodel value error with ImageClassifier

### ISSUE THREAD

**Issue by dcdj99** [keras-team/autokeras#1205]
### Bug Description

i get this error when using the image classifier function to test out auto-keras:

<line 180, in get_hypermodel
    'The `hypermodel` argument should be either '

ValueError: The `hypermodel` argument should be either a callable with signature `build(hp)` returning a model, or an instance of `HyperModel`.>

### Bug Reproduction
Code for reproducing the bug:

import tensorflow as tf
from tensorflow import keras
import autokeras as ak

img_gen = ImageDataGenerator(rotation_range=30,
                                  width_shift_range=0.1,
                                  height_shift_range=0.1,
                                  rescale=1/255,
                                  shear_range=0.15,
                                  zoom_range=0.15,
                                  horizontal_flip=True,
                                  validation_split=0.2,
                                  fill_mode='nearest')

train_gen = img_gen.flow_from_directory(train_data,
                                             target_size= target_size,
                                             #color_mode='grayscale',
                                             shuffle=True, 
                                             seed=42, 
                                             batch_size= batch_size,
                                             class_mode='categorical',
                                             subset='training'
                                             )

test_gen = img_gen.flow_from_directory(train_data, 
                                            target_size= target_size,
                                            #color_mode='grayscale',
                                            shuffle=True, 
                                            seed=42, 
                                            batch_size= batch_size,
                                            class_mode='categorical',
                                            subset='validation'
                                            )

model = ak.ImageClassifier(num_classes=42, 
                             loss='categorical_crossentropy',
                             metrics='accuracy', 
                             objective='val_accuracy'
                             )
model.fit(train_gen,test_gen,epochs = 20)

Data used by the code:

various images of different categories

### Setup Details
Include the details about the versions of:
 - OS type and version: windows
 - Python: latest
 - autokeras: 1.0.3
 - keras-tuner: 1.0.2rc0
 - scikit-learn: latest
 - numpy:latest
 - pandas:latest
 - tensorflow: 2.2

**Comment by dcdj99** [comment]
i get the same error when using the examples from the autokeras webpage

**Comment by castrovictor** [comment]
Currently, autokeras does not support generators given by flow_from_directory. I tried to wrap them into a tf.Dataset because they are supposed to be supported, but there is a problem when fitting it. I opened an issue about that.

**Comment by dcdj99** [comment]
> Currently, autokeras does not support generators given by flow_from_directory. I tried to wrap them into a tf.Dataset because they are supposed to be supported, but there is a problem when fitting it. I opened an issue about that.

Thanks for replying, although flow_from_directory is not supported, it doesnt seems to be the source of my error. ive tried other datas including the examples given in the website and i still get the same error. i'm wondering if there is an issue with keras tuner?

**Comment by haifeng-jin** [comment]
Please refer to #984 for how to use generators.

**Comment by dcdj99** [comment]
> Please refer to #984 for how to use generators.

Hi, please see above comment that the error is not due to the generators.
