### ISSUE TITLE
Set minimum epochs before early stopping

### ISSUE THREAD

**Issue by sword134** [keras-team/autokeras#1209]
### Feature Description
The ability to run a minimum amount of epochs before early stopping is activated. For example. Min_epochs=100, the model will run a minimum of 100 epochs before early stopping will be able to stop the model training.
### Code Example

```classifier = ak.AutoModel(
    inputs=input_node, outputs=output_node, max_trials=100, min_epochs=100, overwrite=True)
```

**Comment by FreeGoldRush** [comment]
A GPU sitting idle just begs for more epochs, but other than that, can someone give a clear explanation of why this is needed and when it would be useful?
