### ISSUE TITLE
visualize network

### ISSUE THREAD

**Issue by RengarWang** [keras-team/autokeras#1217]
I successfully run the MNIST example, but I want to visualize the network, and I don't know how to do it

**Comment by haifeng-jin** [comment]
```
model = clf.export_model()
```
You can get a keras model in this way.
Then refer to this one for how to visualize it. https://keras.io/api/utils/model_plotting_utils/

**Comment by RengarWang** [comment]
> ```
> model = clf.export_model()
> ```
> 
> You can get a keras model in this way.
> Then refer to this one for how to visualize it. https://keras.io/api/utils/model_plotting_utils/

thanks！
