### ISSUE TITLE
Save top 3 best models

### ISSUE THREAD

**Issue by abdulsam** [keras-team/autokeras#1220]
I want to save not just one but the top 3 best performing models created by AutoKeras. I want to analyze the differences between them. How can I save them?

**Comment by haifeng-jin** [comment]
You can use `AutoModel.tuner.get_best_models(3)`

**Comment by abdulsam** [comment]
> You can use `AutoModel.tuner.get_best_models(3)`

Throwing an error:
`AttributeError: type object 'AutoModel' has no attribute 'tuner'`

**Comment by abdulsam** [comment]
At the same time, how can I export these trained weights of 3 best models?

**Comment by haifeng-jin** [comment]
@abdulsam You can use a for loop to do so.
```python
for index, model in enumerate(AutoModel.tuner.get_best_models(3)):
  model.save('model' + str(index) + '.h5')
```

**Comment by abdulsam** [comment]
@haifeng-jin While loading the saved models, it is giving a warning
`WARNING:tensorflow:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.`

I ignored this warning because I can train it again. But while using fit() method on the loaded model, it is showing this error:
`ValueError: Shapes (None, 1) and (None, 10) are incompatible`

**Comment by haifeng-jin** [comment]
I guess it is because of the label encoding? We do a one-hot encoding for the labels under the hood.
