### ISSUE TITLE
Hyperband Tuner only trains for 2 Epochs

### ISSUE THREAD

**Issue by naitslup** [keras-team/autokeras#1235]
### Bug Reproduction
Code for reproducing the bug:

import numpy as np
import autokeras as ak

x_train = np.ones([500,10])
y_train = np.zeros([500])

model = ak.StructuredDataRegressor(tuner='hyperband')
model.fit(x_train, y_train, epochs=100)

Data used by the code:

### Setup Details
Include the details about the versions of:
 - OS type and version: Win10
 - Python: 3.7.6
 - autokeras: 1.0.3
 - keras-tuner: 1.0.2rc0
 - scikit-learn: 0.21.3
 - numpy: 1.18.1
 - pandas: 1.0.1
 - tensorflow: 2.2.0

**Comment by haifeng-jin** [comment]
Yes, that is the property of the hyperband tuner.
It use successive halving which only train the models for less epochs at first and select the good ones and further train.
