### ISSUE TITLE
On model.fit, at Starting New Trial include trial number

### ISSUE THREAD

**Issue by dcohron** [keras-team/autokeras#1258]
I hope that this would be easy to implement.  When training a model, in the output along with "Starting new trial" include the trial number which would count up to the "max_trials" parameter passed in the model definition.  Would look like "Starting new trial- #1/50" and increment up to the max-trials (in this case 50).  

This would allow monitoring of the progress of the training, just like the output currently displays the count of the epochs ("Epoch 1/10", "Epoch 2/10", etc.)

Thank you for your consideration and thank you for the tool.

**Comment by haifeng-jin** [comment]
I believe this would be a feature in Keras Tuner. The prints are there.

**Comment by dcohron** [comment]
Ah, thank you much.
