### ISSUE TITLE
model.fit is quick at first - very slow in subsequent trials

### ISSUE THREAD

**Issue by hughpearse** [keras-team/autokeras#1262]
# Bug Description
With a configuration of 2 trials and 1 epoch, model training takes approximately 60s per epoch on the first trial. Then on the second trial the estimated time jumps from 1 minute per epoch to 3 hours per epoch. This was also observed with a configuration of 1 trial and 1 epoch when the trial is executed successfully (in Jupyter notebook) and then started again.

If I was to guess the cause of the issue, I would say that the model is initially living in memory but gets written to disk at some point, and then is repeatedly read from disk after a trial increment or in subsequent executions.

### Bug Reproduction
```python
clf = ak.ImageClassifier(max_trials=2)
clf.fit(X_train, y_train, epochs=1)
```

Notice that the output says ETA: 2:40:43
```python
INFO:tensorflow:Reloading Oracle from existing project ./image_classifier/oracle.json
INFO:tensorflow:Reloading Tuner from ./image_classifier/tuner0.json

Search: Running Trial #2
etc...
  35/1051 [..............................] - ETA: 2:40:43 - loss: 1.9709 - accuracy: 0.3464
```

Data used by the code:
https://www.kaggle.com/c/digit-recognizer/data
https://keras.io/api/datasets/mnist/
or mnist.load_data()

### Expected Behavior
Each epoch should complete in approximately 60 seconds.

### workaround
Run the following command to speed up the training
```bash
foo@bar:~$ rm -rf ./image_classifier/
```

### Additional context
working as designed - https://github.com/hughpearse/kaggle/blob/master/digit-recognizer/entry.ipynb
not working - [slow-version.ipynb.zip](https://github.com/keras-team/autokeras/files/5006228/slow-version.ipynb.zip)

### Setup Details
Include the details about the versions of:
 - OS type and version: Mac OS Catalina 10.15.4
 - Python: 3.6
 - autokeras: 
 - keras-tuner: git+https://github.com/keras-team/keras-tuner.git@1.0.2rc1
 - scikit-learn:
 - numpy: 1.18.5
 - pandas:
 - tensorflow:

**Comment by haifeng-jin** [comment]
This is as expected. We try very different models in the first several trials to quickly locate the models suitable for the dataset. The second model is much larger than the first one.
