### ISSUE TITLE
ImageGenerator

### ISSUE THREAD

**Issue by tl-yang** [keras-team/autokeras#129]
### Suggested Name

ImageGenerator

### Task Description

Generating new images similar to the training images. The input data should be a set of images without labels.

### Evaluation Metrics

Human Evaluation

### Benchmark Datasets

CelebA

### Reason

NA

### Solution

Do a baseline solution first.
Do not search for different architectures.
Just use a default architecture, which only has dynamic parts in the input and output sizes.

**Comment by tlatkowski** [comment]
Hi @tl-yang , @jhfjhfj1 

Is there any progress on this? In current version of code (0.4.0) i could only find the implementation of DCGAN for image generation, but it is not possible to use NAS for searching optimal generator architecture. 

Moreover, **NetworkModule** is currently restricted to 1D output, are you planning to implement **NetworkModule** that supports 3D output generation?

BR
