### ISSUE TITLE
AutoKeras version compatibility with TensorFlow

### ISSUE THREAD

**Issue by zhulingchen** [keras-team/autokeras#1294]
I would like to have a compatibility list of versions of AutoKeras versus TensorFlow.

Like which version of TensorFlow was AutoKeras 1.0.0 has been tested against; which version of TensorFlow as AutoKeras 1.0.1 has been tested against, etc.?

It would be great if there is a version comparison table, similar to the table of TensorFlow version versus CUDA version as below:

Version | Python version | Compiler | Build tools | cuDNN | CUDA
tensorflow-2.3.0 | 3.5-3.8 | GCC 7.3.1 | Bazel 3.1.0 | 7.6 | 10.1
tensorflow-2.2.0 | 3.5-3.8 | GCC 7.3.1 | Bazel 2.0.0 | 7.6 | 10.1
tensorflow-2.1.0 | 2.7, 3.5-3.7 | GCC 7.3.1 | Bazel 0.27.1 | 7.6 | 10.1
tensorflow-2.0.0 | 2.7, 3.3-3.7 | GCC 7.3.1 | Bazel 0.26.1 | 7.4 | 10.0

Thank you very much!

**Comment by zhulingchen** [comment]
> 
> 
> Since every release is fixing important bugs. We always expect the users to use the latest version.

That would be a little bit too ambitious.

To be more specific, which version of autokeras would have no issue with TensorFlow 2.1.0? 1.0.0?

**Comment by haifeng-jin** [comment]
Yes. I think 1.0.0 is compatible with TF 2.1.0.
AutoKeras is still not stable enough and under active development.
We are still pending on some future features of tensorflow.
So in the near future, we will always based on the latest TensorFlow version.

I think from 1.0.3 on AutoKeras will raise an error if your TensorFlow version is not compatible.
