### ISSUE TITLE
 ImportError: cannot import name 'image_preprocessing' from tensorflow.python.keras.layers.preprocessing import image_preprocessing as image_ops

### ISSUE THREAD

**Issue by Lucgald** [keras-team/autokeras#1296]
I tried to run autokeras and was hit with the error message upon import autokeras:

from tensorflow.python.keras.layers.preprocessing import image_preprocessing as image_ops
ImportError: cannot import name 'image_preprocessing'

I am currently on:

Keras: 2.2.4
Tensorflow: 2.1.0
OS: Windows 10

Thank you for your help

**Comment by Miremax** [comment]
1. Download **https://raw.githubusercontent.com/tensorflow/tensorflow/v2.3.0/tensorflow/python/keras/layers/preprocessing/image_preprocessing.py** - it just doesnt exist in tf 2.0-2.1
2. Comment all the _@tf.keras.utils.register_keras_serializable(package='Text')_, that will couse an error.

After that tf object detection api works fine, as for me

**Comment by hudson-dev** [comment]
Any update on this issue?

**Comment by haifeng-jin** [comment]
The solution is to use TF 2.3 with AutoKeras 1.0.10.

**Comment by parthlathiya42** [comment]
@haifeng-jin Solved the issue upgrading tensorflow.
