### ISSUE TITLE
Remove titanic fixture from the repo

### ISSUE THREAD

**Issue by haifeng-jin** [keras-team/autokeras#1307]
Please follow the style of how the wine example downloads the datasets to remove the usages of titanic fixtures in the /tests directory.
Just replace these two lines should be good enough.
https://github.com/keras-team/autokeras/blob/master/tests/utils.py#L45-L46

Refer to these 4 lines for how to get the paths.
https://github.com/keras-team/autokeras/blob/master/docs/py/structured_data_classification.py#L15-L19

**Comment by haifeng-jin** [comment]
@mandalbiswadip Would you like to take this one?

**Comment by mandalbiswadip** [comment]
@haifeng-jin sure. Will take this up.
