### ISSUE TITLE
Can't re-fit or make predictions on keras functional model after loading it

### ISSUE THREAD

**Issue by spamz23** [keras-team/autokeras#1311]
### Bug Description

After I use autokeras to search for an optimal model I export it and save it. Then after loading it, I can't `predict()` to make predictions or `fit()` to retrain the model. Both methods give the same error:
`UnimplementedError:  Cast float to string is not supported
	 [[node functional_1/Cast (defined at <ipython-input-8-4b9d4ec3c8be>:5) ]] [Op:__inference_train_function_17076]`´

### Bug Reproduction

[Bug repro on googlecolab](https://colab.research.google.com/drive/144UVhoMhEKTb2Tmu0d7Dq5aknnXnIl1q?usp=sharing)

Data used by the code:
Dummy data using sklearn `make_classification()`

### Expected Behavior

Expected the keras functional model `predict()` method to work with a 'numpy.ndarray', as well as `fit()` method. Should be able to refit the model

### Setup Details
Include the details about the versions of:
 - OS type and version: Google colab
 - Python: 3.6
 - autokeras: 1.0.7
 - keras-tuner: 1.0.2rc1
 - scikit-learn: 0.22.2.post1
 - numpy: 1.18.5
 - pandas: 1.0.5
 - tensorflow: 2.3.0

**Comment by haifeng-jin** [comment]
For StructuredDataClassifier or Regressor, after you export the model, you should convert your data to np.unicode first before feeding into the exported model.

**Comment by spamz23** [comment]
Thanks, it worked. But how can I re-fit the exported model (deleting weights)?

**Comment by haifeng-jin** [comment]
I forgot how. But there must be a solution. This is more like a Keras question. If anyone has an answer, welcome to post here.

**Comment by devGichanLee** [comment]
my issue
```
print(type(m_search)) # <class 'autokeras.tasks.structured_data.StructuredDataClassifier'>
model1 = m_search.export_model()
print(type(model1)) # <class 'tensorflow.python.keras.engine.functional.Functional'>
```
after export_model(), it's changed to 'Functional', not to <class 'tensorflow.python.keras.engine.training.Model'>. with this message 'WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.' load_model() has also same message

after load or export, the model can't be re-fit or predict anymore with this message which wasn't when the model is StructuredDataClassifier
`valueerror: shapes (none, 1) and (none, 3) are incompatible`
