### ISSUE TITLE
filter size as a parameter for convblock

### ISSUE THREAD

**Issue by CuriousSingularity** [keras-team/autokeras#1318]
hi, 

May I know why the filter size is not available as a parameter for the convblock? Could we have this feature instead of hardcoded values? Even for the DenseBlock too.

**Comment by haifeng-jin** [comment]
We didn't expect people would want to set this parameter. Currently, they are not fixed but tunable. So anyone who is interested in this feature is welcome to pull request. Thanks!

**Comment by CuriousSingularity** [comment]
Alright, no problem. I will work on it and create pull request. 👍
