### ISSUE TITLE
AudioClassifier

### ISSUE THREAD

**Issue by jhfjhfj1** [keras-team/autokeras#132]
### Suggested Name

AudioClassifier

### Task Description

Each training instance is an audio. The target is a single label.
There should be an audio loader, which loads the audio files into numpy arrays.

### Evaluation Metrics

Accuracy.

### Benchmark Datasets

[GTZAN Genre Collection](http://marsyasweb.appspot.com/download/data_sets/)

**Comment by ffxz** [comment]
where is the AudioClassifier
