### ISSUE TITLE
The dataset should at least contain 2 batches to be split

### ISSUE THREAD

**Issue by Cariaga** [keras-team/autokeras#1326]
```
import pandas as pd
import numpy as np
import autokeras as ak
from tensorflow.keras.datasets import cifar10
from tensorflow.python.keras.utils.data_utils import Sequence
from tensorflow.keras.models import model_from_json
import os
def build_model():
    input_layer =ak.Input()
    cnn_layer = ak.ConvBlock()(input_layer)
    cnn_layer2 =ak.ConvBlock()(cnn_layer)
    dense_layer =ak.DenseBlock()(cnn_layer2)
    dense_layer2 =ak.DenseBlock()(dense_layer)
    output_layer =ak.ClassificationHead(num_classes=10)(dense_layer2)
    automodel =ak.auto_model.AutoModel(input_layer,output_layer,max_trials=20,seed=123,project_name="automl")
    return automodel

def build():
    ((trainX,trainY),(testX,testY))=cifar10.load_data()
    automodel = build_model()
    automodel.fit(trainX,trainY,validation_split=0.2,epochs=40,batch_size=64)#error here

if __name__ == '__main__':
    build()

```

i got this error even trying the example in the docs

```

    automodel.fit(trainX,trainY,validation_split=0.2,epochs=40,batch_size=64)
  File "S:\Anaconda\envs\tensor37\lib\site-packages\autokeras\auto_model.py", line 276, in fit
    validation_split=validation_split,
  File "S:\Anaconda\envs\tensor37\lib\site-packages\autokeras\auto_model.py", line 409, in _prepare_data
    dataset, validation_split
  File "S:\Anaconda\envs\tensor37\lib\site-packages\autokeras\utils\data_utils.py", line 47, in split_dataset
    "The dataset should at least contain 2 batches to be split."
ValueError: The dataset should at least contain 2 batches to be split.


```

autokeras 1.0.8
keras 2.3.1
tensorflow 2.1.0
numpy 1.19.1
pandas 1.1.1
keras-tuner 1.0.2rc1
python 3.7.7

**Comment by jisho-iemoto** [comment]
I also have the same issue, maybe after I upgraded Auto-Keras and other packages relating to it.
Since it took somewhat a long time, I guess keras-tuner should be taken into account as well (this is just my opinion without any evidence).

**Comment by haifeng-jin** [comment]
I will look into this and try to fix it in the next release. Thanks.

**Comment by jisho-iemoto** [comment]
With my case, this issue disappeared after updating keras-tuner to 1.0.2rc2.
However, the same issue as titled "Parallel workers on same machine randomly throw exceptions when starting #301" occurs instead :<

**Comment by jisho-iemoto** [comment]
Hello.
Just after updating Auto-Keras to 1.0.9 (I guess other relating files are also updated automatically, if needed), the same issue is still found.

**Comment by haifeng-jin** [comment]
I don't think it is related to the bug. But it may break other parts of the code. So I suggest you use virtualenv to install AutoKeras to separate the dependencies.

**Comment by jisho-iemoto** [comment]
Thanks a lot for the comment.
I've built up the environment by Anaconda 3 and it is already virtual.  And the errors above have been solved step by step.

Though I don't know whether it helps solve the bug or not, I tried to "reduce the output" (original: 3 kinds in a list, trial: a single in a list), which was also in vain due to the same error.

**Comment by ciessielski** [comment]
I have the same issue error.

autokeras: 1.0.9
kerastuner: 1.0.2rc2
tensorflow: 2.3.1

**Comment by haifeng-jin** [comment]
A temporary work around can be split the data to training and validation before calling fit. Use validation_data arg to pass the validation set.

**Comment by haifeng-jin** [comment]
@ciessielski @jisho-iemoto @Cariaga Would you confirm that the training data you are using has number of samples that at least 2 times the batch_size. For example, if your batch_size is 32 (default), then your data should at least contain 33 samples.

**Comment by jisho-iemoto** [comment]
Hello, @haifeng-jin 
I'm now trying based on your suggestion that I should explicitly set varidation_data.
(FYI, X has 30k rows * (30-100 cols * 24 groups), Y has [30k rows*4 cols, 30k list, 30k list])

It seems that the "SPLIT #" bug can be swept by this means, however, I encountered "kernel died" errors instead :<  
I'll take some more time to see it.

**Comment by jisho-iemoto** [comment]
The error was as follows (I also tried on a newly prepared virtual environment):

---
 Non-OK-status: GpuLaunchKernel(FillPhiloxRandomKernelLaunch<Distribution>, num_blocks, block_size, 0, d.stream(), gen, data, size, dist) status: Internal: no kernel image is available for execution on the device
---

**Comment by jisho-iemoto** [comment]
> The error was as follows (I also tried on a newly prepared virtual environment):
> 
> ## Non-OK-status: GpuLaunchKernel(FillPhiloxRandomKernelLaunch, num_blocks, block_size, 0, d.stream(), gen, data, size, dist) status: Internal: no kernel image is available for execution on the device

Additional parameters here, I'm running the code on GPU:

autokeras 1.0.9
keras 2.3.1
tensorflow 2.3.0
tensorflow-gpu 2.3.1
numpy 1.19.2
pandas 1.0.5
keras-tuner 1.0.2rc2
python 3.7.8

CuDNN 7.6
CUDA v10.1
GPU: GeForce GTX 960M

**Comment by haifeng-jin** [comment]
I really haven't seen this error before.
Would you try the same code running without GPU? Just mask the GPU out using env var.

**Comment by jisho-iemoto** [comment]
> I really haven't seen this error before.
> Would you try the same code running without GPU? Just mask the GPU out using env var.

Sorry, I'm a total stranger and amateur, so I can't understand which file for me to manipulate.  For instance, "config.py" in a certain folder?

**Comment by jisho-iemoto** [comment]
> > I really haven't seen this error before.
> > Would you try the same code running without GPU? Just mask the GPU out using env var.
> 
> Sorry, I'm a total stranger and amateur, so I can't understand which file for me to manipulate. For instance, "config.py" in a certain folder?

Sorry again, I managed to run the codes on CPU.
Yes, it worked only 1 epoch, but then, the error message of "Function call stack: train_function" appeared and stopped.

**Comment by jisho-iemoto** [comment]
> > > I really haven't seen this error before.
> > > Would you try the same code running without GPU? Just mask the GPU out using env var.
> > 
> > 
> > Sorry, I'm a total stranger and amateur, so I can't understand which file for me to manipulate. For instance, "config.py" in a certain folder?
> 
> Sorry again, I managed to run the codes on CPU.
> Yes, it worked only 1 epoch, but then, the error message of "Function call stack: train_function" appeared and stopped.

The actual cause seems in connection with KerasTuner.  The error message in detail is below:

tensorflow.python.framework.errors_impl.UnimplementedError:  Cast double to string is not supported
	 [[node functional_1/Cast (defined at C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\kerastuner\engine\tuner.py:142) ]] [Op:__inference_train_function_50491]

Function call stack:
train_function
---
All the data used are converted into float32 and there is not a string data and/or columns with string data type.  I wonder what's wrong with this.  And I guess this issue is far from what originally made me in trouble.

**Comment by neel04** [comment]
Still having this error :( I can confirm that I am indeed sending >set batch size but apparently in the very end of the data, it fails

**Comment by neel04** [comment]
Apparently, its still trying to `split` the data despite explicitly providing the validation set? 🤔

**Comment by neel04** [comment]
Converting to numpy arrays actually seems to help///
