### ISSUE TITLE
Final fit would lead to overfitting?

### ISSUE THREAD

**Issue by toohsk** [keras-team/autokeras#1329]
When I'm finding the best model with using the EarlyStopping callbacks in the fit function, it works as I'm expecting.
But I found that when I defined the EarlyStopping callback in the `fit` function and after the number of trials leads to `max_trials` the final search starts without the EarlyStopping.

And I thought setting a higher number of epochs than necessary would lead to overfitting with the training dataset and it would be the poor performance even if it found the best architecture.
What do you think?

And with my suggestion, it would be a quite simple change, how about setting the `early_stopping_inserted` flag to True when  `callbacks` has EarlyStopping callback. 
Because, within the `autokeras/engine/tuner.py`'s `search` function, the `early_stopping_inserted` flag is set to False when the user set EarlyStopping callback in the ordinary `fit` function.
What do you think about this, too?
And if it seems good, is it okay to do this by myself?

**Comment by haifeng-jin** [comment]
We remove the early stopping only in two cases: https://github.com/keras-team/autokeras/blob/master/autokeras/engine/tuner.py#L170.
If validation data is not provided, we will run a final fit with the entire training data provided by the user.
So we don't have extra data for validation. So we cannot do early stopping.
If you provide your own validation data and pass the early stopping in the callbacks, we won't need to run the final fit.
