### ISSUE TITLE
Can't find the required version of keras-tuner.

### ISSUE THREAD

**Issue by Samar-080301** [keras-team/autokeras#1336]
I was trying the auto-keras package, but while importing it as `from autokeras.image_supervised import ImageClassifier, load_image_dataset`. 
It prompted that keras-tuner not found. 
So I did `pip install keras-tuner`. It installed `keras-tuner==1.0.1`.  But when I ran the import statement again, it prompted that keras tuner v1.0.2 is required which can be downloaded from `https://github.com/keras-team/keras-tuner.git@1.0.2rc1#egg=keras-tuner-1.0.2rc1%60`.
But this link gave `Error 404`. 
[Colab notebook link](https://colab.research.google.com/drive/131wA6fan6Z_Y5BMIIvQ4MYvLY3vmSftM?usp=sharing)
Please help me!

**Comment by haifeng-jin** [comment]
`pip3 install git+https://github.com/keras-team/keras-tuner.git@1.0.2rc1`
This command works on my computer.

**Comment by Samar-080301** [comment]
Thanks a lot for your help!
