### ISSUE TITLE
How to load a saved AutoKeras StructeredDataClassifier model for prediction?

### ISSUE THREAD

**Issue by Samar-080301** [keras-team/autokeras#1340]
### Bug Reproduction
Code for reproducing the bug:    [Colab Link](https://colab.research.google.com/drive/1Mt8r5JO6yIawV7hl-TtCyaeHcpr5nhhm?usp=sharing)
Data used by the code:
Provided in the notebook.
### Expected Behavior
`NotImplementedError: Save or restore weights that is not an instance of `tf.Variable` is not supported in h5, use `save_format='tf'` instead. Got a model or layer MultiCategoryEncoding with weights [<tensorflow.python.keras.engine.base_layer_utils.TrackableWeightHandler object at 0x7fdbd14abac8>`
### Setup Details
Include the details about the versions of:
 - OS type and version: Google Colaboratory Notebook with no GPUs or TPUs
 - Python:  3.6.9
 - autokeras: 1.0.8
 - keras-tuner:  1.0.2
 - scikit-learn:   0.22.2.post1
 - numpy:  1.18.5
 - pandas:  1.0.5
 - tensorflow:  2.3.0

**Comment by haifeng-jin** [comment]
Yes, please use a name that doesn't end with 'H5' or 'h5' when saving the model.

**Comment by devGichanLee** [comment]
> Yes, please use a name that doesn't end with 'H5' or 'h5' when saving the model.

then it will be automatically saved tf's <class 'tensorflow.python.keras.engine.functional.Functional'>, and doesn't work after load_model.

**Comment by haifeng-jin** [comment]
Would you paste the error of how it doesn't run after load?
You can try to change the data type to string before feeding to the model.
