### ISSUE TITLE
How to read the best model architecture?

### ISSUE THREAD

**Issue by AntonioDomenech** [keras-team/autokeras#1364]
Where can I find the architecture of the best model saved and how can I visualize it?

**Comment by dcohron** [comment]
I have a similar issue.  I think that if you can load the best model you could then run keras.Model.summary() (summary method in the keras Model class)  on that model to see the architecture.  Should be simple as that.

I have tried accessing the best model two ways:
1)  Via the try/except in the documentation for tf or h5 formats.  This does not work because I have a custom metric (F1 Score) which triggers a "ValueError: Unable to restore custom object of type _tf_keras_metric currently.  Please make sure that the layer implements `get_config`and `from_config` when saving. In addition, please use the `custom_objects` arg when calling `load_model()`."
2)  Diggine a bit deeper I tried loaded = tf.saved_model.load(best_model_path) from  ...model/best_model/saved_model.pb which triggers a "ValueError: The same saveable will be restored with two names: layer_with_weights-6/encoding layers/0/_table/.ATTRIBUTES/table"

Any help here would be most appreciated.

**Comment by AntonioDomenech** [comment]
Thanks for the information, I'll look into that! If I get any solution I will let you know for sure.

**Comment by AntonioDomenech** [comment]
> @dcohron not related to the question, but I've also encountered the same problem when using custom metrics. I kind of solved it using an answer from another [issue](https://github.com/keras-team/autokeras/issues/1257#issuecomment-674132595).

This doesn't seem to work for me, I keep getting the same error:

Traceback (most recent call last):
  File "/home/a/Documents/Sign_recognition/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 417, in _revive_layer_from_config
    generic_utils.serialize_keras_class_and_config(class_name, config))
  File "/home/a/Documents/Sign_recognition/venv/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 175, in deserialize
    printable_module_name='layer')
  File "/home/a/Documents/Sign_recognition/venv/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 347, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/home/a/Documents/Sign_recognition/venv/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 296, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: Custom>MultiCategoryEncoding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ASL_recognition1.py", line 48, in <module>
    model = tf.keras.models.load_model('/home/a/Documents/autokeras/structured_data_classifier/best_model')
  File "/home/a/Documents/Sign_recognition/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 187, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/home/a/Documents/Sign_recognition/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 121, in load
    path, options=options, loader_cls=KerasObjectLoader)
  File "/home/a/Documents/Sign_recognition/venv/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 633, in load_internal
    ckpt_options)
  File "/home/a/Documents/Sign_recognition/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 194, in __init__
    super(KerasObjectLoader, self).__init__(*args, **kwargs)
  File "/home/a/Documents/Sign_recognition/venv/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 130, in __init__
    self._load_all()
  File "/home/a/Documents/Sign_recognition/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 215, in _load_all
    self._layer_nodes = self._load_layers()
  File "/home/a/Documents/Sign_recognition/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 315, in _load_layers
    layers[node_id] = self._load_layer(proto.user_object, node_id)
  File "/home/a/Documents/Sign_recognition/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 341, in _load_layer
    obj, setter = self._revive_from_config(proto.identifier, metadata, node_id)
  File "/home/a/Documents/Sign_recognition/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 359, in _revive_from_config
    self._revive_layer_from_config(metadata, node_id))
  File "/home/a/Documents/Sign_recognition/venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 428, in _revive_layer_from_config
    'call.'.format(cls=class_name))
RuntimeError: Unable to restore a layer of class Custom>MultiCategoryEncoding. Layers of class Custom>MultiCategoryEncoding require that the class be provided to the model loading code, either by registering the class using @keras.utils.register_keras_serializable on the class def and including that file in your program, or by passing the class in a keras.utils.CustomObjectScope that wraps this load call.

**Comment by AntonioDomenech** [comment]
@dcohron to display the architecture of the best model I found I could do the next:

1. export the model:
model = clf.export_model()

2. Ask for the model Sumary:
model.summary()

if you add this at the end of the AutoKeras code, you'll be able to see the architecture of the model in the Terminal.

I got the following message for a random trial I did:
_________________________________________________________________
Layer (type)                             Output Shape                             Param #   
==============================================================
input_1 (InputLayer)                 [(None, 84)]                                   0         
_________________________________________________________________
multi_category_encoding       (Mul (None, 84)                               0         
_________________________________________________________________
normalization (Normalization      (None, 84)                                169       
_________________________________________________________________
dense (Dense)                           (None, 512)                             43520     
_________________________________________________________________
batch_normalization (BatchNo   (None, 512)                              2048      
_________________________________________________________________
re_lu (ReLU)                              (None, 512)                                 0         
_________________________________________________________________
dense_1 (Dense)                        (None, 32)                              16416     
_________________________________________________________________
batch_normalization_1 (Batch    (None, 32)                                128       
_________________________________________________________________
re_lu_1 (ReLU)                           (None, 32)                                  0         
_________________________________________________________________
dense_2 (Dense)                       (None, 101)                              3333      
_________________________________________________________________
classification_head_1 (Softm     (None, 101)                                0         
==============================================================
Total params: 65,614
Trainable params: 64,357
Non-trainable params: 1,257
_________________________________________________________________


This doesn't solve the problem about loading the best model but at least it gives you the opportunity to recreate the best model 
 architecture on tensorflow by yourself, which gives much less problems. I hope this is helpful :)

**Comment by krishdb38** [comment]
@AntonioDomenech I have the same structure in the model.
when I save the best model 

and load model using 
model = tf.keras.models.load_model("model_auto_keras_rc_50_trials.h5")

I cant load saying Unknown layer MultiCategory Encoding.

did you solve the problem?
![image](https://user-images.githubusercontent.com/45994360/149435352-f39ed593-d72e-4301-be8b-e36e01be47c5.png)

I don't know how to solve this

**Comment by AntonioDomenech** [comment]
@krishdb38 You didn't load the custom objects created by AutoKeras, that's why you get the error if I'm correct. You can load any custom objects in the load_model() command.

So insted of loading the model the way you did it:
`model = tf.keras.models.load_model("model_auto_keras_rc_50_trials.h5")`

You should load the model with custom objects like this:
`model = tf.keras.models.load_model("model_auto_keras_rc_50_trials.h5", custom_objects=ak.CUSTOM_OBJECTS)`

Note that `ak.CUSTOM_OBJECTS` are the custom objects from AutoKeras, so you need to import AutoKeras when loading the model.

I hope this helps :)

**Comment by krishdb38** [comment]
@AntonioDomenech 
thank you I solved the problem the same as you mentioned which later I found in documentation later after posting .

Thank you

**Comment by AntonioDomenech** [comment]
@krishdb38 Apologies for not responding quicker! I'm happy you could solve it!
