### ISSUE TITLE
Question: How to continue to make new trials from previous trials?

### ISSUE THREAD

**Issue by medphisiker** [keras-team/autokeras#1365]
Hello,
Since the selection of the optimal parameters can be very time consuming. Often libraries for Bayesian selection of optimal parameters of machine learning models allow us to save the study object. In order to be able to load it in the future and continue the selection of the optimal parameters further from the very same place where we stopped.

for example optuna library

```
import optuna
from optuna.samplers import TPESampler

study = optuna.create_study(direction="maximize", sampler=TPESampler(n_startup_trials=50))
study.optimize(objective_0, n_trials=100)
joblib.dump(study, 'save_path') # to save hyperparameter object
study = joblib.load(tuna_path) # to restore hyperparameter object
study.optimize(objective_0, n_trials=100) # to continue for a new 100 trials from previous 100 trials (from 100 to 200 trial)
```

AutoKeras has similar functionality ?

for example

```
clf = ak.StructuredDataClassifier(
    overwrite=True,
    max_trials=3) # 3 trials
# Feed the tensorflow Dataset to the classifier.
clf.fit(train_set, epochs=10) # fit

Then save clf  object like
clf.save_to_file('....')
Then 
clf.load_from_file.
Then 
clf.fit_for_next_trials from previous ?
```

**Comment by haifeng-jin** [comment]
https://autokeras.com/tutorial/faq/#how-to-resume-a-previously-killed-run

Not sure if this answers your question.

**Comment by medphisiker** [comment]
Hello, thanks for the answer.

According to the link to the documentation you provided:

"This feature is controlled by the overwrite argument of AutoModel or any other task APIs. It is set to False by default, which means it would not overwrite the contents of the directory. In other words, it will continue the previous fit."

That is, we just need to create a new object and just run the search again, and it will continue from that place ?

**Comment by haifeng-jin** [comment]
You don't need to create a new object. You just run the same .py file again.
If you want to create a new object, please make sure all the configs remains the same as the previous one.

**Comment by medphisiker** [comment]
Thanks for the answer. I will experiment =)
