### ISSUE TITLE
Partly Pre-trained model

### ISSUE THREAD

**Issue by mshahriarish** [keras-team/autokeras#1369]
Hello,
I have been trying to use AutoKeras for my project. However, I have a problem that I do not know how to solve. The model I would like to train is an encoder-decoder. However, I would like to pre-train the encoder part, freeze its weights, and then train the decoder section. Is it possible to do it in AutoKeras?

Thank you in advance.
Regards,

**Comment by haifeng-jin** [comment]
Unfortunately, AutoKeras cannot support such training at the moment. It can be done with a custom training loop using Keras. May be Keras Tuner can support this if you need to tune the hyperparameters.
