### ISSUE TITLE
ERROR: Package 'dataclasses' requires a different Python: 3.8.3 not in '>=3.6, <3.7'

### ISSUE THREAD

**Issue by shanghaiyangming** [keras-team/autokeras#1383]
ERROR: Package 'dataclasses' requires a different Python: 3.8.3 not in '>=3.6, <3.7'

**Comment by shanghaiyangming** [comment]
When I use pip install to install, the following error message is displayed: ERROR: Package'dataclasses' requires a different Python: 3.8.3 not in'>=3.6, <3.7'

**Comment by shanghaiyangming** [comment]
The documentation is very clear：
Currently, AutoKeras is only compatible with Python >= 3.5 and TensorFlow >= 2.3.0
Why can't it be installed?

**Comment by mklosi** [comment]
what are you installing with pip, just autokeras?   `pip install autokeras` ?
