### ISSUE TITLE
SupervisedTimeseriesDataPipeline.predict method returns zero results

### ISSUE THREAD

**Issue by mklosi** [keras-team/autokeras#1397]
The following code: 

```python
from autokeras import TimeseriesForecaster
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.DataFrame({
    "feature1": range(10, 110),
    "feature2": range(20, 120),
    "label": range(30, 130),
})
df_X = df.drop("label", axis=1)
df_y = df[["label"]]

df_train_X, df_test_X, df_train_y, df_test_y = train_test_split(
    df_X, df_y, test_size=0.1,
)

auto_model = TimeseriesForecaster(
    max_trials=1,
    lookback=1,
)

auto_model.fit(
    x=df_train_X,
    y=df_train_y,
    epochs=10,
    validation_split=0.1,
)

predicted_y = auto_model.predict(df_test_X)
```

should produce a "predicted_y" ndarray of size 10, instead it returns 0 elements.

I think the issue is here - https://github.com/keras-team/autokeras/blob/master/autokeras/tasks/time_series_forecaster.py#L101

This line should instead just be `lower_bound = self.predict_from`

@haifeng-jin    tell me if I'm missing smth. If not, I can push out PR.

**Comment by haifeng-jin** [comment]
The usage of this class is a little bit tricky. You may refer to https://github.com/keras-team/autokeras/blob/master/tests/integration_tests/task_api_test.py#L105

**Comment by mklosi** [comment]
I ran the tests with the change and all of them pass.
