### ISSUE TITLE
Predict function fails with multi modal task

### ISSUE THREAD

**Issue by pavanagrawal123** [keras-team/autokeras#1402]
### Bug Description
If we train a model with a multi-modal approach, described in the documentation, we can't run predict on the model with the following error: 
 ValueError: Failed to find data adapter that can handle input: (<class 'tuple'> containing values of types {"<class 'tensorflow.python.data.ops.dataset_ops.MapDataset'>"}), <class 'NoneType'>
### Bug Reproduction
Code for reproducing the bug:
https://colab.research.google.com/drive/1aNDKe73yQElXUznjN0z99kx_GbBMOjRm?usp=sharing

This is the example given by autokeras, with a predict function added to the end showing the error. 
Data used by the code:
Random numpy data

### Setup Details
Include the details about the versions of:
 - OS type and version: Ubuntu 18.04. 3 LTS
 - Python: 3.6.7
 - autokeras: 1.0.10
 - keras-tuner: 1.0.2rc3
 - scikit-learn: 0.22.2.post1
 - numpy: 1.18.5
 - pandas: 1.1.2
 - tensorflow: 2.3.0

### Additional context
If this is an easy bug to fix, if you can point out where I should be looking, I can open a PR.

Further, if I'm doing something wrong in the example, let me know and I can also help correct some of the documentation in this area. 

Thanks so much!

**Comment by winston-p** [comment]
I also just hit this exact bug with AutoKeras ver 1.0.10. May I know if there is any planned release date for ver 1.0.11 that should fix this bug?

**Comment by winston-p** [comment]
Hi @haifeng-jin  I faced the same bug in v1.0.10 and just tested with the latest v1.0.11 - the issue is still unresolved. Can you confirm that it's in the bugfix for v1.0.11?
