### ISSUE TITLE
Compatibility with tensorflow 2.4.0

### ISSUE THREAD

**Issue by q-55555** [keras-team/autokeras#1412]
### Bug Description
When installing tensorflow > 2.3.1 (for example : tf-nightly or tensorflow==2.4.0r0), ImageClassifier fails with this error:

Here is the colab :
https://colab.research.google.com/drive/18GAYjUFnOqeVR-SZ3Fcc7RfxRVTUd0SN?usp=sharing

`
def wrapper(*args, **kwargs):
       """Call target, and fall back on dispatchers if there is a TypeError."""
try:
       return target(*args, **kwargs)
       TypeError: cast() missing 1 required positional argument: 'dtype'
`

### Bug Reproduction

import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.python.keras.utils.data_utils import Sequence
import autokeras as ak
(x_train, y_train), (x_test, y_test) = mnist.load_data()

clf = ak.ImageClassifier(
    overwrite=True,
    max_trials=1)

clf.fit(x_train, y_train, epochs=10)

predicted_y = clf.predict(x_test)
print(predicted_y)
print(clf.evaluate(x_test, y_test))

### Setup Details
Include the details about the versions of:
 - OS type and version: Windows 10
 - Python: 3.8
 - autokeras: 1.0.10
 - keras-tuner: 1.0.2rc4
 - scikit-learn: 0.23.2
 - numpy: 1.18.5
 - pandas: 1.1.3
 - tensorflow: 2.4.0r0

**Comment by haifeng-jin** [comment]
This is a very important bug, I will look into this. Thanks.

**Comment by CandelaAr1992** [comment]
Somebody solved this problem?
