### ISSUE TITLE
Image Regression with Matching Input and Output Shapes 

### ISSUE THREAD

**Issue by ghost** [keras-team/autokeras#1421]
### Feature Description
Currently, with ImageRegressor we can take in (batch_size, width, height, channels) and predict (batch_size, n_features). However,  I want to feed in a batch of images (batch_size, width, height, channels) and predict each pixel in another image with the same dimensions (batch_size, width, height, channels). This idea might be extendable to ImageClassifier as well.

### Reason
Being able to have different sized outputs will make the package more versatile. For my hobby project, I want to take in a spectrogram of a song and remove the vocals. Others may want to implement filters for images. Other ideas likely exist as well.

### Solution
There are probably several ways to implement this. From an ease of use point of view, the best way would be to have an argument in ak.ImageRegressor to specify which type of output shape is desired - (batch_size, n_features) or (batch_size, width, height, channels). An example endstate where training_data and validation_data are generators providing batches of the same shape is below.

```
clf = ak.ImageRegressor(max_trials=3)
clf.fit(x=training_data, validation_data=validation_data, output_dim_shape='same')
```

**Comment by gregegg** [comment]
I think I too am interested in this capability.  Is this related to #1429?
