### ISSUE TITLE
Text classifier has trouble running BERT

### ISSUE THREAD

**Issue by raghuvarranvh** [keras-team/autokeras#1460]
### Bug Description

When I try to run a sample code using the text classifier, there is error in loading the BERT checkpoint from google cloud system

> "UnimplementedError: File system scheme 'gs' not implemented (file: 'gs://cloud-tpu-checkpoints/bert/keras_bert/uncased_L-12_H-768_A-12\vocab.txt')"

complete trace : 
[autokeras_error.txt](https://github.com/keras-team/autokeras/files/5671936/autokeras_error.txt)

### Bug Reproduction
Code for reproducing the bug:
```
import autokeras as ak
import numpy as np
clf = ak.TextClassifier(overwrite=True,max_trials=10)
clf.fit(tr_x, tr_y, epochs=1,validation_data=(te_x,te_y))
```
Data used by the code:
```
tr_x = np.array(["If you like adult comedy cartoons, like South Park, then this is nearly a similar format about the small adventures of three teenage girls at Bromwell High. Keisha, Natella and Latrina have given exploding sweets and behaved like bitches, I think Keisha is a good leader. There are also small stories going on with the teachers of the school. There's the idiotic principal, Mr. Bip, the nervous Maths teacher and many others. The cast is also fantastic, Lenny Henry's Gina Yashere, EastEnders Chrissie Watts, Tracy-Ann Oberman, Smack The Pony's Doon Mackichan, Dead Ringers' Mark Perry and Blunder's Nina Conti. I didn't know this came from Canada, but it is very good. Very good!",\
        "good movie",    
        "I basically skimmed through the movie but just enough to catch watch the plot was about. To tell you the truth it was kind of boring to me and at some spots it didn't make sense. The only reason I watched this movie in the first place was to see CHACE CRAWFORD!!! He is so hot, but in this movie his hair was kind of weird. But still hot.<br /><br />However, despite how hot CHACE is, it really did not make up for the film. I guess the plot isn't that bad but what really threw me over was the fact that they cuss in like every sentence. Is it that hard to express your anger without saying the F word every time?The cussing was annoying and the whole flashy, camera shaking thing gave me a headache.<br /><br />All in all, although the plot was OK, I found the film to be a bore and over dramatic. That's why I only cut to scenes with CHACE in it. LOL Anyways, not worth renting unless your a die-hard fan of a specific cast member like I was. Oh yeah the cast was Hot. The girls were HOT!!! But CHACE IS THE BEST!!"])
tr_y=np.array(['pos','pos','neg'])
te_x = np.array(["worst Movie","Nice one"])
te_y = np.array(['bad','good'])
```

### Setup Details
Include the details about the versions of:
 - OS type and version:
 - Python: 3.7.9
 - autokeras: 
 - keras-tuner:1.0.3
 - scikit-learn:0.23.2
 - numpy:1.18.5
 - pandas:1.1.5
 - tensorflow:2.3.0

### Additional context

I installed the following procedure for installation using anaconda prompt:
```
conda create -n env_autokeras
conda activate env_autokeras
conda install tensorflow
pip install git+https://github.com/keras-team/keras-tuner.git
pip install autokeras
```

**Comment by ibrahimishag** [comment]
> ### Bug Description
> When I try to run a sample code using the text classifier, there is error in loading the BERT checkpoint from google cloud system
> 
> > "UnimplementedError: File system scheme 'gs' not implemented (file: 'gs://cloud-tpu-checkpoints/bert/keras_bert/uncased_L-12_H-768_A-12\vocab.txt')"
> 
> complete trace :
> [autokeras_error.txt](https://github.com/keras-team/autokeras/files/5671936/autokeras_error.txt)
> 
> ### Bug Reproduction
> Code for reproducing the bug:
> 
> ```
> import autokeras as ak
> import numpy as np
> clf = ak.TextClassifier(overwrite=True,max_trials=10)
> clf.fit(tr_x, tr_y, epochs=1,validation_data=(te_x,te_y))
> ```
> 
> Data used by the code:
> 
> ```
> tr_x = np.array(["If you like adult comedy cartoons, like South Park, then this is nearly a similar format about the small adventures of three teenage girls at Bromwell High. Keisha, Natella and Latrina have given exploding sweets and behaved like bitches, I think Keisha is a good leader. There are also small stories going on with the teachers of the school. There's the idiotic principal, Mr. Bip, the nervous Maths teacher and many others. The cast is also fantastic, Lenny Henry's Gina Yashere, EastEnders Chrissie Watts, Tracy-Ann Oberman, Smack The Pony's Doon Mackichan, Dead Ringers' Mark Perry and Blunder's Nina Conti. I didn't know this came from Canada, but it is very good. Very good!",\
>         "good movie",    
>         "I basically skimmed through the movie but just enough to catch watch the plot was about. To tell you the truth it was kind of boring to me and at some spots it didn't make sense. The only reason I watched this movie in the first place was to see CHACE CRAWFORD!!! He is so hot, but in this movie his hair was kind of weird. But still hot.<br /><br />However, despite how hot CHACE is, it really did not make up for the film. I guess the plot isn't that bad but what really threw me over was the fact that they cuss in like every sentence. Is it that hard to express your anger without saying the F word every time?The cussing was annoying and the whole flashy, camera shaking thing gave me a headache.<br /><br />All in all, although the plot was OK, I found the film to be a bore and over dramatic. That's why I only cut to scenes with CHACE in it. LOL Anyways, not worth renting unless your a die-hard fan of a specific cast member like I was. Oh yeah the cast was Hot. The girls were HOT!!! But CHACE IS THE BEST!!"])
> tr_y=np.array(['pos','pos','neg'])
> te_x = np.array(["worst Movie","Nice one"])
> te_y = np.array(['bad','good'])
> ```
> 
> ### Expected Behavior
> ### Setup Details
> Include the details about the versions of:
> 
> * OS type and version:
> * Python: 3.7.9
> * autokeras:
> * keras-tuner:1.0.3
> * scikit-learn:0.23.2
> * numpy:1.18.5
> * pandas:1.1.5
> * tensorflow:2.3.0
> 
> ### Additional context
> I installed the following procedure for installation using anaconda prompt:
> 
> ```
> conda create -n env_autokeras
> conda activate env_autokeras
> conda install tensorflow
> pip install git+https://github.com/keras-team/keras-tuner.git
> pip install autokeras
> ```

I ran into the same error when I set the max_trials to 3.
However, it works well when I execute the code in Google Colab!.

**Comment by raghuvarranvh** [comment]
So, is there some missing dependency? Any direction in how to solve this?

**Comment by gerwim** [comment]
Yes, it seems the GS file system API is not build for Windows (see https://github.com/tensorflow/tensorflow/issues/38477). The only way to get this working (that I know of, without compiling any sources) is to don't run with Windows (e.g. Ubuntu / MacOS / Google Colab).

**Comment by v2thegreat** [comment]
This might be the same as seen in #1489. This is on Ubuntu, tried on two different machines

**Comment by haifeng-jin** [comment]
I didn't know that. Thanks for the answers. Hopefully, it would be supported in Windows soon.

**Comment by eschibli** [comment]
Where does AutoKeras cache the downloads? It shouldn't be difficult to work around the issue by manually downloading the pertinent files.

**Comment by haifeng-jin** [comment]
We use this function to download the file. All the caching mechanisms are relying on this function.
https://www.tensorflow.org/api_docs/python/tf/keras/utils/get_file

**Comment by haifeng-jin** [comment]
You mean it doesn't even cache the weights on your disk after the download?
