### ISSUE TITLE
This can be refactored

### ISSUE THREAD

**Issue by Anselmoo** [keras-team/autokeras#1463]
### Bug Description

The `dir_path` should be in front of the for-loop.

https://github.com/keras-team/autokeras/blob/8532e5de6fbe438ddea0eceb9fa414176e9dbe7c/docs/autogen.py#L112-L114

### Setup Details
Include the details about the versions of:
 - OS type and version:
 - Python: 
 - autokeras: 
 - keras-tuner:
 - scikit-learn:
 - numpy:
 - pandas:
 - tensorflow:

### Possible solution

```python
dir_path = 'py' 
for file_path in os.listdir('py/'): 
    file_name = file_path 
```

**Comment by haifeng-jin** [comment]
Sorry for the late reply.
Thank you for the issue.
You may submit a pull request for this. I will approvee and merge.
