### ISSUE TITLE
When clf.fit there's no output in console

### ISSUE THREAD

**Issue by kaixinbaba** [keras-team/autokeras#1470]
### Bug Description
```python
import autokeras as ak

data_dir = "/Users/here/is/my/image/path"

batch_size = 8
img_height = 28
img_width = 28
seed = 7

train_data = ak.image_dataset_from_directory(
    data_dir,
    # Use 20% data as testing data.
    validation_split=0.2,
    subset="training",
    # Set seed to ensure the same split when loading testing data.
    seed=seed,
    image_size=(img_height, img_width),
    batch_size=batch_size)

clf = ak.ImageClassifier(overwrite=True, max_trials=1)
print('start fit')
clf.fit(train_data, epochs=1)
print('fit done')
```

When I start this script, I got output from my console is : 
```bash
Found 19000 files belonging to 19 classes.
Using 15200 files for training.
2020-12-21 14:03:47.157072: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-12-21 14:03:47.157443: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
start fit
2020-12-21 14:03:47.411752: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
```
There is no more output. I waited for a long time, and the script did not report an error. 
The CPU usage has indeed gone up.
CPU

![image](https://user-images.githubusercontent.com/22809336/102745197-6e52af00-4396-11eb-8b3d-5e16e35536b0.png)

I adjusted the image size from 180 to 28 at the beginning, but it didn’t solve the problem. There are 19 categories and 1000 images in each category(Actually there are 4000 images in each category, I also adjusted this number try to resolve this issue).

### Expected Behavior
here is the example from ak website output from my console
![image](https://user-images.githubusercontent.com/22809336/102745363-bd98df80-4396-11eb-9122-d194b6580cdd.png)

### Setup Details
Include the details about the versions of:
 - OS type and version: MacOS Big Sur 11.0.1
 - Python: 3.6
 - autokeras: 1.0.12
 - keras-tuner: 1.0.2
 - scikit-learn: 0.23.2
 - numpy:  1.19.2
 - pandas: 1.1.3
 - tensorflow: 2.4.0

**Comment by haifeng-jin** [comment]
Maybe it is because of the compatibility with the OS?
Would you try to run on Colab?
