### ISSUE TITLE
Verbosity option for AutoKeras?

### ISSUE THREAD

**Issue by neel04** [keras-team/autokeras#1481]
A simple verbosity flag for AutoKeras that determines the output generated in the form of "Progress bar" - like an option to reduce logging by just printing 1 line about a completed epoch and not the whole progress bar. Is there any workaround for this, or would it have to implemented?

**Comment by haifeng-jin** [comment]
We are working on this, mainly need to enable the feature in Keras Tuner.
This issue is also tracked by #1286 .
