### ISSUE TITLE
Autokeras incompatible with tensorflow 2.3.0

### ISSUE THREAD

**Issue by Arcyno** [keras-team/autokeras#1486]
For GPU compatibility I need to use tensorflow 2.3.0 rather than 2.4.
It should be ok according the the documentation of autokeras (version 1.0.12)

Everything works well on tf 2.4, but when I switch to tf 2.3 I get this error message on any fit trial : 

```
"The dataset should at least contain 2 batches to be split."
ValueError: The dataset should at least contain 2 batches to be split.
```

**Comment by haifeng-jin** [comment]
I don't see why this is happening, maybe you can set smaller batch size to avoid this error.

**Comment by sunzhe09** [comment]
@Arcyno how did you install，when i install autokeras in my tensorflow2.3.2 docker ，the pip will auto install tensorflow2.4
