### ISSUE TITLE
Autokeras seems to be downloading data during training

### ISSUE THREAD

**Issue by v2thegreat** [keras-team/autokeras#1489]
### Bug Description
Not sure if this is a bug, but I'm running the example here: https://autokeras.com/tutorial/text_classification/, and I noticed that it was hanging for a period of time during the `fit`. I looked at my terminal and found that it might be downloading... something? 

![image](https://user-images.githubusercontent.com/22357311/105105084-62cfd200-5a81-11eb-9fb6-dc3e57dddaa6.png)

What's it doing in this step? I've skimmed the docs, and they don't mention anything like this. I'm using the original datasets that are provided (I have saved them as a `.npy` to make experimenting easier, however). 

### Bug Reproduction
Just use the same code in the example.

My modifications:

```python
import autokeras as ak

# Initialize the text classifier.
clf = ak.TextClassifier(
    overwrite=True,
    max_trials=5,
    max_model_size = 700000 * 4) # max size to make sure it fits in memory

# Feed the text classifier with training data.
clf.fit(x_train, y_train, epochs=5)
```

Data used by the code:

Same data, with just saving to NumPy before training

### Expected Behavior
Nothing being downloaded, and the model continuously training (currently hanging while it waits for something to download)

### Setup Details
Include the details about the versions of:
 - OS type and version: Ubuntu 20
 - Python: Python 3.8
 - autokeras: latest
 - keras-tuner: will find out if needed
 - scikit-learn: will find out if needed
 - numpy: will find out if needed
 - pandas: will find out if needed
 - tensorflow: will find out if needed

**Comment by gerwim** [comment]
This is not a bug. It's downloading the BERT model.

**Comment by v2thegreat** [comment]
I noticed that this is taking a long time to download them. Is there any way in which I can pre-download these models or not download them at all? Something like what we see with TPoT?

**Comment by haifeng-jin** [comment]
It would be stored in the `/tmp` folder. It would only be downloaded once as long as you don't clear your folder.
