### ISSUE TITLE
Do Not Require Data to Fit into Memory

### ISSUE THREAD

**Issue by theGOTOguy** [keras-team/autokeras#1497]
### Feature Description

Currently, if you follow, e.g. [the Celeb Age example](https://github.com/keras-team/autokeras/blob/master/examples/celeb_age.py), all of the images must fit into memory in order for Autokeras to successfully build a model.

This is a theme throughout Autokeras:  even if it's coming from a generator, it is converted into a dataset which needs to be loaded into memory or otherwise Autokeras can't be used.  I have experimented with constructing datasets using other methods, such as with interleave, but what I've found is that Autokeras still ultimately loads everything into memory at once regardless.

### Code Example
[The Celeb Age example](https://github.com/keras-team/autokeras/blob/master/examples/celeb_age.py) is suitable.

### Reason
Many big-data sets are too large to fit into memory on typical systems.

### Solution
[Solutions do exist for datasets in Tensorflow](https://www.tensorflow.org/datasets/performances), and probably just need to be implemented and surfaced to users of Autokeras.  If I'm wrong and there is some method to stream the data from mass storage already, I'd love to see it added to the examples.

**Comment by haifeng-jin** [comment]
This is a tutorial for loading data from disk in a streaming manner.
Does it solve the problem?
https://autokeras.com/tutorial/load/

**Comment by theGOTOguy** [comment]
It does not.

This method is suitable for an image classification problem, but not for an image regression problem (e.g., regression from an image to a scalar.)

**Comment by haifeng-jin** [comment]
Loading batch by batch is the reason that people use python generators.
By writing it in a different way, I expect it would solve the problem.

**Comment by theGOTOguy** [comment]
Sorry, you're right.  from_generator does stream the batches one at a time.  There's just an issue with my implementation:  I've wrapped a Keras Sequence with a Python generator, then that with an interleave and it appears that at some stage of this process Tensorflow is attempting to load the entire 600,000 image data set at once.

Maybe my real feature request is to support Keras [Sequences](https://www.tensorflow.org/api_docs/python/tf/keras/utils/Sequence) in addition to Datasets:  I need CPU multi-threading in order to pre-process my data efficiently enough for this process to be practical.

**Comment by haifeng-jin** [comment]
I believe Keras and TF team are trying to build a bridge between the Sequence and TF Dataset format.
When it is done, the users can easily convert the Sequences to Datasets, which is supported in AutoKeras.

**Comment by theGOTOguy** [comment]
That would be perfect.  I looked around but couldn't find an issue for it.  Do you happen to have a link handy so that I can watch the issue?

Otherwise, you can close this "will not fix."  Sequence to Dataset will resolve this issue for me.

**Comment by haifeng-jin** [comment]
I don't have that yet. Will add that to our tutorial when it is supported.
