### ISSUE TITLE
Unable to save an exported keras model gotten from Structured_data_regressor when loading in other script.

### ISSUE THREAD

**Issue by rogeravs1997** [keras-team/autokeras#1515]
### Bug Reproduction
Code for reproducing the bug:
import keras
import autokeras

#loading from one location an exported and exported tf model from Structured_data_regressor
model=keras.models.load_model("D:/Desktop/Modelo Predictivo PPV/5 features/autokeras_model8")

#trying to save the model in other location
model.save("D:/Desktop/Modelo Predictivo PPV/5 features/mytuner_model8",overwrite=True,save_format="tf")
Data used by the code:

### Setup Details
Include the details about the versions of:
 - OS type and version: Windows 10 Home 1909 x64
 - Python: 3.8.5
 - autokeras:  1.0.12
 - keras-tuner:  1.0.2
 - scikit-learn: 0.23.2
 - numpy: 1.19.2
 - pandas:1.2.2
 - tensorflow: 2.4.1

**Comment by haifeng-jin** [comment]
@rogeravs1997 Thanks for the issue!
Would you paste the error message as well?

**Comment by rogeravs1997** [comment]
Sure. There are a bunch of GPU warnings (I do not use a GPU) and the critical error of kernel died.

**An error ocurred while starting the kernel**
2021󈚦󈚾 17:07:07.868734: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021󈚦󈚾 17:07:07.870459: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021󈚦󈚾 17:07:13.500853: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021󈚦󈚾 17:07:13.503441: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021󈚦󈚾 17:07:13.534758: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1060 computeCapability: 6.1
coreClock: 1.6705GHz coreCount: 10 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 178.99GiB/s
2021󈚦󈚾 17:07:13.536583: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021󈚦󈚾 17:07:13.537917: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
2021󈚦󈚾 17:07:13.539245: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cublasLt64_11.dll'; dlerror: cublasLt64_11.dll not found
2021󈚦󈚾 17:07:13.540595: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2021󈚦󈚾 17:07:13.542187: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
2021󈚦󈚾 17:07:13.543475: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2021󈚦󈚾 17:07:13.544782: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cusparse64_11.dll'; dlerror: cusparse64_11.dll not found
2021󈚦󈚾 17:07:13.546020: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
2021󈚦󈚾 17:07:13.546585: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021󈚦󈚾 17:07:13.548224: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance‑critical operations: AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021󈚦󈚾 17:07:13.550784: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021󈚦󈚾 17:07:13.551434: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267] 
2021󈚦󈚾 17:07:13.551843: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021󈚦󈚾 17:07:14.594800: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021󈚦󈚾 17:07:15.418992: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.

**Comment by haifeng-jin** [comment]
It might because the training uses GPU and when loading you don't have GPU?
I am not sure if it works in this case.
It seems except for the first line, all the printed info is warnings instead of errors.

**Comment by rogeravs1997** [comment]
> 
> 
> It might because the training uses GPU and when loading you don't have GPU?
> I am not sure if it works in this case.
> It seems except for the first line, all the printed info is warnings instead of errors.

I've never used my GPU for training, but I'll try setting it up to discard the option you mentioned.
