### ISSUE TITLE
ValueError:  StructuredDataInput

### ISSUE THREAD

**Issue by arodrisa** [keras-team/autokeras#1544]
I have two dataframes with the following shapes:

x_train:
(223307, 60, 10)
y_train:
(223307,)

I want to create a model by using the following lines: 
reg = ak.StructuredDataRegressor(max_trials=500, overwrite=False)
reg.fit(x_train, y_train,epochs=100)

But I am getting the following error: 
ValueError: Expect the data to StructuredDataInput to have shape (batch_size, num_features), but got input shape [32, 60, 10].

I understand that it is because the batch size is 32. 
But shouldn't the model make a regression taking into account the given shapes?

**Comment by haifeng-jin** [comment]
The regressor only accepts vectors for now.
What is the meaning of the dimension of 60 and 10?
Do you consider it as structured data?
