### ISSUE TITLE
Get error while running any examples of autokeras

### ISSUE THREAD

**Issue by FrankFeenix** [keras-team/autokeras#1558]
### Bug Description
Get error while running any examples of autokeras

### Bug Reproduction
Code for reproducing the bug:
Traceback (most recent call last):
  File "c:\Users\Administrator\automodel.py", line 5, in <module>
    import autokeras as ak
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\autokeras\__init__.py", line 1, in <module>
    from autokeras.auto_model import AutoModel
    from autokeras import graph as graph_module
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\autokeras\graph.py", line 5, in <module>
    from autokeras import hypermodels
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\autokeras\hypermodels\__init__.py", line 7, in <module>
    from autokeras.hypermodels.heads import ClassificationHead
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\autokeras\hypermodels\heads.py", line 5, in <module>
    from autokeras import keras_layers
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\autokeras\keras_layers.py", line 11, in <module>
    Combiner = inspect.getmro(preprocessing.Normalization()._combiner.__class__)[1]
AttributeError: 'Normalization' object has no attribute '_combiner'
PS C:\Users\Administrator> & C:/Users/Administrator/AppData/Local/Programs/Python/Python39/python.exe c:/Users/Administrator/automodel.py
2021-05-09 17:35:01.387621: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "c:\Users\Administrator\automodel.py", line 5, in <module>
    import autokeras as ak
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\autokeras\__init__.py", line 1, in <module>
    from autokeras.auto_model import AutoModel
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\autokeras\auto_model.py", line 11, in <module>
    from autokeras import graph as graph_module
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\autokeras\graph.py", line 5, in <module>
    from autokeras import hypermodels
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\autokeras\hypermodels\__init__.py", line 7, in <module>
    from autokeras.hypermodels.heads import ClassificationHead
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\autokeras\hypermodels\heads.py", line 5, in <module>
    from autokeras import keras_layers
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\autokeras\keras_layers.py", line 11, in <module>
    Combiner = inspect.getmro(preprocessing.Normalization()._combiner.__class__)[1]
AttributeError: 'Normalization' object has no attribute '_combiner'

Data used by the code:
On examples of library

### Expected Behavior
Run without issue

### Setup Details
Include the details about the versions of:
 - OS type and version: Microsoft Windows 10 Pro, version: 10.0.19042 Build 19042
 - Python: 3.9.2
 - autokeras: 1.0.2
 - keras-tuner: 1.0.2
 - scikit-learn: 0.24.2
 - numpy: 1.19.5
 - pandas: 1.2.4
 - tensorflow: 2.5.0rc3

**Comment by f00stx** [comment]
@FrankFeenix can you recall what the problem was? I'm having the same issue, immediately upon import.

**Comment by curiouscod3** [comment]
**Similar Error here!** 
### **'Normalization' object has no attribute '_combiner'**

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <module>
----> 1 import autokeras as ak

File ~/dev/miniforge3/envs/ml/lib/python3.9/site-packages/autokeras/__init__.py:1, in <module>
----> 1 from autokeras.auto_model import AutoModel
      2 from autokeras.engine.block import Block
      3 from autokeras.engine.head import Head

File ~/dev/miniforge3/envs/ml/lib/python3.9/site-packages/autokeras/auto_model.py:11, in <module>
      8 import tensorflow as tf
      9 from tensorflow.python.util import nest
---> 11 from autokeras import graph as graph_module
     12 from autokeras import hypermodels
     13 from autokeras import nodes as input_module

File ~/dev/miniforge3/envs/ml/lib/python3.9/site-packages/autokeras/graph.py:5, in <module>
      2 import tensorflow as tf
      3 from tensorflow.python.util import nest
----> 5 from autokeras import hypermodels
      6 from autokeras import nodes
      7 from autokeras.engine import head as head_module

File ~/dev/miniforge3/envs/ml/lib/python3.9/site-packages/autokeras/hypermodels/__init__.py:7, in <module>
      5 from autokeras.hypermodels.basic import RNNBlock
      6 from autokeras.hypermodels.basic import XceptionBlock
----> 7 from autokeras.hypermodels.heads import ClassificationHead
      8 from autokeras.hypermodels.heads import RegressionHead
      9 from autokeras.hypermodels.preprocessing import CategoricalToNumerical

File ~/dev/miniforge3/envs/ml/lib/python3.9/site-packages/autokeras/hypermodels/heads.py:5, in <module>
      2 from tensorflow.python.util import nest
      4 from autokeras import adapters
----> 5 from autokeras import keras_layers
      6 from autokeras import utils
      7 from autokeras.engine import head as head_module

File ~/dev/miniforge3/envs/ml/lib/python3.9/site-packages/autokeras/keras_layers.py:11, in <module>
      8 from tensorflow.python.util import nest
     10 CombinerPreprocessingLayer = inspect.getmro(preprocessing.Normalization)[1]
---> 11 Combiner = inspect.getmro(preprocessing.Normalization()._combiner.__class__)[1]
     13 INT = 'int'
     14 NONE = 'none'

AttributeError: 'Normalization' object has no attribute '_combiner'`
```


- OS: MacOS Monterey Ver 12.2.1 (Apple M1)
- Python : 3.9.10
- numpy: 1.22.2
- pandas: 1.4.1
- autokeras : 1.0.2
- keras : 2.8.0
- keras-tuner : 1.1.0
- tensorflow-deps           2.8.0
- tensorflow-macos          2.8.0             
- tensorflow-metadata       1.7.0                    
- tensorflow-metal          0.4.0

**Comment by thomascheuk** [comment]
Similar Error here!

**Comment by dcleres** [comment]
Similar Error here!

OS: MacOS Monterey Ver 12.2.1 (Apple M1)

Python : 3.9.11
numpy: 1.21.2
pandas: 1.4.1
autokeras : 1.0.2
keras : 2.8.0
keras-tuner : 1.1.0
tensorflow-deps 2.8.0
tensorflow-macos 2.8.0
tensorflow-metadata 1.7.0
tensorflow-metal 0.4.0

**Comment by jakob-fankhauser** [comment]
has anybody been able to fix this problem?

**Comment by haifeng-jin** [comment]
Please update AutoKeras and TensorFlow to the latest version. The error would disappear.

**Comment by jakob-fankhauser** [comment]
running both latest versions `autkeras 1.0.2` and `tensorflow-macos 2.8.0` as i am on mac m1

might have something to do with tensorflow-macos but thanks for the reply

**Comment by haifeng-jin** [comment]
the latest autokeras is 1.0.19. https://github.com/keras-team/autokeras/releases

**Comment by jakob-fankhauser** [comment]
okay, but i cannot install `autokeras 1.0.19` version as it requires ` tensorflow>=2.8.0` which cannot be installed on the m1 mac

**Comment by mode80** [comment]
Since you've installed tensorflow-macos you can instruct pip to ignore the tensorflow>=2.8.0 dependency with:
```
pip install autokeras==1.0.19 --no-deps
```

**Comment by gH2AX** [comment]
I'm still getting this issue with autokeras 1.1.0; tensorflow-macos 2.10.0 is installed and working on my M1 MacbookPro.
