### ISSUE TITLE
Expect the target data for classification_head_1 to have shape [1], but got [2].

### ISSUE THREAD

**Issue by KC046** [keras-team/autokeras#1679]
### Feature Description

Use AutoKeras to Image Classification on Colab

directory structure is:
```
dataset/
...OK/
......train_OK_data_(0).jpg
......train_OK_data_(1).jpg
...NG/
......train_NG_data_(0.jpg
......train_NG_data_(1).jpg
...test/
......0.jpg
......1.jpg
```

### Code

```python 
from google.colab import drive 
drive.mount("/content/drive", force_remount=True)

import os,shutil

original_dataset_dir = r'/content/drive/MyDrive/dataset' 
```

```python 
!pip3 install autokeras
```

```python 
import autokeras as ak
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import cv2 
import numpy as np 
from tqdm import tqdm                 
from PIL import Image
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
```
```python 
#input data
X=[]
Z=[]

OK_DIR= r'/content/drive/MyDrive/dataset/OK' 
NG_DIR= r'/content/drive/MyDrive/dataset/NG' 

print(os.listdir(r'/content/drive/MyDrive/dataset'))
```
['OK', 'NG', 'test']
```python 
def make_train_data(feature_type,DIR):
    for img in tqdm(os.listdir(DIR)): 
        label = feature_type
        path = os.path.join(DIR,img)
        print(path)
        img = cv2.imread(path) 
        X.append(np.array(img))
        Z.append(str(label))
```
```python 
make_train_data('OK',OK_DIR)
```
```python 
make_train_data('NG',NG_DIR)
```
```python 
le=LabelEncoder() 
Y=le.fit_transform(Z)
Y=to_categorical(Y,2)
X=np.array(X)           
X=X/255 

x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=42)

print(x_train.shape)
print(x_test.shape) 
print(y_train.shape) 
print(y_test.shape) 
```
(140, 189, 186, 3)
(60, 189, 186, 3)
(140, 2)
(60, 2)
```python 
clf = ak.ImageClassifier(max_trials=2)
```
```python 
clf.fit(x_train, y_train, epochs=1)
```
### **error:**

ValueError_________________________________________Traceback (most recent call last)
`<ipython-input-59-c47677809cb5> in <module>()`
----> 1 clf.fit(x_train, y_train, epochs=1)

3 frames
[/usr/local/lib/python3.7/dist-packages/autokeras/tasks/image.py](https://localhost:8080/#) in fit(self, x, y, epochs, callbacks, validation_split, validation_data, **kwargs)
    169             validation_split=validation_split,
    170             validation_data=validation_data,
--> 171             **kwargs
    172         )
    173         return history

[/usr/local/lib/python3.7/dist-packages/autokeras/auto_model.py](https://localhost:8080/#) in fit(self, x, y, batch_size, epochs, callbacks, validation_split, validation_data, verbose, **kwargs)
    277             x=x, y=y, validation_data=validation_data, batch_size=batch_size
    278         )
--> 279         self._analyze_data(dataset)
    280         self._build_hyper_pipeline(dataset)
    281 

[/usr/local/lib/python3.7/dist-packages/autokeras/auto_model.py](https://localhost:8080/#) in _analyze_data(self, dataset)
    370 
    371         for analyser in analysers:
--> 372             analyser.finalize()
    373 
    374         for hm, analyser in zip(self.inputs + self._heads, analysers):

[/usr/local/lib/python3.7/dist-packages/autokeras/analysers/output_analysers.py](https://localhost:8080/#) in finalize(self)
     75                 "Expect the target data for {name} to have "
     76                 "shape {expected}, but got {actual}.".format(
---> 77                     name=self.name, expected=expected, actual=self.shape[1:]
     78                 )
     79             )

ValueError: Expect the target data for classification_head_1 to have shape [1], but got [2].

I am new to automl, but not to machine learning, so please bear with me if I'm missing something obvious. I searched for [image_dataset_from_directory](https://autokeras.com/utils/) and didn't see another post about this issue.

Any suggestions are highly appreciated.

**Comment by GrzelakL** [comment]
Hello, how did you solve this issue ?

**Comment by haifeng-jin** [comment]
It is about what your labels looks like.
You can try to print the `y_train` in this tutorial:
https://autokeras.com/tutorial/image_classification/

And compare the format to yours.
