### ISSUE TITLE
Custom metric have error problem in prediction

### ISSUE THREAD

**Issue by midisec** [keras-team/autokeras#1683]
I customize an evaluation metric, R_squared, which trains properly but when I predict, errors occur.

`
def R_squared(y, y_pred):
  residual = tf.reduce_sum(tf.square(tf.subtract(y, y_pred)))
  total = tf.reduce_sum(tf.square(tf.subtract(y, tf.reduce_mean(y))))
  r2 = tf.subtract(1.0, tf.divide(residual, total))
  return r2

reg = ak.StructuredDataRegressor(
    overwrite=True, max_trials=3, seed=0,loss="MeanSquaredError"
     ,objective= kerastuner.Objective('val_R_squared', direction='max')
    ,metrics=[R_squared]
)  

reg.fit(
    x=X_train, y=y_train,
    epochs=10,
    validation_data=(X_val, y_val),
)

predicted_y = reg.predict(X_test, custom_objects={'R_squared':R_squared})
`

I can't find the solution in the documentation and google, help.

Error message：
ValueError                                Traceback (most recent call last)
Input In [115], in <module>
----> 1 predicted_y = reg.predict(X_test, custom_objects={'R_squared':R_squared})

File D:\soft\Miniconda\envs\mykeras\lib\site-packages\autokeras\tasks\structured_data.py:165, in BaseStructuredDataPipeline.predict(self, x, **kwargs)
    151 """Predict the output for a given testing data.
    152 
    153 # Arguments
   (...)
    161     The predicted results.
    162 """
    163 x = self.read_for_predict(x)
--> 165 return super().predict(x=x, **kwargs)

File D:\soft\Miniconda\envs\mykeras\lib\site-packages\autokeras\auto_model.py:448, in AutoModel.predict(self, x, batch_size, verbose, **kwargs)
    446 dataset = self._adapt(x, self.inputs, batch_size)
    447 pipeline = self.tuner.get_best_pipeline()
--> 448 model = self.tuner.get_best_model()
    449 dataset = pipeline.transform_x(dataset)
    450 dataset = tf.data.Dataset.zip((dataset, dataset))

File D:\soft\Miniconda\envs\mykeras\lib\site-packages\autokeras\engine\tuner.py:63, in AutoTuner.get_best_model(self)
     61 def get_best_model(self):
     62     with keras_tuner.engine.tuner.maybe_distribute(self.distribution_strategy):
---> 63         model = tf.keras.models.load_model(self.best_model_path)
     64     return model

File D:\soft\Miniconda\envs\mykeras\lib\site-packages\keras\utils\traceback_utils.py:67, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     65 except Exception as e:  # pylint: disable=broad-except
     66   filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67   raise e.with_traceback(filtered_tb) from None
     68 finally:
     69   del filtered_tb

File D:\soft\Miniconda\envs\mykeras\lib\site-packages\keras\saving\saved_model\load.py:1000, in revive_custom_object(identifier, metadata)
    998   return revived_cls._init_from_metadata(metadata)  # pylint: disable=protected-access
    999 else:
-> 1000   raise ValueError(
   1001       f'Unable to restore custom object of type {identifier}. '
   1002       f'Please make sure that any custom layers are included in the '
   1003       f'`custom_objects` arg when calling `load_model()` and make sure that '
   1004       f'all layers implement `get_config` and `from_config`.')

ValueError: Unable to restore custom object of type _tf_keras_metric. Please make sure that any custom layers are included in the `custom_objects` arg when calling `load_model()` and make sure that all layers implement `get_config` and `from_config`.

**Comment by Kabster17** [comment]
Hi, I am actually currently facing with the same issue, with the same error when trying to implement ImageClassifier with custom f1-score metric as a custom objective suggested/implemented in the faq section. Can I ask what is the work around this issue? 

I noticed that F1 score is well supported by the Autokeras but not sure what to make out with this error. Here is the snippet of my error message:

ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_12316/2665656444.py in <module>
      3 # Evaluate on the testing data.
      4 print('Accuracy: {accuracy}'.format(
----> 5     accuracy=clf.evaluate(x_test, y_test)))

~\anaconda3\envs\autokeras\lib\site-packages\autokeras\auto_model.py in evaluate(self, x, y, batch_size, verbose, **kwargs)
    488         pipeline = self.tuner.get_best_pipeline()
    489         dataset = pipeline.transform(dataset)
--> 490         model = self.tuner.get_best_model()
    491         return utils.evaluate_with_adaptive_batch_size(
    492             model=model, batch_size=batch_size, x=dataset, verbose=verbose, **kwargs

~\anaconda3\envs\autokeras\lib\site-packages\autokeras\engine\tuner.py in get_best_model(self)
     61     def get_best_model(self):
     62         with keras_tuner.engine.tuner.maybe_distribute(self.distribution_strategy):
---> 63             model = tf.keras.models.load_model(self.best_model_path)
     64         return model
     65 

~\anaconda3\envs\autokeras\lib\site-packages\keras\utils\traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

~\anaconda3\envs\autokeras\lib\site-packages\keras\saving\saved_model\load.py in revive_custom_object(identifier, metadata)
    999   else:
   1000     raise ValueError(
-> 1001         f'Unable to restore custom object of type {identifier}. '
   1002         f'Please make sure that any custom layers are included in the '
   1003         f'`custom_objects` arg when calling `load_model()` and make sure that '





ValueError: Unable to restore custom object of type _tf_keras_metric. Please make sure that any custom layers are included in the `custom_objects` arg when calling `load_model()` and make sure that all layers implement `get_config` and `from_config`.
