### ISSUE TITLE
Problem in autokeras model

### ISSUE THREAD

**Issue by MatheusPaula97** [keras-team/autokeras#1685]
[Feature Extractor.txt](https://github.com/keras-team/autokeras/files/8062259/Feature.Extractor.txt)

When I try to remove layers using .children, this problem occurs which does not occur with the original torch model:

![image](https://user-images.githubusercontent.com/99619009/153901245-88e10165-b06c-418c-959e-37117bc5930d.png)

I don't know if you can post problems outside the range of this github, but I didn't find any autokeras groups. If anyone can find an alternative to run the feature_x_train, I'd appreciate it

**Comment by haifeng-jin** [comment]
You are using a torch model? We only support tensorflow.keras.
