### ISSUE TITLE
error : KeyError: 'text_block_1/conv_block_1/filters_0_1'  with textclassifier

### ISSUE THREAD

**Issue by YASIRAQ** [keras-team/autokeras#1812]
I'm doing a text classification with 5 trials, in the 3rd I'm getting this error

this is a part of my code:
clf = ak.TextClassifier(max_trials = 50, overwrite =True)
clf.fit(x_train, y_train, epochs=100  , verbose = 2  , validation_data=(x_valid,y_valid))

this error I have faced was :
KeyError: 'text_block_1/conv_block_1/filters_0_1'

**Comment by haifeng-jin** [comment]
@YASIRAQ Would you please confirm the autokeras and keras-tuner version you are using?
You can run `pip freeze` to show them.

It would be even better if you can provide a short colab notebook to reproduce the error.
You can use fake data and fix the seed.
Thanks.

**Comment by YASIRAQ** [comment]
> @YASIRAQ Would you please confirm the autokeras and keras-tuner version you are using? You can run `pip freeze` to show them.
> 
> It would be even better if you can provide a short colab notebook to reproduce the error. You can use fake data and fix the seed. Thanks.

the versions I use are :
auto keras =1.0.20
keras-tuner =1.1.3

if you do not mind explaining what i must do exactly ?
thank you very much

**Comment by haifeng-jin** [comment]
@YASIRAQ It seems like a bug, but I cannot reproduce it.
The 3rd trial is always the Bert model. There is no randomness in the first 3 trials.
Do you see this error if you run [this tutorial](https://autokeras.com/tutorial/text_classification/) for 5 trials?

**Comment by YASIRAQ** [comment]
> @YASIRAQ It seems like a bug, but I cannot reproduce it. The 3rd trial is always the Bert model. There is no randomness in the first 3 trials. Do you see this error if you run [this tutorial](https://autokeras.com/tutorial/text_classification/) for 5 trials?

I have tried another dataset . it works well
I don't know where the problem is ?
the most important I want to tell you that I worked on my dataset on Sunday , it worked well . the problem happened yesterday
may be this bug happens randomly ?

**Comment by YASIRAQ** [comment]
I run the tutorial , it worked well
the most important I want to tell you that I worked on my dataset on Sunday , it worked well . the problem happened yesterday
may be this bug happens randomly ?

**Comment by YASIRAQ** [comment]
> 
I run the tutorial , it worked well
the most important I want to tell you that I worked on my dataset on Sunday , it worked well . the problem happened yesterday
may be this bug happens randomly ?

**Comment by RaedMatti** [comment]
When I run 2 trials the code works well, as you said the problem happens with the BERT model in the 3rd trial. One time it worked with 10 trials and I had good results. The error occurs randomly.

> @YASIRAQ It seems like a bug, but I cannot reproduce it. The 3rd trial is always the Bert model. There is no randomness in the first 3 trials. Do you see this error if you run [this tutorial](https://autokeras.com/tutorial/text_classification/) for 5 trials?

**Comment by haifeng-jin** [comment]
It is really strange. I don't think there is any randomness in the first 3 trials.
The tuner would try 3 sets of predefined hyperparameters before exploring the rest.

Is it possible that it is because that you removed `overwrite=True`, which caused the problem?

It seems an important bug, but I cannot reproduce it on my computer.

**Comment by RaedMatti** [comment]
I didn't remove overwrite=True, 
now I'm running an autosklearn code on the same dataset, and it's working, and I don't have any issues with it.
When I run AK On Colab sometimes it passes the 3rd trial and sometimes don't but on kaggle it didn't pass the 3rd trial.

**Comment by YASIRAQ** [comment]
> It is really strange. I don't think there is any randomness in the first 3 trials. The tuner would try 3 sets of predefined hyperparameters before exploring the rest.
> 
> Is it possible that it is because that you removed `overwrite=True`, which caused the problem?
> 
> It seems an important bug, but I cannot reproduce it on my computer.

can you please

**Comment by YASIRAQ** [comment]
> I didn't remove overwrite=True, now I'm running an autosklearn code on the same dataset, and it's working, and I don't have any issues with it. When I run AK On Colab sometimes it passes the 3rd trial and sometimes don't but on Kaggle it didn't pass the 3rd trial.

hi , I'm beginner in deep learning area , and I only use Collab . is there any other servers I can use to run my codes ?
thank you very much

**Comment by RaedMatti** [comment]
> > I didn't remove overwrite=True, now I'm running an autosklearn code on the same dataset, and it's working, and I don't have any issues with it. When I run AK On Colab sometimes it passes the 3rd trial and sometimes don't but on Kaggle it didn't pass the 3rd trial.
> 
> hi , I'm beginner in deep learning area , and I only use Collab . is there any other servers I can use to run my codes ? thank you very much

You can use >> https://www.kaggle.com/
it will give you grate resources for learning, and you can run your codes either.
