### ISSUE TITLE
Exception thrown: cannot import name 'keras' from 'tensorflow' (unknown location)

### ISSUE THREAD

**Issue by rgoudie** [keras-team/autokeras#1824]
### Bug Description
After installing AutoKeras and depencies according to instructions, trying to import autokeras throws the exception:
`cannot import name 'keras' from 'tensorflow' (unknown location)`

### Bug Reproduction
`from autokeras import StructuredDataClassifier`

### Expected Behavior
Import succeeds without error.

### Setup Details
Include the details about the versions of:
 - Windows 10
 - Python: 3.8.0
 - autokeras: 1.0.20
 - keras-tuner: 1.2.0.dev0
 - keras: 2.11.0
 - scikit-learn: 1.2.0
 - numpy: 1.22.4
 - pandas: 1.5.2
 - tensorflow: 2.11.0

### Additional context
The exception is thrown in many instances.

**Example:** [This](https://autokeras.com/tutorial/timeseries_forecaster) tutorial website:
```
import pandas as pd
import tensorflow as tf
import autokeras as ak  <--- same exception thrown
```

![image](https://user-images.githubusercontent.com/34731480/210184913-9994c9d0-b28c-4449-b5d5-e2ca620c894f.png)

**Comment by haifeng-jin** [comment]
It might be a TensorFlow installation problem.
Would you please try `import keras from tensorflow` in your Python commandline?
It it gives the same error, then it is the TF install problem.

**Comment by rgoudie** [comment]
So sorry for the late reply. I never received a notification and completely forgot about the issue.

**Comment by rgoudie** [comment]
I will close the issue at this time.
