### ISSUE TITLE
Cant install autokeras 

### ISSUE THREAD

**Issue by paulgureghian** [keras-team/autokeras#196]
### Reproducing Steps
  * Step 1: ...
  * Step 2: ...

### Expected Behavior
 I tried to install autokeras into a pipenv using  pipenv install autokeras  and  pipenv install --pre autokeras. both failed 

### Setup Details
Include the details about the versions of:
 - OS type and version:
 - Python: 
 - autokeras: 
 - scikit-learn:
 - numpy:
 - keras:
 - scipy:
 - tensorflow:
 - pytorch:

### Additional context

![capture15](https://user-images.githubusercontent.com/8146561/45576634-d667d180-b82c-11e8-945d-6fc610c3033a.PNG)

**Comment by paulgureghian** [comment]
cant install autokeras with pipenv

**Comment by jhfjhfj1** [comment]
@paulgureghian 
Thank you for the issue.
Would you please check what is the latest tensorflow version possible on pipenv?

Thanks

**Comment by paulgureghian** [comment]
I tried to find that out by looking at the pipenv docs, but I couldn't figure it out.
