### ISSUE TITLE
Question: what is the maximum number/size of images it can handle ?

### ISSUE THREAD

**Issue by hlalibe** [keras-team/autokeras#197]
Hi,

I have currently around 125'000 .png files of 7kb (533x533 pixels) each to train on, is AutoKeras able to handle this ?

Running under Ubuntu 16.04 128 GB RAM, Nvidia Titan XP 12Gb

If so, how much time will it take to run roughly ? minutes ? hours ?

**Comment by jhfjhfj1** [comment]
I think it is because the size of image is too large.
You may want to try compress it first.
We may implement this compression feature in the future.
Thanks.

**Comment by hlalibe** [comment]
I believe you are replying to my other post, no ?
https://github.com/jhfjhfj1/autokeras/issues/198

I can resize my images, what is the maximum size you recommend ?
And do you have any feed-back on my questions above ?

thanks

**Comment by erichhhhho** [comment]
Tried (14967, 224, 224, 3) with 1080ti 12GB and 32Gb ram and Failed
