### ISSUE TITLE
Colab GPU Tutorial (Example use GPU on Colab). Should be a Colab notebook

### ISSUE THREAD

**Issue by shyamalschandra** [keras-team/autokeras#339]
Will you be adding the functionality to run autokeras from GPU and TPU runtime in google research colab?

### Feature Description
Will you be adding the functionality to run autokeras from GPU and TPU runtime in google research colab?

### Reason
I need to accelerate the search.

### Solution
Update to the autokeras library.

### Alternative Solutions
I can do it myself.

### Additional Context
It doesn't work right now in colab.

**Comment by tl-yang** [comment]
@shyamalschandra  The latest version should work on Colab. If you encounter any problem using Google Colab with the latest Autokeras, please let us know!

**Comment by shyamalschandra** [comment]
Do you have any commits that have this note on it?  Should there be any difference?

**Comment by jhfjhfj1** [comment]
@tl-yang Is there a colab tutorial or example now? Can we put it on start.md? Thanks.

**Comment by tlkh** [comment]
I can do up a small Colab tutorial. Only minor issue is installing autokeras requirements has a different version of PyTorch to the one on Colab. 

Workaround and working Colab notebook:

https://github.com/keras-team/autokeras/issues/624#issuecomment-495916771

**Comment by mikewlange** [comment]
I'm guessing this is an oldie that never got closed. But just in case. 

[https://colab.research.google.com/drive/1LIGgokMC2rPlx-2Aa6TfcYZSHYdXu7ze](https://colab.research.google.com/drive/1LIGgokMC2rPlx-2Aa6TfcYZSHYdXu7ze)

Oh, skip to #10 if you don't feel like battling ngrok for tensorboard

**Comment by shyamalschandra** [comment]
@mikewlange : Interested but this doesn't get TPUs to work with autokeras?  Right?  Just curious if you had an example with the TPU integration with autokeras.
