### ISSUE TITLE
[Question]Error while running test cases

### ISSUE THREAD

**Issue by maldil** [keras-team/autokeras#374]
I am trying to run test cases in my local machine. I got following error while running the test case. If anybody having an idea about the error, I would be grateful to have your help

I am new to this project and starting to learn. As the first attempt I ran the test cases as below. I am running the test cases in a python virtual machine and OS Mac. 

command 
```pytest test_preprocessor.py```
Error
```
E   OSError: dlopen(/Users/malinda/Documents/Python/VMS/VM1/VID2VID/lib/python3.7/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
E     Referenced from: /Users/malinda/Documents/Python/VMS/VM1/VID2VID/lib/python3.7/site-packages/lightgbm/lib_lightgbm.so
E     Reason: image not found
```

**Comment by vishakh-slb** [comment]
I too had similar issues. Running on MacOS X. Using python3.6 virtual environment.
It looks like a problem with MacOS. It looks like a problem with OpenMP (which is probably not installed on your machine)

Try installing it with brew:
```bash
brew install libomp
```
