### ISSUE TITLE
Crash when input image too small. Because of the pooling layers.

### ISSUE THREAD

**Issue by JY00002** [keras-team/autokeras#393]
the input shape of my model is: tr_X shape (110000, 2, 128, 1).
Traceback:Given input size: (64x1x64). Calculated output size: (64x0x32). Output size is too small at /pytorch/aten/src/THCUNN/generic/SpatialDilatedMaxPooling.cu:69.

it seems that something error with pooling.

**Comment by songqiqqq** [comment]
any idea ? I ran into the same problem as stated in this issue[545](https://github.com/jhfjhfj1/autokeras/issues/545)

**Comment by githubsqg** [comment]
I reshape (8160, 1, 1089, 1) to (8160, 121, 9, 1), then it works. Maybe when using ImageClassifier, the second dimension doesn't support 1.
