### ISSUE TITLE
feature_request: support for seq models: RNN, LSTM, GRU

### ISSUE THREAD

**Issue by mark-watson** [keras-team/autokeras#411]
### Feature Description
Support for RNN, specifically LSTM and/or GRU - I might be willing to help implement in autokeras

### Reason
Much of my work involves RNN, specifically LSTM and GRU, and I am sure that many other potential autokeras users would be interested in sequence model support also.

### Solution

I suggest initially just supporting LSTM since LSTM cover GRU use cases, with a slight cost in model complexity and training time.

### Alternative Solutions
none

### Additional Context
Please reach out to me if you would like help implementing this.

**Comment by slavakurilyak** [comment]
Inspiration: Microsoft's [nni](https://github.com/Microsoft/nni), an AutoML toolkit for neural architecture search, already supports [sequential](https://github.com/Microsoft/nni/search?q=sequential&unscoped_q=sequential) models.

**Comment by illcat** [comment]
Is there a plan to increase RNN?

**Comment by anuraagvaidya** [comment]
I agree. We need AutoKeras for sequential models.

**Comment by anuraagvaidya** [comment]
> ### Feature Description
> Support for RNN, specifically LSTM and/or GRU - I might be willing to help implement in autokeras
> 
> ### Reason
> Much of my work involves RNN, specifically LSTM and GRU, and I am sure that many other potential autokeras users would be interested in sequence model support also.
> 
> ### Solution
> I suggest initially just supporting LSTM since LSTM cover GRU use cases, with a slight cost in model complexity and training time.
> 
> ### Alternative Solutions
> none
> 
> ### Additional Context
> Please reach out to me if you would like help implementing this.

Seems that the support is present.
[https://github.com/keras-team/autokeras/issues/696](url)
