### ISSUE TITLE
feature_request: AdaNet

### ISSUE THREAD

**Issue by tl-yang** [keras-team/autokeras#415]
### Feature Description
Incorporating AdaNet to Auto-Keras. 

### Reason
Using AdaNet to utilize the intermediate search result could increase the performance a lot.

**Comment by erichulburd** [comment]
I'm curious if there is any reason why AdaNet wasn't initially included in AutoKeras. The results seemed promising, so I assume either (a) its algorithms were subsequently outclassed or (b) its integration would involve a level of complexity that wasn't worthwhile for this library.
