### ISSUE TITLE
Autokeras with MNIST data fails

### ISSUE THREAD

**Issue by Garfield2013** [keras-team/autokeras#434]
When I run the MNIST example (with the full dataset) from the website (https://autokeras.com/start/):

    from keras.datasets import mnist
    from autokeras.image.image_supervised import ImageClassifier
    
    if __name__ == '__main__':
        (x_train, y_train), (x_test, y_test) = mnist.load_data()
        x_train = x_train.reshape(x_train.shape + (1,))
        x_test = x_test.reshape(x_test.shape + (1,))
    
        clf = ImageClassifier(verbose=True)
        clf.fit(x_train, y_train, time_limit=12 * 60 * 60)
        clf.final_fit(x_train, y_train, x_test, y_test, retrain=True)
        y = clf.evaluate(x_test, y_test)
        print(y)

 it comes out with the following error when the time is out:

> File "C:\Program Files\Python36\lib\site-packages\sklearn\metrics\classification.py",
> line 1568, in <genexpr>
>     	name_width = max(len(cn) for cn in target_names)
>     TypeError: object of type 'numpy.uint8' has no len()

When I run on a subset of the MNIST data (20 train / 200 test) it comes out with the following error when the time is out:

> File "C:\Program
> Files\Python36\lib\site-packages\autokeras\preprocessor.py", line 50,
> in <lambda> 	return np.array(list(map(lambda x: self.label_to_vec[x],
> data)))
>      KeyError: 7

**Comment by jmschabdach** [comment]
When you run it, does it not find a solution in 12 hours? How many epochs does it get through?

Developers, what is the expected shape/size of the architecture for this example? How long should it be expected to run before it finds a solution?
