### ISSUE TITLE
Auto Keras Installation Error - imageio

### ISSUE THREAD

**Issue by mohammed-fakruddin** [keras-team/autokeras#444]
### Reproducing Steps
  * Step 1: pip install tensorflow
  * Step 2: pip install keras
  * Step 3: pip install autokeras

During the installation of AutoKeras I ge the following error message - 

Found existing installation: imageio 2.2.0
Cannot uninstall 'imageio'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
### Expected Behavior

I am expecting successful installation of autokeras library.

### Setup Details
Include the details about the versions of:
 - OS type and version: mac HishSierra (10.13)
 - Python: 3.6

**Comment by feedliu** [comment]
Maybe you can try to create a virtual enviorment or use anaconda to get a pure enviorment.

**Comment by Yogeshnaik1190** [comment]
I tried the same command: pip install autokeras. I am getting the same error. (using an Anaconda-Jupyter notebook on OS: Ubuntu)

**Comment by mi7plus** [comment]
Try to install like this:
`pip install autokeras --ignore-installed`

**Comment by juan57** [comment]
^Above installed autokeras but reinstalled the CPU version of Tensorflow.
(If using CUD9.2) I had to uninstall tensorflow and reinstall version 1.12

**Comment by gnaaromat** [comment]
If I do that I run into the 

` ERROR: Could not find a version that satisfies the requirement torch==1.0.1 (from autokeras==0.3.7) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.0.1 (from autokeras==0.3.7)`

Problem. Any better ideas? ^^

**Comment by gnaaromat** [comment]
Well if anyone runs over this issue:

`conda uninstall imageio`

so easy. took me 30 minutes to figure that out 👯‍♂
