### ISSUE TITLE
I don't know how to use it ? Please provide a detailed tutorial,and more examples !

### ISSUE THREAD

**Issue by minda163** [keras-team/autokeras#457]
### Feature Description

I don't know how to use it ? Please provide a detailed tutorial,and more examples ! 
### Reason

Be badly in need of tutorial ！

**Comment by jhfjhfj1** [comment]
Thank you for the issue. We are working on it. #408

**Comment by hemangjoshi37a** [comment]
[This Video](https://www.youtube.com/watch?v=veWfGSZSzmE&t=473s) might be useful.
