### ISSUE TITLE
AttributeError: type object 'MlpGenerator' has no attribute 'fit'

### ISSUE THREAD

**Issue by minda163** [keras-team/autokeras#458]
### Bug Description

In this tutorial
https://github.com/jhfjhfj1/autokeras/blob/master/mkdocs/docs/start.md

![image](https://user-images.githubusercontent.com/33540791/51221657-6b164380-1975-11e9-8af6-d050a9fe9451.png)
I followed it, but it's wrong
```
import autokeras as ak
MLpG = ak.net_module.MlpGenerator(81,x_train[:,1].shape)
MLpG.fit
```
![image](https://user-images.githubusercontent.com/33540791/51221732-b2043900-1975-11e9-9b18-e16aa3bfbea1.png)
Where did I go wrong and how should I fix it？
What should I do when I want to get a network structure for my data（not for image ）？

**Comment by jhfjhfj1** [comment]
Can you try with the latest master branch? If it still fails, we will look into it. Thank you!

**Comment by minda163** [comment]
@jhfjhfj1 
I installed autokeras yesterday , used "pip install autokeras'',it shoud be the latest master branch.
![image](https://user-images.githubusercontent.com/33540791/51225288-d0256580-1984-11e9-8b89-1738a1210e7d.png)

**Comment by yuvrajkhanna** [comment]
issue is still there can you tell me when it will be fixed??
