### ISSUE TITLE
the model size of object_detection is too big

### ISSUE THREAD

**Issue by wjnodejs** [keras-team/autokeras#463]
the model size of object_detection is about 100M.
i want to apply on mobile. how to make the model smaller

**Comment by hemangjoshi37a** [comment]
100Mb is not big. Your phone will handle it fine. By the way which mobile do you have??

**Comment by wjnodejs** [comment]
i found the tflite at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite . thank you .
