### ISSUE TITLE
ImportError: cannot import name 'extend_notes_in_docstring'

### ISSUE THREAD

**Issue by supanat** [keras-team/autokeras#466]
from autokeras.image.image_supervised import ImageClassifier, load_image_dataset
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-07e309238f8e> in <module>()
----> 1 from autokeras.image.image_supervised import ImageClassifier, load_image_dataset

/jet/var/python/lib/python3.6/site-packages/autokeras/image/image_supervised.py in <module>()
      5 from autokeras.constant import Constant
      6 from autokeras.nn.loss_function import classification_loss, regression_loss
----> 7 from autokeras.nn.metric import Accuracy, MSE
      8 from autokeras.preprocessor import OneHotEncoder, ImageDataTransformer
      9 from autokeras.supervised import PortableDeepSupervised, DeepSupervised

/jet/var/python/lib/python3.6/site-packages/autokeras/nn/metric.py in <module>()
      1 from abc import abstractmethod
      2 
----> 3 from sklearn.metrics import accuracy_score, mean_squared_error
      4 
      5 

/jet/var/python/lib/python3.6/site-packages/sklearn/metrics/__init__.py in <module>()
      5 
      6 
----> 7 from .ranking import auc
      8 from .ranking import average_precision_score
      9 from .ranking import coverage_error

/jet/var/python/lib/python3.6/site-packages/sklearn/metrics/ranking.py in <module>()
     25 import numpy as np
     26 from scipy.sparse import csr_matrix
---> 27 from scipy.stats import rankdata
     28 
     29 from ..utils import assert_all_finite

/jet/var/python/lib/python3.6/site-packages/scipy/stats/__init__.py in <module>()
    343 from __future__ import division, print_function, absolute_import
    344 
--> 345 from .stats import *
    346 from .distributions import *
    347 from .morestats import *

/jet/var/python/lib/python3.6/site-packages/scipy/stats/stats.py in <module>()
    169 import scipy.special as special
    170 import scipy.linalg as linalg
--> 171 from . import distributions
    172 from . import mstats_basic
    173 from ._distn_infrastructure import _lazywhere

/jet/var/python/lib/python3.6/site-packages/scipy/stats/distributions.py in <module>()
     11                                     rv_frozen)
     12 
---> 13 from . import _continuous_distns
     14 from . import _discrete_distns
     15 

/jet/var/python/lib/python3.6/site-packages/scipy/stats/_continuous_distns.py in <module>()
      9 import numpy as np
     10 
---> 11 from scipy.misc.doccer import (extend_notes_in_docstring,
     12                                replace_notes_in_docstring)
     13 from scipy import optimize

ImportError: cannot import name 'extend_notes_in_docstring'

**Comment by hemangjoshi37a** [comment]
import scipy in your code. It will probably solve the error.

**Comment by supanat** [comment]
> import scipy in your code. It will probably solve the error.

Thank you.

**Comment by Samar-080301** [comment]
> > import scipy in your code. It will probably solve the error.
> 
> Thank you.

I wrote `import scipy
from autokeras import ImageClassifier, load_image_dataset`
But the following error prompted `ImportError: cannot import name 'load_image_dataset' from 'autokeras'`. Please help me!
