### ISSUE TITLE
CnnModule: ValueError: expected 2D or 3D input (got 4D input)

### ISSUE THREAD

**Issue by kapsl** [keras-team/autokeras#475]
### Bug Description
I created a custom dataset class which loads csv data (which is basically timeseries data) but normally runs with a convolutional net. The shape of the data is (2500, 1, 12). 

### Reproducing Steps
When fitting: batchnorm.py line 156 it complains that ValueError: expected 2D or 3D input (got 4D input). This is because it counts the batch as additional input?!
t about the problem here.

**Comment by sameedmsiddiqui** [comment]
Hi all,

I get a similar error: 

  File "/home/me/anaconda3/envs/autokeras/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 156, in _check_input_dim
    .format(input.dim()))
ValueError: expected 2D or 3D input (got 4D input).

I've posted a new thread about this issue, giving more details about the code I used [(here)](https://github.com/jhfjhfj1/autokeras/issues/500)
