### ISSUE TITLE
feature_request: How to create models with labels as array

### ISSUE THREAD

**Issue by schliffen** [keras-team/autokeras#509]
### Description

I want to be able to train models in which labels are vectors. imagine that I have image, I want to get feature points from the image. input: [image_1, image_2, .... image_N] and label is a vector like [(x_1, y_1), (x_2, y_2), ... , (x_N, y_N)]  

### Reason

There are lots of problems in them we need to have labels as arrays.

**Comment by SharifElfouly** [comment]
Is this even possible in autokeras? If yes, how?
