### ISSUE TITLE
Current model size is too big. Discontinuing training this model to search for other models.

### ISSUE THREAD

**Issue by qmpzzpmq** [keras-team/autokeras#537]
### Bug Description
Hi, I am using autokeras with my own dataset its input size is (4225000,50), (4225000,39). I am trying to training a classifier. And the data is feded with hdf5 file, I recomile hdf5 and h5py for pytorch parallel running.

As the issue [https://github.com/jhfjhfj1/autokeras/issues/236](url) said, the model size control looks bad. 
I know the `Constant.MAX_MODEL_SIZE = graph.size() - 1` at  search.py is using for control the size of model, and I tried to print these 2 value `Constant.MAX_MODEL_SIZE `  `graph.size()` in each iterration. it seems it doens't change anymore.

Here is my log:
+----------------------------------------------+
|             Training model 7464              |
+----------------------------------------------+

Current model size is too big. Discontinuing training this model to search for other models.

Initializing search.
Initialization finished.

Also, before training, the 'MAX_MODEL_SIZE' is constrained mannually.
`Constant.MAX_MODEL_SIZE = max(1, round(Constant.MAX_MODEL_SIZE/1e3))`

**Comment by rafaelmarconiramos** [comment]
I had the same problem with the input: (5561, 512, 512,6).
I read here in another issue that is a problem of autokeras: generate very complex models.
