### ISSUE TITLE
Execute autokeras on GPU

### ISSUE THREAD

**Issue by rafaelmarconiramos** [keras-team/autokeras#539]
I try many different combinations of autokeras dependencies, but I never get to run autokeras on GPU.
Does somebody know what the problem is? Or the version of the libraries like pytorch, cudatoolkit, tensorflow-gpu ....

Could the project yield a docker container with autokeras and GPU support backend tensorflow? 

I want to test autokeras, but it is impossible to execute my problem without GPU.

Thanks

**Comment by William8Work** [comment]
I was able to run the test examples from autokeras using GPU through tensorflow. Did you check if your environment has properly installed the CUDA drivers and tensorflow-gpu is loaded?

One way the check if the tensorflow is using GPU or not, run the following codes:
   import tensorflow as tf
   sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

You should see the output referencing the GPU if it's successful.

**Comment by rafaelmarconiramos** [comment]
Thanks. I got the tensorflow docker for GPU execution and installed the autokeras. Now it works.

**Comment by adrianog** [comment]
Can I ask you exactly what docker image you are running? Ty

**Comment by crypdick** [comment]
@adrianog  see https://autokeras.com/docker/

**Comment by cannin** [comment]
One way of checking for GPU on Tensorflow 2: 

```
sess = tf.compat.v1.Session(config=tf.compat.v1.ConfigProto(log_device_placement=True))
```
