### ISSUE TITLE
[Feature request]fit_generator style training from Keras 

### ISSUE THREAD

**Issue by 2ndMessiah** [keras-team/autokeras#540]
### Feature Description

Use a python generator to generate input data for flexibility.

This feature was ever requested once, but the issue was closed somehow while there's no alternative APIs.

Thanks.

**Comment by crypdick** [comment]
Possibly related to #99

**Comment by cibic89** [comment]
AutoKeras is not usable without fit_generator I feel. It is limited to toy problems!

**Comment by eladmw** [comment]
I agree, if fit_generator is applied, this module will become very popular. Sparse integration would also be nice.

**Comment by haifeng-jin** [comment]
Let's use #984 to track this generator issue. Thanks.
