### ISSUE TITLE
How to evaluate the MLP module

### ISSUE THREAD

**Issue by kylechang523** [keras-team/autokeras#548]
When I use MLP module training the data, I faced two problems. 
First, when i set running time as 24h, it sometimes will appear the error 'RuntimeError: weight should at leat have at  least two dimensions'. 
Second, I found the MLP module has no attributes to 'evaluate' or 'predict' after I use 'mlp.final_fit'. How can we evaluate the model performance basing on the test set? Is there any way to solve it?

I hope I'm not the only one facing this problem!

**Comment by ttyen** [comment]
I touched the same issue: 'RuntimeError: weight should at leat have at least two dimensions'.
When I ran my own dataset on either Latest Stable or Bleeding Edge version

**Comment by whyboy** [comment]
I meet the same issue, and another issue is that

**Comment by whyboy** [comment]
I meet the sam issue with you!

**Comment by whyboy** [comment]
Another issue is : MlpModule object has no attribute   export_autokeras_module.   Does anybody meet the same issue with me ? my aim is to save the module

**Comment by itsergiu** [comment]
Please provide an example for classic MLP Boston house price dataset.

https://gist.github.com/securetorobert/322f099cd6e4bb6ce05ccd954eb0cf3e
https://machinelearningmastery.com/regression-tutorial-keras-deep-learning-library-python/

**Comment by ArioBattolla** [comment]
Hi,
I did not find any complete example how to build MLP for simple regressions. 
I think an autokeras code for MLP Boston house price dataset, as suggested by itsergiu, could be really of great help!
