### ISSUE TITLE
Feature request: add model export and load for TextClassifier

### ISSUE THREAD

**Issue by William8Work** [keras-team/autokeras#577]
### Feature Description

Add Model Export and Model Load Function to TextClassifier
### Reason

TextClassifier has been updated recently. However, after training, although I can make predict calls but there is no method to export or save the model into file. This creates issue for repeated prediction or predictions that are needed to integrated with other application scenarios without going through the training and fit.

There are issues reported on this related topic: https://github.com/jhfjhfj1/autokeras/issues/394#issue-394011769
### Solution

Provide an export_keras_model() method to export the model to file, and provide another load_model() to read model from file.

By reading through the codes, it seems that there is a variable self.output_model_file under text_supervised.py has the model file with name pytorch_model.bin. Adding export and load function should be relatively easy. If this is the right approach, I am happy to help to produce these two methods and submit a pull request for you all to review.

Thanks,

William.

**Comment by gladkikhartem** [comment]
model is automatically exported after training to /tmp/...
To set directory i've used this method:

```
clf = TextClassifier(verbose=True)
clf.output_model_file = **filename**
```
