### ISSUE TITLE
Image with Ubuntu and Anaconda and installed auto-keras for VMWare or VirtualBox.

### ISSUE THREAD

**Issue by itsergiu** [keras-team/autokeras#601]
I installed Anaconda on Windows 10. It works fine with keras.
I tried to install autokeras, but I get errors with numpy libraries.

In order to have a quick start and accelerate tests with auto-keras I suggest and ask to create and provide an image for VMWare or VirtualBox with Ubuntu and Anaconda and installed autokeras .

**Comment by garawalid** [comment]
@itsergiu 
It's possible to use Docker like a virtual machine. 
First, you need to [install Docker for Windows](https://docs.docker.com/docker-for-windows/install/). 

Then download Auto-Keras docker image with devel tag. This image uses Ubuntu 18.04 as a base. 
```bash
$ docker pull garawalid/autokeras:devel
```
You need to create a volume to persist your data in the container. 
```
$ docker volume create volume-autokeras
```
This command will start Auto-Keras container
```
$ docker run -it -v volume-autokeras:/app --shm-size 2G garawalid/autokeras:devel /bin/bash
```



When you install a new package in your container, you need to save your container like this :

```
$ docker ps -a 
```
```
b52fe902f038        garawalid/autokeras:devel                  "/bin/bash"              About a minute ago   Exited (1) 3 seconds ago                                         goofy_jackson
```
```
$ docker commit <container_id> garawalid/autokeras:devel
```
where `container_id` equals to `b52fe902f038` in this case.
