### ISSUE TITLE
ImageClassifier1D for raw vital signs classification

### ISSUE THREAD

**Issue by maystroh** [keras-team/autokeras#617]
### Bug Description
I'm trying to use ImageClassifier1D to find the optimal network that classifies raw vital signs (ECG, PPG etc...). I'm not sure if this is the right classifier to use in this case but I just wanted to give it a try. 

### Reproducing Steps
Here you can find the code of the main classes I'm using:
```
class Preproc:

    def __init__(self, signals, labels):
        self.mean, self.std = compute_mean_std(signals)
        self.classes = set(l for label in labels for l in label)
        self.int_to_class = dict( zip(range(len(self.classes)), self.classes))
        self.class_to_int = {c : i for i, c in self.int_to_class.items()}

    def process(self, x, y):
        return self.process_x(x), self.process_y(y)

    def process_x(self, x):
        x = pad(x, type='train')
        x = (x - self.mean) / self.std
        x = x[:, :, None]
        return x

    def process_y(self, y):
        y = pad([[self.class_to_int[c] for c in s] for s in y], type='gt', val=0,  dtype=np.int32)
        y = keras.utils.np_utils.to_categorical(y, num_classes=len(self.classes))
        return y

def pad(x, type, val=0, dtype=np.float32):
    max_len = max(len(i) for i in x)
    padded = np.full((len(x), max_len), val, dtype=dtype)
    for e, i in enumerate(x):
        if 'train' in type:
            padded[e, : len(i)] = i
        elif 'gt' in type:
            padded[e, :] = [i[0]] * max_len

    return padded

def compute_mean_std(x):
    x = np.hstack(x)
    return (np.mean(x).astype(np.float32), np.std(x).astype(np.float32))

class Dataset:

    #Path of file that contains the dataset
    dataset_path = ''

    interval_time = 256 
    column_to_classify = ''
    column_values = []
    is_training=False

    signal_sampling_frequency = 125
    def __init__(self, file_path, column_to_classify, column_values, window_time=2.0, training=False):
        self.interval_time = int(window_time * self.signal_sampling_frequency)
        self.dataset_path = file_path
        self.column_to_classify = column_to_classify
        self.column_values = column_values
        self.is_training = training

    def recursive_len(self, item):
        if type(item) == list:
            return sum(self.recursive_len(subitem) for subitem in item)
        else:
            return 1

    def read_csv_GT(self, type_dataset):
        data_x = []
        data_y = []
        df = pd.read_csv(self.dataset_path, sep='|')
        for index, row in tqdm.tqdm(df.iterrows(), total=df.shape[0]):
            if row['Dataset'] in type_dataset:
                file_data = np.fromfile(row['patient_file'], dtype='>u2')
                ranges = row['range_selected'].split(":")
                data_to_treat = file_data[int(ranges[0]):int(ranges[1])]

                segments = []
                signal_label = 1 if (row[self.column_to_classify] == self.column_values[0]) else 0
                for x in range(0, len(data_to_treat), int(self.interval_time)):
                    if x + int(self.interval_time) <= len(data_to_treat):
                        segments.append(data_to_treat[x:x + self.interval_time])

                trunc_samp = self.interval_time * int(len(data_to_treat) / self.interval_time)
                data_x.append(data_to_treat[:trunc_samp])
                data_y.append([row[self.column_to_classify]] * len(segments))

        return data_x, data_y

    def load_training_dataset(self):
        return self.read_csv_GT(['Train', 'Dev'])

    def load_dev_dataset(self):
        return  self.read_csv_GT('Dev')

    def load_test_dataset(self):
        return self.read_csv_GT('Test')

```
Here is the main function:

```
from dataset import Dataset
import load
train = dataset.load_training_dataset()
preproc = load.Preproc(*train)
train_x, train_y = preproc.process(*train)
clf = ImageClassifier1D(path="./automodels/", verbose=True, augment=False)  # Give a custom path of your choice
    clf.fit(train_x, train_y, time_limit=30 * 60)
```

Here is the output:

> File "auto/train.py", line 115, in <module>
>     train(args, params)
>   File "auto/train.py", line 97, in train
>     clf.fit(train_x, train_y, time_limit=30 * 60)
>   File "/usr/local/lib/python3.6/site-packages/autokeras/image/image_supervised.py", line 130, in fit
>     super().fit(x, y, time_limit)
>   File "/usr/local/lib/python3.6/site-packages/autokeras/supervised.py", line 126, in fit
>     random_state=42)
>   File "/usr/local/lib/python3.6/site-packages/sklearn/model_selection/_split.py", line 2184, in train_test_split
>     arrays = indexable(*arrays)
>   File "/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 260, in indexable
>     check_consistent_length(*result)
>   File "/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 235, in check_consistent_length
>     " samples: %r" % [int(l) for l in lengths])
> ValueError: Found input variables with inconsistent numbers of samples: [231, 111342]

### Expected Behavior
First of all, I'm not sure if I'm using it the right way or ImageClassifier1D is the right classifier to use, so please help. Also, I still don't know where the problem is coming from. I'm sure it's coming from format of the data and how they are formatted but not sure how to fix it. 

Any help would be appreciated.

### Setup Details
Include the details about the versions of:
 - OS type and version: Singularity image with ubuntu 16.04
 - Python: 3.6
 - autokeras: using the latest docker image garawalid/autokeras:latest
 - scikit-learn: using the latest docker image garawalid/autokeras:latest
 - numpy: using the latest docker image garawalid/autokeras:latest
 - keras: 2.2.4
 - scipy: using the latest docker image garawalid/autokeras:latest
 - tensorflow: 1.12.0

**Comment by simgunz** [comment]
From my understanding Y data should be passed as a 1D array of labels, not as an one-hot-encoded 2D array.
