### ISSUE TITLE
Runerror when training model 136

### ISSUE THREAD

**Issue by xujiameng** [keras-team/autokeras#620]
I ran image categorization on the workstation, and when I ran to 136 models, I showed such errors.

RuntimeError : Given groups=1 , weight of size [ 128 , 192 , 1] , expected input [ 128, 256 , 83 ] to have 192 channels , but got 256 channels instead

Has anybody ever had the same problem?

**Comment by zhoukaisheng** [comment]
我也是？然后就卡住了
