### ISSUE TITLE
pip install autokeras fails on torch ==1.1.0

### ISSUE THREAD

**Issue by christian-steinmeyer** [keras-team/autokeras#622]
### Bug Description
When executing `pip install autokeras`, I get the following message:
`Could not find a version that satisfies the requirement torch==1.0.1.post2 (from autokeras) (from versions: 0.1.2, 0.1.2.post1)
No matching distribution found for torch==1.0.1.post2 (from autokeras)`

### Reproducing Steps
  * Step 1: set up anaconda environment
  * Step 2: install pytorch via their website's recommended command: `conda install pytorch-cpu torchvision-cpu -c pytorch`
  * Step 3: try to install autokeras via `pip install autokeras`
  * Step 4: get the following output:

```
Collecting autokeras
  Downloading https://files.pythonhosted.org/packages/c2/32/de74bf6afd09925980340355a05aa6a19e7378ed91dac09e76a487bd136d/autokeras-0.4.0.tar.gz (67kB)
    100% |████████████████████████████████| 71kB 1.3MB/s
Collecting scipy==1.2.0 (from autokeras)
  Downloading https://files.pythonhosted.org/packages/c4/0f/2bdeab43db2b4a75863863bf7eddda8920b031b0a70494fd2665c73c9aec/scipy-1.2.0-cp36-cp36m-win_amd64.whl (31.9MB)
    100% |████████████████████████████████| 31.9MB 508kB/s
Requirement already satisfied: tensorflow==1.13.1 in c:\[...]\lib\site-packages (from autokeras) (1.13.1)
Collecting torch==1.0.1.post2 (from autokeras)
  Could not find a version that satisfies the requirement torch==1.0.1.post2 (from autokeras) (from versions: 0.1.2, 0.1.2.post1)
No matching distribution found for torch==1.0.1.post2 (from autokeras)
```

### Expected Behavior
Autokeras is installed without error.

### Setup Details
Include the details about the versions of:
 - OS type and version: Windows 10 Version	10.0.17763 Build 17763
 - Python: 3.6.8 (anaconda)
 - autokeras: 0.4.0
 - scikit-learn: 0.20.3
 - numpy:1.16.2
 - keras: 2.2.4
 - scipy:1.2.1
 - tensorflow:1.13.1
 - pytorch:1.1.0

**Comment by QierLi** [comment]
I have exactly the same problem with you

**Comment by karlknaub** [comment]
Me too.

**Comment by rkhaghi** [comment]
Same problem any update?

**Comment by yckoong** [comment]
me too, same issue here.

**Comment by PotatoPalooza** [comment]
The same problem here, I am also on windows 10 and running Python 3.6.8. Any workarounds yet? I will try switching python versions if that will do anything.

**Comment by phier77** [comment]
You can switch to autokeras0.3.7 & pytorch1.0.1

**Comment by PotatoPalooza** [comment]
> You can switch to autokeras0.3.7 & pytorch1.0.1

I tried this but using the pip installer it still won't go through with the error. "ERROR: Could not find a version that satisfies the requirement torch==1.0.1" it seems the issue is it is trying to pip install torch by name which does not seem to work.

**Comment by JJSeah** [comment]
I solved the issue by changing the setup.py file which I have attached below. Hope this helps.


from distutils.core import setup
from setuptools import find_packages

setup(
    name='autokeras',
    packages=find_packages(exclude=('tests',)),
    install_requires=['scipy==1.2.0',
                      'tensorflow==1.13.1',
                      'torch==1.1.0',
                      'torchvision==0.2.2.post3',
                      'numpy==1.16.1',
                      'scikit-learn==0.20.2',
                      'scikit-image==0.14.2',
                      'tqdm==4.31.0',
                      'imageio==2.5.0',
                      'requests==2.21.0'
                      ],
    version='0.4.0',
    description='AutoML for deep learning',
    author='DATA Lab at Texas A&M University',
    author_email='jhfjhfj1@gmail.com',
    url='http://autokeras.com',
    download_url='https://github.com/keras-team/autokeras/archive/0.3.7.tar.gz',
    keywords=['AutoML', 'keras'],
    classifiers=[]
)

**Comment by JasonMDSI** [comment]
Hi JJSeah, I'm new to Anaconda/Python so could you please tell me where I can find that setup.py file?

**Comment by JJSeah** [comment]
> Hi JJSeah, I'm new to Anaconda/Python so could you please tell me where I can find that setup.py file?

Hi Jason, you can download the setup.py file from this repo or just create a new python file and change the code accordingly above. You can run the python file by [python setup.py install] in your terminal to began the installation.

Hope this helps!

**Comment by JasonMDSI** [comment]
Hi JJSeah, thank you for your quick response. However when I run the setup.py file in my Windows 7 command prompt, I've got this error below. It seemed python couldn't recognize the function setup(name='autokeras', ....). Do you have any ideas how to resolve this?

D:\Users\jason>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    setup(
NameError: name 'setup' is not defined

**Comment by JasonMDSI** [comment]
Hi JJSeah, thank you for your quick response. However when I run the setup.py file in my Windows 7 command prompt, I've got this error below. It seemed python couldn't recognize the function setup(name='autokeras', ....). Do you have any ideas how to resolve this?

D:\Users\jason>python setup.py install
Traceback (most recent call last):
File "setup.py", line 1, in 
setup(
NameError: name 'find_packages' is not defined

**Comment by yckoong** [comment]
> I solved the issue by changing the setup.py file which I have attached below. Hope this helps.
> 
> from distutils.core import setup
> from setuptools import find_packages
> 
> setup(
> name='autokeras',
> packages=find_packages(exclude=('tests',)),
> install_requires=['scipy==1.2.0',
> 'tensorflow==1.13.1',
> 'torch==1.1.0',
> 'torchvision==0.2.2.post3',
> 'numpy==1.16.1',
> 'scikit-learn==0.20.2',
> 'scikit-image==0.14.2',
> 'tqdm==4.31.0',
> 'imageio==2.5.0',
> 'requests==2.21.0'
> ],
> version='0.4.0',
> description='AutoML for deep learning',
> author='DATA Lab at Texas A&M University',
> author_email='[jhfjhfj1@gmail.com](mailto:jhfjhfj1@gmail.com)',
> url='http://autokeras.com',
> download_url='https://github.com/keras-team/autokeras/archive/0.3.7.tar.gz',
> keywords=['AutoML', 'keras'],
> classifiers=[]
> )

Successfully install using `setup.py` on terminal 
![image](https://user-images.githubusercontent.com/29967331/58065861-b3f73680-7bb9-11e9-9b5c-6d37209e3ec9.png)

but prompt error when `import autokeras`, any idea?
![image](https://user-images.githubusercontent.com/29967331/58065927-f587e180-7bb9-11e9-82f2-f5a858e6f527.png)

**Comment by JasonMDSI** [comment]
@yckoong, thanks for the tip. After importing find_packages, I could see that autokeras installed in my anaconda base environment, and got exactly the same error **No module named 'autokeras'**

**Comment by JasonMDSI** [comment]
@yckoong, thanks for the tip. After importing find_packages, I could see that autokeras installed in my anaconda base environment, then got exactly the same error No module named 'autokeras'

**Comment by JasonMDSI** [comment]
@yckoong, thanks for the tips as I was able to run the setup.py file and saw that autokeras installed in my anaconda base environment. I also got exactly the same error **No module named 'autokeras'** when importing it in Jupyter notebook.

**Comment by phier77** [comment]
> > I solved the issue by changing the setup.py file which I have attached below. Hope this helps.
> > from distutils.core import setup
> > from setuptools import find_packages
> > setup(
> > name='autokeras',
> > packages=find_packages(exclude=('tests',)),
> > install_requires=['scipy==1.2.0',
> > 'tensorflow==1.13.1',
> > 'torch==1.1.0',
> > 'torchvision==0.2.2.post3',
> > 'numpy==1.16.1',
> > 'scikit-learn==0.20.2',
> > 'scikit-image==0.14.2',
> > 'tqdm==4.31.0',
> > 'imageio==2.5.0',
> > 'requests==2.21.0'
> > ],
> > version='0.4.0',
> > description='AutoML for deep learning',
> > author='DATA Lab at Texas A&M University',
> > author_email='[jhfjhfj1@gmail.com](mailto:jhfjhfj1@gmail.com)',
> > url='http://autokeras.com',
> > download_url='https://github.com/keras-team/autokeras/archive/0.3.7.tar.gz',
> > keywords=['AutoML', 'keras'],
> > classifiers=[]
> > )
> 
> Successfully install using `setup.py` on terminal
> ![image](https://user-images.githubusercontent.com/29967331/58065861-b3f73680-7bb9-11e9-9b5c-6d37209e3ec9.png)
> 
> but prompt error when `import autokeras`, any idea?
> ![image](https://user-images.githubusercontent.com/29967331/58065927-f587e180-7bb9-11e9-82f2-f5a858e6f527.png)

me too

**Comment by JJSeah** [comment]
it might be because you didnt install the models into conda but in your computer environment

**Comment by JasonMDSI** [comment]
Hi JJSeah, 
I think you're right: I see autokeras folder resides outside AppData folder which contains site-packages. I did follow the instruction of running [python setup.py installation] in the windows command prompt, so why didn't it work? Can you tell what I did wrong? Thanks
![image](https://user-images.githubusercontent.com/11934573/58098961-f8b4b900-7c1d-11e9-9b36-4617033b314c.png)

**Comment by phier77** [comment]
![image](https://user-images.githubusercontent.com/17315826/58115938-b8f5cd80-7c2d-11e9-87ad-97a4a02898eb.png)
I met the same problem with you.@JasonMDSI It showed "No module named autokeras"when I tried to import autokeras in Jupyter Notebook.Then I download the file named autokeras-master from github and  I put the autokeras file under the file named "site-packages" under created environment "autokeras" .Finally,it works.Before traning models, I suggesst you use pip to install nvidia apex to speed up because autokeras 0.4 uses pytorch to train models rather than tensorflow.

**Comment by JasonMDSI** [comment]
Hi Phier77, thanks for your great workaround! It worked!!! Would you mind clarifying how you also managed to have folders autokeras.egg-info and autokeras-0.4.0-py3.6.egg in your site-packages? should I move my folder autokeras.egg-info into my site-packages directory? Is cudatoolkit for gpu laptop? Mine one is cpu only so no need to install pytorch torchvision cudatoolkit=8? Thanks

**Comment by JordanMakesMaps** [comment]
#639 brought up a good point. Not sure if switching the URL to 0.4.0 solves any of the issues discussed here, but making that correction in the setup.py file along with starting from a fresh anaconda environment (python==3.6) and doing the following:

1.) installing pytorch 1.0.1 and torchvision from [here](https://pytorch.org/get-started/previous-versions/)
2.) removing the version of numpy just installed (pip remove numpy)
3.) installing by hand (using conda install, not pip) the rest of the dependencies
4.) git cloning apex, python setup.py install

results in a working version of autokeras with the only issue being a depreciation warning from sklearn:
"Cloudpickle.py, the imp module is deprecated in favor of importlib"

Really hope that helps someone!

![image](https://user-images.githubusercontent.com/8714759/58510511-e4fddb00-8166-11e9-9aa0-2131fe3e00d6.png)

**Comment by wangwuqi** [comment]
I have installed 1.13.1 tensorflow-gpu, and when i pip install keras, it downloads tensorflow again...

**Comment by nlovlyn-splunk** [comment]
I am seeing this error on Windows Server 2016 with Python 3.6.8 when following the standard installation instructions that utilize pip instead of setup.py. 

`C:\Windows\system32>systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows Server 2016 Datacenter
OS Version:                10.0.14393 N/A Build 14393

C:\Windows\system32>python --version
Python 3.6.8

C:\Windows\system32>pip --version
pip 19.1.1 from c:\program files\python36\lib\site-packages\pip (python 3.6)

C:\Windows\system32>pip install autokeras
Collecting autokeras
  Using cached https://files.pythonhosted.org/packages/c2/32/de74bf6afd09925980340355a05aa6a19e7378ed91dac09e76a487bd136d/autokeras-0.4.0.tar.gz
Collecting scipy==1.2.0 (from autokeras)
  Using cached https://files.pythonhosted.org/packages/c4/0f/2bdeab43db2b4a75863863bf7eddda8920b031b0a70494fd2665c73c9aec/scipy-1.2.0-cp36-cp36m-win_amd64.whl
Collecting tensorflow==1.13.1 (from autokeras)
  Using cached https://files.pythonhosted.org/packages/bf/58/34bfa8fa17f86333361172b3b502e805195180f19a7496ad0f6149138d55/tensorflow-1.13.1-cp36-cp36m-win_amd64.whl
Collecting torch==1.0.1.post2 (from autokeras)
  ERROR: Could not find a version that satisfies the requirement torch==1.0.1.post2 (from autokeras) (from versions: 0.1.2, 0.1.2.post1)
ERROR: No matching distribution found for torch==1.0.1.post2 (from autokeras)

C:\Windows\system32>
`

**Comment by nba2020** [comment]
> > Hi JJSeah, I'm new to Anaconda/Python so could you please tell me where I can find that setup.py file?
> 
> Hi Jason, you can download the setup.py file from this repo or just create a new python file and change the code accordingly above. You can run the python file by [python setup.py install] in your terminal to began the installation.
> 
> Hope this helps!
Thanks for your hint I followed your reply and still getting the following errors
Could you please help me with that?:
```
running install
running bdist_egg
running egg_info
writing autokeras.egg-info\PKG-INFO
writing dependency_links to autokeras.egg-info\dependency_links.txt
writing requirements to autokeras.egg-info\requires.txt
writing top-level names to autokeras.egg-info\top_level.txt
reading manifest file 'autokeras.egg-info\SOURCES.txt'
writing manifest file 'autokeras.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
warning: install_lib: 'build\lib' does not exist -- no Python modules to install

creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\EGG-INFO
copying autokeras.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying autokeras.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying autokeras.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying autokeras.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying autokeras.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist\autokeras-0.4.0-py3.7.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing autokeras-0.4.0-py3.7.egg
Removing c:\users\siorb\appdata\local\programs\python\python37\lib\site-packages\autokeras-0.4.0-py3.7.egg
Copying autokeras-0.4.0-py3.7.egg to c:\users\siorb\appdata\local\programs\python\python37\lib\site-packages
autokeras 0.4.0 is already the active version in easy-install.pth

Installed c:\users\siorb\appdata\local\programs\python\python37\lib\site-packages\autokeras-0.4.0-py3.7.egg
Processing dependencies for autokeras==0.4.0
Searching for torch==1.1.0
Reading https://pypi.org/simple/torch/
No local packages or working download links found for torch==1.1.0
error: Could not find suitable distribution for Requirement.parse('torch==1.1.0')
```

**Comment by christian-steinmeyer** [comment]
If you have a clean (conda) environment, clone the current state of the git project, and install all requirements from it, it should work. Details can be found on the website under "getting started" > without pip.

**Comment by alexsiormpas** [comment]
@christian-steinmeyer 
- What does clean conda environment mean? No package installed?
- COuld you please share the link  to the website you're mentioning so I can read what I need to do.
Sorry very new to Python :)

**Comment by christian-steinmeyer** [comment]
@alexsiormpas 
[Conda](https://docs.conda.io/en/latest/) (or Anaconda) is a package manager for the python language. With it, you can create multiple environments, comparable to "Virtual Machines", in which you can install, uninstall etc. packages with certain requirements without affecting your overall system. As a result, you can install autokeras for example, without it conflicting with any other projects you might have, if you use a dedicated environment. A minimal version that you could have a look at is [Miniconda](https://docs.conda.io/en/latest/miniconda.html). You'll find plenty of documentation and materials online.

[This](https://autokeras.com/start/) is the website, I mentioned. There, you'll finde these commands that should be executed:
```
pip install -r requirements.txt
python setup.py install
```

**Comment by b3326023** [comment]
@christian-steinmeyer 
Excuse me, I've downloaded the newest version of code from github, but I don't see the requirements.txt. Where is it?

**Comment by christian-steinmeyer** [comment]
> @christian-steinmeyer
> Excuse me, I've downloaded the newest version of code from github, but I don't see the requirements.txt. Where is it?

It looks like it was replaced by another workflow and the content is now present in the form of the `setup.py` file.
