### ISSUE TITLE
No documentation for Binary Classification

### ISSUE THREAD

**Issue by danucalovj** [keras-team/autokeras#623]
Good project, but lacking documentation, hence opening a custom issue here.

Every example provided in the website uses pretrained models and built-in classifiers without documentation on using those with custom data.

Example, how would I find documentation on implementing something like the famous Pima Indians Keras Example??? Link:

https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/

In short, I'd like to A) Load my custom data B) train and test my model based on this data and set a column as a prediction target.

If AutoKeras is being designed for non-"experts" this type of scenario needs to be covered in the documentation or the project is falling tremendously short of it's intent.

Needed:

Binary Classification examples
Setting target columns for above
Multiclass Classification examples

All of the above without using preloaded models.

**Comment by huaiyizhao** [comment]
Can't agree more. We need more documentation and examples dealing with custom data. And  a bit more classifiers.
