### ISSUE TITLE
Adding predict probabilities

### ISSUE THREAD

**Issue by rwtam121** [keras-team/autokeras#630]
Hi Autokeras team,
I know autokeras can predict classes using results = clf.predict(x_test), but I'm wondering if you have another function similar to predict_proba that can also provide the confidence of those predictions.

**Comment by zhoukaisheng** [comment]
Like you, I also need to get the probability of the final prediction. My solution is as follows:
add following code to the supervised.py
`    def predict_proba(self, x_test):
        """Return predict probability results for the testing data.

        Args:
            x_test: An instance of numpy.ndarray containing the testing data.

        Returns:
            A numpy.ndarray containing the predictions for the testing data.
        """
        x_test = self.preprocess(x_test)
        test_loader = self.data_transformer.transform_test(x_test)
        return self.cnn.predict(test_loader)`

**Comment by taylor4712** [comment]
What does the argument " self" take?

**Comment by takeofuture** [comment]
I have the same question coming up.
Is thee any progress?
What is self? Model object loaded from ? 
Ex.
clf = ak.ImageClassifier
clf.fit(x_train, y_train)
model = clf.export_model()
So  passing like predict_proba(model, x_test), I am a bit confused with "self".
Thank you!

**Comment by leandroimail** [comment]
I Have the same issue with multiclass probabilities. I need to know what is the class predicted but I do not have certain. Hava a simple way to solve this problem?
