### ISSUE TITLE
ImageRegressor for image-to-vector regression?

### ISSUE THREAD

**Issue by zhulingchen** [keras-team/autokeras#633]
### Feature Description

Currently, the _ImageRegressor_ class only accepts image-to-scalar regression, not image-to-vector regression, which means that _y_ for training and testing can only be one-dimension scalars rather than multiple-dimension vectors.

### Reason

In _image_supervised.py_, within the definition of the class _ImageRegressor_, the following function _transform_y_ is defined (in Line 277-278 as of May 18, 2019) as:

    def transform_y(self, y_train):
        return y_train.flatten().reshape(len(y_train), 1)

require the input training data of size 1 in the second dimension while the first dimension is the number of training samples.

### Solution

Could you think of a way to let _ImageRegressor_ support image-to-vector regression?

**Comment by BDANG** [comment]
Pending pull request: https://github.com/keras-team/autokeras/pull/584
