### ISSUE TITLE
AutoKeras cannot save Keras models anymore?

### ISSUE THREAD

**Issue by zhulingchen** [keras-team/autokeras#634]
When I try to save the found best model after clf.fit(x, y), I cannot save the found best model using the command as below, like other people have successfully used before:

clf.export_keras_model('my_model.h5')

as the following error is indicated:

AttributeError: 'Graph' object has no attribute 'produce_keras_model'

**Comment by zhulingchen** [comment]
I also notice that AutoKeras 0.4.0 starts to use PyTorch to find the best model rather than TensorFlow. How do I specify the latest version of AutoKeras to use the TensorFlow backend instead?

**Comment by doyled-it** [comment]
So, in `autokeras/backend/__init__.py`, I noticed this:

```
from autokeras.constant import Constant

class Backend:
backend = torch if Constant.BACKEND == 'torch' else tensorflow
```

And if you follow that into `autokeras/constant.py` it looks like `Constant.BACKEND` default set to `'torch'`. We just set that to 'tensorflow' in our environment, but there should be a way to change this.

**Comment by zhulingchen** [comment]
> 
> 
> So, in [`autokeras/backend/__init__.py`](https://github.com/keras-team/autokeras/blob/master/autokeras/backend/__init__.py), I noticed this:
> 
> ```
> from autokeras.constant import Constant
> 
> class Backend:
> backend = torch if Constant.BACKEND == 'torch' else tensorflow
> ```
> 
> And if you follow that into [`autokeras/constant.py`](https://github.com/keras-team/autokeras/blob/master/autokeras/constant.py) it looks like `Constant.BACKEND` default set to `'torch'`. We just set that to `'tensorflow'` in our environment, but there should be a way to change this.
> 
> By changing `autokeras/backend/__init__.py` you can get it working now, but this should in no way close this issue haha:
> `backend = tensorflow`

Yes. so if autokeras stopped supporting keras why do you call "autokeras" instead of "autotorch"? It confuses me.

**Comment by doyled-it** [comment]
> Yes. so if autokeras stopped supporting keras why do you call "autokeras" instead of "autotorch"? It confuses me.

I'm not on the autokeras project. I just also ran into this problem and found your issue open. It didn't stop supporting keras though. Keras != tensorflow and has been able to be run with different backends for a while (theano, tensorflow, and pytorch). I'm not sure why they set the default to pytorch and don't allow you to change it.

**Comment by zhulingchen** [comment]
> 
> 
> > Yes. so if autokeras stopped supporting keras why do you call "autokeras" instead of "autotorch"? It confuses me.
> 
> I'm not on the autokeras project. I just also ran into this problem and found your issue open. It didn't stop supporting keras though. Keras != tensorflow and has been able to be run with different backends for a while (theano, tensorflow, and pytorch). I'm not sure why they set the default to pytorch and don't allow you to change it.

Keras supports TensorFlow, Theano, CNTK (from Microsoft) as backends, and I do not think Keras supports PyTorch as backends.

**Comment by josai** [comment]
having the same issue even with backend = tensorflow

**Comment by mansiag05** [comment]
Hi @josai 
I am also facing the same issue/error.
Were you able to export the keras model?

**Comment by rubenhekster** [comment]
@josai, same issue, not able to export to keras model, however exporting autokeras model to h5 works fine. Are you using python3.6?

**Comment by rh-ia** [comment]
Same issue here, autokeras-model export works fine keras export model, has same error. Are you on python3.6?

**Comment by liuyuancc** [comment]
I have the same problem

**Comment by wshzd** [comment]
python3.6.5
error as follows:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-d1e3316252b2> in <module>()
----> 1 clf.export_keras_model("hezd.h5")

~/anaconda3/lib/python3.6/site-packages/autokeras/supervised.py in export_keras_model(self, model_file_name)
    250             Save the architecture, weights, and optimizer state of the best model
    251         """
--> 252         self.cnn.best_model.produce_keras_model().save(model_file_name)
    253 
    254     def predict(self, x_test):

AttributeError: 'Graph' object has no attribute 'produce_keras_model'

**Comment by Swizz** [comment]
I have the same problem listed above. 
And would love to export the auto keras model into a valid keras model (then a tensorflow js model), but none of the solutions seem to work as intented.

Any update on this ?

**Comment by wshzd** [comment]
autokeras0.4.0
# save the model
clf.export_autokeras_model("keras.model")
# load the model
from autokeras.utils import pickle_from_file
model = pickle_from_file("keras.model")
results = model.evaluate(x_test, y_test)
print(results)
according to the above code, the result is ok.

**Comment by jplnasa5** [comment]
> autokeras0.4.0
> # save the model
> 
> clf.export_autokeras_model("keras.model")
> # load the model
> 
> from autokeras.utils import pickle_from_file
> model = pickle_from_file("keras.model")
> results = model.evaluate(x_test, y_test)
> print(results)
> # according to the above code, the result is ok.



but how to use in autokeras1.0?

**Comment by bozbil** [comment]
# for autokeras 1.0:

## save the model
model.save('my_model') 

## load the model
import tensorflow as tf
new_model = tf.keras.models.load_model('my_model')
