### ISSUE TITLE
how to show the network structure in examples/mnist.py

### ISSUE THREAD

**Issue by bannerLiao** [keras-team/autokeras#644]
i know that it generate such 0.graph ,  1.graph, but i do not how to open it and observe it？

**Comment by JordanMakesMaps** [comment]
I was interested in using AutoKeras to create a Keras model but after enough hassle I ended up using the following code from which I can build a Keras model or visualize using some of PyTorch's visualization tools.

      
       `clf = ImageClassifier(verbose=True, augment = True)

        print("\n--Training...")
        clf.fit(train_x, train_y, time_limit = training_time)

        print("\n--Finding final model...")
        clf.final_fit(train_x, train_y, test_x, test_y, retrain = False)
                    
        best_model = clf.cnn.best_model.produce_model()
        print(best_model)
        torch.save(best_model, output + "torch_best_model_trial_" + str(trial))`

with the printed output being:

![image](https://user-images.githubusercontent.com/8714759/58987071-c0c87c80-87ac-11e9-87c9-82d77422643f.png)

Hope that helps, and if anyone comes across a way to export a Keras model directly using AutoKeras 0.4.0 I would eternally grateful 🙌
