### ISSUE TITLE
Error in visualize.py,  'PortableImageClassifier' object has no attribute 'searcher'

### ISSUE THREAD

**Issue by bannerLiao** [keras-team/autokeras#647]
Traceback (most recent call last):
  File "visualize.py", line 30, in <module>
    visualize('test_autokeras_model.pkl')
  File "visualize.py", line 22, in visualize
    cnn_module.searcher.path = path
AttributeError: 'PortableImageClassifier' object has no attribute 'searcher'

**Comment by wukailu** [comment]
same problem+1
