### ISSUE TITLE
Exception occurred when using tensorflow as backend

### ISSUE THREAD

**Issue by chenjiazhonghw** [keras-team/autokeras#671]
### Bug Description

The following exceptions were caught when I used tensorflow as backend:
1. Exception occurred at train(): 'StubReLU' has no attribute 'import_weights_keras'
2. Exception occurred at train(): 'StubConv2d' has no attribute 'import_weights_keras'

### Reproducing Steps
  * Step 1: Change backend from PyTorch to Tensorflow, by modifying Constant.BACKEND defined in constant.py. ('torch' to 'tensorflow')
  * Step 2: Run /examples/a_simple_example/mnist.py.

### Expected Behavior

No exception caught

### Setup Details
Include the details about the versions of:
 - OS type and version: Ubuntu 16.04
 - Python: 3.7.3
 - autokeras: not installed, I ran it with the latest source code as of 2019.6.17
 - scikit-learn: 0.21.2
 - numpy: 1.16.4
 - keras: 2.2.4
 - scipy: 1.3.0
 - tensorflow: 1.13.1
 - pytorch: 1.1.0

### Additional context

In \autokeras\backend\tensorflow\model.py we can see the following code:
def set_keras_weight_to_stub(keras_layer, stub_layer):
    stub_layer.import_weights_keras(keras_layer)

I searched 'import_weights_keras' but could not find its declaration.

**Comment by leo-XUKANG** [comment]
same bug
