### ISSUE TITLE
ImportError: cannot import name classification_loss

### ISSUE THREAD

**Issue by humzaiqbal** [keras-team/autokeras#695]
### Bug Description
When I run the line `from autokeras import classification_loss` I get an `ImportError: cannot import name 'classification_loss'`
### Reproducing Steps
  * Run the line `from autokeras import classification_loss`

### Expected Behavior
The module `classification_loss` to be imported

### Setup Details
Include the details about the versions of:
 - OS type and version: Mac OSX `10.13.6`
 - Python: `3.6.5`
 - autokeras: `0.4.0`
 - scikit-learn: `0.2.0`
 - numpy: `1.16.1`
 - keras: `2.2.4`
 - scipy: `1.2.0`
 - tensorflow: `1.14.0`
 - pytorch: `1.0.1.post2`

Any help would be appreciated, thanks

**Comment by cdelcroix** [comment]
Hi, 

You are using the legacy branch (autokeras 0.4), you should try:

`from autokeras.backend.torch.loss_function import classification_loss`

(or `from autokeras.backend.tensorflow.loss_function import classification_loss` depending of your backend)

An example can be found [there](https://github.com/keras-team/autokeras/blob/legacy/examples/net_modules/mlp_module.py
)

**Comment by manugarri** [comment]
@cdelcroix  when you say 0.4 is the legacy branch, what do you mean? is the version available in pipy isnt it?

**Comment by cdelcroix** [comment]
@manugarri [the version available on pypi is 0.4.0](https://pypi.org/project/autokeras/). According to the [readme](https://github.com/keras-team/autokeras/blob/master/README.md) of the master branch of this repo @humzaiqbal should use 

> the legacy branch (...) to checkout the 0.4 version.

**Comment by cdelcroix** [comment]
@manugarri yes, [the doc](https://autokeras.com/) is confusing. Some examples, for example the [CnnModule tutorial](https://autokeras.com/start/) are not made for autokeras 0.4 = pipy autokeras.

Autokeras team should make a doc like [the PyTorch one](https://pytorch.org/docs/stable/index.html), where on the top left you can choose your lib version.
