### ISSUE TITLE
Specify corresponding GPU in autokeras training 

### ISSUE THREAD

**Issue by momo1986** [keras-team/autokeras#712]
Hello,

My autokeras version is autokeras-legacy with version 0.4.0.

My keras version is 2.2.4.

I have 4 GPUs in my training platform.

I only use 3 with specifying:

>     import os
>     os.environ['CUDA_VISIBLE_DEVICES'] ='0,1,2'

However, the auto-ml program is so overbearing that it utilizes four GPUs.

How can I avoid the situation that autokeras program skip the cuda-device expected to be free.

Thanks & Regards!
Momo

**Comment by francotheengineer** [comment]
Have you tired 'export CUDA_VISIBLE_DEVICES=0,1,2' in the shell (eg bash) that you're running? I know that `os.environ`should do this but I've had this issue before.
