### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by zhenghongpeng** [keras-team/autokeras#720]
### Bug Description

In
autokeras/examples/visualizations/visualize.py  
line 4
from autokeras import pickle_from_file

should be 
from autokeras.utils import pickle_from_file

**Comment by crypdick** [comment]
The same import error happens in `examples/portable_models/portable_load.py`. It looks like this was solved with https://github.com/keras-team/autokeras/pull/719 but then the PR was closed without merging?
