### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torch==1.0.1.post2 (from autokeras) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2) ERROR: No matching distribution found for torch==1.0.1.post2 (from autokeras)

### ISSUE THREAD

**Issue by shapatel13** [keras-team/autokeras#763]
<!Hello I am having trouble installing autokeras onto my computer.  I am using anaconda, i have downgraded to version 3.6.  I have manually tried to install torch 1.0.1, but nothing has worked so far.  I have been working on this for about a month now, any help would be appreciated.  
**If you are reporting a bug:**
*  Verify that your issue is not being currently addressed by other issues or pull requests.
*  Please note that Auto-Keras is only compatible with **Python 3.6**.
*  Tag the issue with the `bug report` tag.
-->

### Reproducing Steps
  * Step 1: ...pip install autokeras
  * Step 2: ...

### Setup Details
Include the details about the versions of:
 - OS type and version:
 - Python: 
 - autokeras: 
 - scikit-learn:
 - numpy:
 - keras:
 - scipy:
 - tensorflow:
 - pytorch:

**Comment by Naveenagv** [comment]
I have been trying to install auto keras and I'm having the same error. Can anybody help me on how to resolve the error.

**Comment by zthcool** [comment]
you may want to install autokeras 0.4 in Windows,the error "torch==1.0.1.post2" shoud be installed in Linux.Try it in Ubuntu will work well
