### ISSUE TITLE
Ask about version 1.0.

### ISSUE THREAD

**Issue by giangtranml** [keras-team/autokeras#794]
Hi team, thanks for your great work. So, when will the auto-keras version 1.0 be released?

**Comment by foodiehack** [comment]
Hey have you tested autokeras for text classification

**Comment by giangtranml** [comment]
Not yet, what's up?

**Comment by foodiehack** [comment]
Ok I having hard time using 1.0 version for text classification and there is no proper documentation for it. So needed some help.
0.4 lack some functionalities I want to use.

**Comment by yfq512** [comment]
@stale I use autokeras.StructuredDataClassifier, but I don't know how save model. I try many methods  ...,but it does' not work! Can you help me

**Comment by haifeng-jin** [comment]
@yfq512 
Here is a tutorial: https://autokeras.com/tutorial/structured_data_classification/
Let me know if it works or not.
Thanks.

**Comment by yfq512** [comment]
I can run code like this example.
But I want save model as ***.h5 file. I do not find some api about savemodel like imageclassition



发自我的iPhone


------------------ Original ------------------

**Comment by haifeng-jin** [comment]
@yfq512 You can first export the model as a Keras Model. Then call the save_model function of the Keras Model.
Am I understanding your needs correctly?
