### ISSUE TITLE
Examples don't work for both versions.

### ISSUE THREAD

**Issue by taylor4712** [keras-team/autokeras#803]
Hey, after a long time run i managed to download autokeras 1.0. and 0.4. I tried to do the examples on both versions and it did not work. 

Example : 
from keras.datasets import mnist
     from autokeras.image.image_supervised import ImageClassifier

    if __name__ == '__main__':
    (x_train, y_train), (x_test, y_test) = mnist.load_data()
    x_train = x_train.reshape(x_train.shape + (1,))
    x_test = x_test.reshape(x_test.shape + (1,))
    clf = ImageClassifier(verbose=True)
    clf.fit(x_train, y_train, time_limit=12 * 60 * 60)
    clf.final_fit(x_train, y_train, x_test, y_test, retrain=True)
    y = clf.evaluate(x_test, y_test)
    print(y)

from https://autokeras.com/start/

The error is : ModuleNotFoundError: No module named 'autokeras.image'

**Comment by rish-16** [comment]
Hey there!

Now you can access the `ImageClassifier` directly from the `autokeras` module as follows:

```python
import autokeras as ak
from tensorflow.keras.datasets import mnist

(xtrain, ytrain), (xtest, ytest) = mnist.load_data()
xtrain = xtrain.reshape([-1, 28, 28, 1])
xtest = xtest.reshape([-1, 28, 28, 1])

clf = ak.ImageClassifier(verbose=True)
clf.fit(xtrain, ytrain)
```

Hope this helps!

**Comment by taylor4712** [comment]
Thank your for your help!
But now the following error:

ModuleNotFoundError: No module named 'tensorflow' 

even though i have installed tensorflow..

Which version are you using? 0.4 or 1.0? because i have troubles of downloading 0.4 i have 1.0

**Comment by rish-16** [comment]
Hmm, that's odd. When I try it without the `verbose=True` flag, it works just fine. When I try it with the `validation_data` parameter it throws an error that says `validation_data` is not a parameter even though the code in the repo says so. 

Maybe, it'll work if you use the `verbose=True` flag:
```python
...
clf = ak.ImageClassifier(verbose=True)
clf.fit(xtrain, ytrain)
...
```

Can you please try this? It may work with the verbose flag. Also, worse case your `autokeras` library has not been updated yet. You can try upgrading via `pip`:
```bash
pip install --upgrade autokeras
```

Then, you can try running it again and checking if it works with/without the `verbose=True` flag.

Hope this helps!

**Comment by taylor4712** [comment]
Thank you, 

If I use it with the verbose=True flag it shows me this:

TypeError: init() got an unexpected keyword argument 'verbose'

for the line in clf = ak.ImageClassifier(verbose=True)

I did ugrade autokeras as you said, but it is already in the latest version it say "Requirement already up-todate, skipping upgrade" 

How did you install autokeras? Maybe my version does not work properly... i had some issues with it. 
I used: 

pip install git+git://github.com/keras-team/autokeras@master#egg=autokeras # for 1.0 version

from https://autokeras.com/

Thank you for your help!

**Comment by rish-16** [comment]
I followed the installation instructions in the README:
```bash
pip install autokeras
```
Regardless of using the `verbose=True` flag, the code `clf.fit(...)` works for me just fine.

**Comment by taylor4712** [comment]
That does not work for me because when i try 
pip install autokeras 

it shows me 
```
  ERROR: Could not find a version that satisfies the requirement torch==1.0.1.post2 (from autokeras) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.0.1.post2 (from autokeras)
```

**Comment by rish-16** [comment]
Ah ok. The README says that you need to use `pip3` to install it. Have you tried that?
```bash
pip3 install autokeras
```

Because `autokeras` is a library that can be installed using the latest version of `pip` (which is `pip3`).

**Comment by Goreg12345** [comment]
Hi there,

I'm facing the same issue. I'm using a conda environment
`
conda create -n autokeras python=3.6 tensorflow-gpu keras nb_conda
conda activate autokeras
`
If I use the latest version of pip3 and autokeras 0.4 during the installation the following error occurs:
`ERROR: Could not find a version that satisfies the requirement torch==1.0.1.post2 (from autokeras) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.0.1.post2 (from autokeras)`
If I use the latest version of pip3 and autokeras 1.0 the error `ValueError: Either validation_data or validation_splitshould be provided.` rises in the example of the Geeting Started Document. 
I used pip3:
`pip 19.3.1 from C:\Users\Georg\Anaconda3\envs\autokeras\lib\site-packages\pip (python 3.6)`

If I try to provide validation_split=0.8 the exception `KeyError: 'label_to_int'` rises, as well if I provide validation_data.

I also tried different versions of pip but no one worked.

I tried the example from autokeras.com for the Task API for 1.0, I tried the example for 0.4 and I tried the MNIST exmple of this repo, but all exited with validation data should be provided or label_to_int or No module named 'autokeras.image'.

I also tried everything in this thread but nothing did work.

**Comment by zthcool** [comment]
> Hi there,
> 
> I'm facing the same issue. I'm using a conda environment
> `conda create -n autokeras python=3.6 tensorflow-gpu keras nb_conda conda activate autokeras`
> If I use the latest version of pip3 and autokeras 0.4 during the installation the following error occurs:
> `ERROR: Could not find a version that satisfies the requirement torch==1.0.1.post2 (from autokeras) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2) ERROR: No matching distribution found for torch==1.0.1.post2 (from autokeras)`
> If I use the latest version of pip3 and autokeras 1.0 the error `ValueError: Either validation_data or validation_splitshould be provided.` rises in the example of the Geeting Started Document.
> I used pip3:
> `pip 19.3.1 from C:\Users\Georg\Anaconda3\envs\autokeras\lib\site-packages\pip (python 3.6)`
> 
> If I try to provide validation_split=0.8 the exception `KeyError: 'label_to_int'` rises, as well if I provide validation_data.
> 
> I also tried different versions of pip but no one worked.
> 
> I tried the example from autokeras.com for the Task API for 1.0, I tried the example for 0.4 and I tried the MNIST exmple of this repo, but all exited with validation data should be provided or label_to_int or No module named 'autokeras.image'.
> 
> I also tried everything in this thread but nothing did work.

I got the same question with you "error ValueError: Either validation_data or validation_splitshould be provided"
