### ISSUE TITLE
Export AutoKeras 1.0 model for AutoModel and GraphAutoModel

### ISSUE THREAD

**Issue by zhulingchen** [keras-team/autokeras#810]
I start to try your AutoKeras 1.0.0a and want to see how I could export the model by `ak.AutoModel` and `ak.GraphAutoModel`.

I tried Task API model export before: https://github.com/keras-team/autokeras/issues/634

But it seems AutoModel and GraphAutoModel no longer have `export_keras_model` and `export_autokeras_model` functions.

Any solutions?

**Comment by zhulingchen** [comment]
I dug into your source code and found you are using `kerastuner` for hyperparameter optimization. Therefore the automatically-searched and trained models are compatible with `tf.keras` models, so I should be able to use all related `tf.keras` callbacks and model-saving functionalities as shown in https://www.tensorflow.org/guide/keras/save_and_serialize.

**Comment by zhulingchen** [comment]
I think I can close the issue now.

**Comment by shivaji27** [comment]
Can you please  give any  example code. It would be great to export Auto -keras model into pure keras /tensorflow model so that it could be parsed  by  OpenCV DNN module.
Thanks
