### ISSUE TITLE
How to resume training with GraphAutoModel ?

### ISSUE THREAD

**Issue by AlkaSaliss** [keras-team/autokeras#813]
### Bug Description
In the Autokeras paper I read that : 
_**First, the user can
restore and continue a previous search which might be accidentally
killed. From the users’ perspective, the main difference of using
Auto-Keras comparing with the AutoML systems aiming at shallow
models is the much longer time consumption, since a number of
deep neural networks are trained during the neural architecture
search. It is possible for some accident to happen to kill the process
before the search finishes. Therefore, the search outputs all
the searched neural network architectures with their trained parameters
into a specific directory on the disk. As long as the path
to the directory is provided, the previous search can be restored.**_

I am using the GraphAutoModel API to define my experiments and sometimes the experiment is interrupted (for whatever reason). In the paper it is said that user can resume the search from previous saved results, however I can't find in the doc how to do so.
Can you please point me to the right way of doing this ?
Thanks
### Reproducing Steps
Not relevant

### Expected Behavior
Find method/way of resuming training in the documentation

### Setup Details
Include the details about the versions of:
 - OS type and version: Linux
 - Python: 3.6
 - autokeras: 1.0

**Comment by gaocegege** [comment]
Same question. I'd appreciate it anyone could help.

**Comment by SivamPillai** [comment]
I am using AutoModel in the new autokeras1.0.0. Have you been able to find an answer to this question? I am wondering if I use the same directory name and call AutoModel.fit() if it will resume operations.

**Comment by junkgear** [comment]
Could you please answer my question

https://stackoverflow.com/questions/59301161/explanation-needed-for-autokerass-automodel-and-graphautomodel
