### ISSUE TITLE
version 1.0.0 FunctionalAPI tutorial doesn't work

### ISSUE THREAD

**Issue by sansyo** [keras-team/autokeras#820]
!pip install git+git://github.com/keras-team/autokeras@master
!pip install kerastuner

import autokeras as ak
import numpy as np
import tensorflow as tf
from keras.datasets import mnist

# Prepare the data.
(x_train, y_classification), (x_test, y_test) = mnist.load_data()
x_image = x_train.reshape(x_train.shape + (1,))
x_test = x_test.reshape(x_test.shape + (1,))

x_structured = np.random.rand(x_train.shape[0], 100)
y_regression = np.random.rand(x_train.shape[0], 1)

# Build model and train.
inputs = ak.ImageInput(shape=(28, 28, 1))
outputs1 = ak.ResNetBlock(version='next')(inputs)
outputs2 = ak.XceptionBlock()(inputs)
image_outputs = ak.Merge()((outputs1, outputs2))

structured_inputs = ak.StructuredInput()
structured_outputs = ak.DenseBlock()(structured_inputs)
merged_outputs = ak.Merge()((image_outputs, structured_outputs))

classification_outputs = ak.ClassificationHead()(merged_outputs)
regression_outputs = ak.RegressionHead()(merged_outputs)
automodel = ak.GraphAutoModel(inputs=inputs,
                              outputs=[regression_outputs,
                                       classification_outputs])

automodel.fit((x_image, x_structured),
              (y_regression, y_classification),
              trials=100,
              epochs=200,
              callbacks=[tf.keras.callbacks.EarlyStopping(),
                         tf.keras.callbacks.LearningRateScheduler()])

Then, I got module not found error that says there are no kerastuner.engine..

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-67f87a123c31> in <module>()
----> 1 import autokeras as ak
      2 import numpy as np
      3 import tensorflow as tf
      4 from keras.datasets import mnist
      5 

2 frames
/usr/local/lib/python3.6/dist-packages/autokeras/meta_model.py in <module>()
      1 import tensorflow as tf
----> 2 from kerastuner.engine import hyperparameters as hp_module
      3 from tensorflow.python.util import nest
      4 
      5 from autokeras.hypermodel import block as block_module

ModuleNotFoundError: No module named 'kerastuner.engine'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

Is there any way to solve this?

**Comment by zhulingchen** [comment]
I guess the latest commits (after commit `e4a5dbe7e29d64c9b095d134f0ca2a5543353dda`) requires the kerastuner of version 1.0rc0 (pip install git+https://github.com/keras-team/keras-tuner.git@1.0rc0).

**Comment by chaos0625** [comment]
After I add kerastuner to autokeras, it also has error like below:
RuntimeError: Too many failed attempts to build model.
Have you met this problem and solved it?

**Comment by chaos0625** [comment]
@zhulingchen 
After I add kerastuner to autokeras, it also has error like below:
RuntimeError: Too many failed attempts to build model.
Have you met this problem and solved it?

**Comment by homerdeng** [comment]
I solved this problem by updating the tensorflow. Maybe you can try that.

**Comment by chaos0625** [comment]
@homerdeng which tensorflow version did you use?

**Comment by yfq512** [comment]
I use autokeras.StructuredDataClassifier, but I don't know how to save model. I try many methods ...,but it does' not work! Can you help me?

**Comment by manmeet3591** [comment]
> I guess the latest commits (after the commit `e4a5dbe7e29d64c9b095d134f0ca2a5543353dda`) require `kerastuner` of version 1.0rc0:
> 
> `pip install git+https://github.com/keras-team/keras-tuner.git@1.0rc0`
> 
> You may refer to this commit:
> 
> [e4a5dbe](https://github.com/keras-team/autokeras/commit/e4a5dbe7e29d64c9b095d134f0ca2a5543353dda)

This worked for me. Thanks.
