### ISSUE TITLE
[Question] Project Algorithms Milestones and its relations to Kerastuner

### ISSUE THREAD

**Issue by Uiuran** [keras-team/autokeras#828]
Hi,

You seem to be using RandomSearch and params band search (HyperBand) from kerastuner as algorithms. You are planning to deploy other popular NAS/AutoML as Reinforcement Learning and Meta-Heuristic Search (GA e.g.) ? Does keras-team plans to do all the algorithms in kerastuner or in this module ?  Do you have a road to the milestones of it until the beta ? 

NAS is a very new research topic and seems to be very exciting to build a module to easy the flow through this research ...

To note: master branch is not specifying kerastuner as dependency as-far-i-have-seem.

 thank you

**Comment by tuokri** [comment]
Commenting here as this is related to Keras Tuner not being specified as a dependency as mentioned in the OP.

Installing autokeras from source (master branch) results in the following error upon import:
```python
>>> import autokeras
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tuokri/autokeras/autokeras/__init__.py", line 1, in <module>
    from autokeras.auto_model import AutoModel
  File "/home/tuokri/autokeras/autokeras/auto_model.py", line 1, in <module>
    import kerastuner
ModuleNotFoundError: No module named 'kerastuner'
```

This is fixed by manually installing Keras Tuner:
`pip install keras-tuner`

**Comment by bhack** [comment]
I ask also for autoaugmentation  plans.
See https://github.com/keras-team/keras-tuner/issues/153

**Comment by bhack** [comment]
Something it Is landing in TPU https://arxiv.org/abs/1909.13719
https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/autoaugment.py

**Comment by jhfjhfj1** [comment]
The current dependency of kerastuner is based on rc0. You can install kerastuner with the following command.
`pip install git+https://github.com/keras-team/keras-tuner.git@1.0rc0`.
You can always check the kerastuner version we are depending on in [.travis.yml](https://github.com/keras-team/autokeras/blob/master/.travis.yml).

**Comment by Uiuran** [comment]
Adding as idea of project milestone, or something i didnt see anywhere else but seems significant for research in AutoML/NAS, and maybe is good to think in an implementation, are the Monte Carlo Tree Search models to architecture search.
