### ISSUE TITLE
Confusion matrix

### ISSUE THREAD

**Issue by taylor4712** [keras-team/autokeras#837]
I have used the following code to get the confusion matrix from my model:

`fromsklearn.metrics import confusion_matrix 
y_prediction = clf.predict(x_test)
print('The confusion matrix is: ')
print(str(confusion_matrix(y_val, y_prediction)))`

But i just prints me out the numbers of the confusion matrix, withouth any row and column name. Any suggestions?

Thanks!

**Comment by kalufinnle** [comment]
The sklearn confusion matrix function is quite straight forward. You can save the confusion matrix by assignment:
`cm = confusion_matrix(ytest,yprediction)` 
Then you add add column/row  name or whatever modification you want to the variable `cm`; then
`print(str(cm))` 
Please refer to https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html
