### ISSUE TITLE
Loading Best model and understanding trial outcomes with AutoModel

### ISSUE THREAD

**Issue by SivamPillai** [keras-team/autokeras#843]
I am trying to load the best model after completing training with AutoModel.fit(). However, I am not able to follow any relevant documentation to understand how this is done.

### Setup Details
Include the details about the versions of:
 - OS type and version: Ubuntu 18.04
 - Python: 3.6.8
 - autokeras: 1.0.0a0
 - scikit-learn: 0.20.2
 - numpy: 1.16.1
 - keras: 2.2.4
 - scipy: 1.2.0
 - tensorflow:
 - pytorch:

### Additional context

I tried digging into the code base to try things like:

`automodel.tuner.get_best_model()`
`automodel.tuner.best_hp`
`automodel.evaluate(x_test)`

it either complains about nonetype object or invalid call

I tried loading using the following:
`automodel.tuner.oracle.get_trial('<trial_id from filename>')`

However, I am unsure how to proceed from here if I would like to load it as a normal Keras model and do my predictions. I can loop in the directory to find the best_model but is there a better way to do the same?

Any help or directions is much appreciated!

Thanks.

**Comment by SivamPillai** [comment]
Any updates or suggestions here please?

**Comment by zhulingchen** [comment]
I am using the latest version based on the most recent commit and I can do something like:

```
_, model = automodel.get_best_model()
model.save(file_path)
```

It worked well for me

**Comment by junkgear** [comment]
Can someone please answer this question

https://stackoverflow.com/questions/59301161/explanation-needed-for-autokerass-automodel-and-graphautomodel
