### ISSUE TITLE
can't install autokeras

### ISSUE THREAD

**Issue by Kantshun** [keras-team/autokeras#844]
### Bug Description

i can't install autokeras, it kept readtime out while installing
### Reproducing Steps
1. i downloaded the code on github, autokeras-master.zip
2. i created a virtual environment to install autokeras
3.it just readtime out for some reason

### Setup Details
Include the details about the versions of:
 - OS type and version: window10 Pro
 - Python: 3.6.6
 - autokeras: master
 - scikit-learn:none
 - numpy:none
 - keras:none
 - scipy:none
 - tensorflow:none
 - pytorch:none

### Additional context

![image](https://user-images.githubusercontent.com/31396222/69644736-ff762a00-109f-11ea-8b93-1a22fdb569e1.png)
![image](https://user-images.githubusercontent.com/31396222/69644777-0ef57300-10a0-11ea-8700-50efbaf6b97f.png)
![image](https://user-images.githubusercontent.com/31396222/69644827-22084300-10a0-11ea-948f-4ffebf9204f5.png)
![image](https://user-images.githubusercontent.com/31396222/69644861-33e9e600-10a0-11ea-84ca-061a3f1dd069.png)
![image](https://user-images.githubusercontent.com/31396222/69644930-4c5a0080-10a0-11ea-9c96-9dc9b218c12c.png)

**Comment by PhilipMachineLearning** [comment]
Same problem here

**Comment by gabrieldemarmiesse** [comment]
You seem to have an internet connection problem when downloading panda. It seems unrelated to autokeras.

**Comment by kalufinnle** [comment]
@Kantshun   
install keras package first. Then install scikit-learn
numpy
scipy:
tensorflow (use <=1.8)
pytorch

Then install autokeras
Let me know if you still encounter any more installation problems

**Comment by Kantshun** [comment]
@gabrieldemarmiesse you are right, internet problem. I can install autokeras now, but its documentation is too brief, i don't quite understand how to use autokeras.

**Comment by haifeng-jin** [comment]
@Kantshun It is definitely an important issue. We will include an installation tutorial on the website later. Thanks.
