### ISSUE TITLE
installation issue o

### ISSUE THREAD

**Issue by pdavis39** [keras-team/autokeras#846]
**My environment is a Jetson Xavier** 
Jetpack 4.2 
Ubuntu 18.04
python version is 3.6.8
relevant pip.list
dask (2.8.0)
dask-glm (0.2.0)
dask-ml (1.1.1)
Keras (2.3.1)
Keras-Applications (1.0.8)
Keras-Preprocessing (1.1.0)
numba (0.46.0)
numpy (1.17.4)
packaging (19.2)
pandas (0.25.3)
pandas-flavor (0.2.0)
pip (19.3.1)
scikit-learn (0.21.3)
scikit-MDR (0.4.4)
scipy (1.3.2)
tensorboard (1.14.0)
tensorflow-estimator (1.14.0)
**tensorflow-gpu (1.14.0+nv19.10)**

**error messages**
pip install git+git://github.com/keras-team/autokeras@master#egg=autokeras
Collecting autokeras
Cloning git://github.com/keras-team/autokeras (to revision master) to /tmp/pip-install-du3y560o/autokeras
Running command git clone -q git://github.com/keras-team/autokeras /tmp/pip-install-du3y560o/autokeras
ERROR: Could not find a version that satisfies the requirement tensorflow (from autokeras) (from versions: none)
ERROR: No matching distribution found for tensorflow (from autokeras)
**Then I tried**
pip install autokeras
Collecting autokeras
  Downloading https://files.pythonhosted.org/packages/c2/32/de74bf6afd09925980340355a05aa6a19e7378ed91dac09e76a487bd136d/autokeras-0.4.0.tar.gz (67kB)
     |████████████████████████████████| 71kB 3.8MB/s 
Collecting scipy==1.2.0
  Downloading https://files.pythonhosted.org/packages/ea/c8/c296904f2c852c5c129962e6ca4ba467116b08cd5b54b7180b2e77fe06b2/scipy-1.2.0.tar.gz (23.3MB)
     |████████████████████████████████| 23.3MB 12.6MB/s 
ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.1 (from autokeras) (from versions: none)
**ERROR: No matching distribution found for tensorflow==1.13.1 (from autokeras)**

I have tried downgrading to tensorflow-gpu==1.13.1, but get the same error message
ERROR: No matching distribution found for tensorflow==1.13.1 (from autokeras)

My hunch is autokeras does not include tensorflow-gpu, thoughts on how to fix this?

thanks in advance for your assistance

**Comment by PhilipMachineLearning** [comment]
Same issue here

**Comment by gabrieldemarmiesse** [comment]
A quick fix is to install it without the dependencies. `pip install --no-deps git+git://github.com/keras-team/autokeras`. 

The long term fix is to remove tensorflow from the setup.py, otherwise it's going to try to install the cpu version of tensorflow everytime. I would consider that a bug. 

See https://github.com/keras-team/keras-tuner/issues/168 which has the same problem.

**Comment by pdavis39** [comment]
Thanks for the follow up.  I followed your suggestion, but I end up with another issue

import autocross

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-43b9b5252b3c> in <module>
----> 1 import autokeras

/media/bison/xavierssd500/sandbox/my-project-env/lib/python3.6/site-packages/autokeras/__init__.py in <module>
----> 1 from autokeras.auto_model import AutoModel
      2 from autokeras.const import Constant
      3 from autokeras.hypermodel.base import Block
      4 from autokeras.hypermodel.base import Head
      5 from autokeras.hypermodel.base import HyperBlock

/media/bison/xavierssd500/sandbox/my-project-env/lib/python3.6/site-packages/autokeras/auto_model.py in <module>
----> 1 import kerastuner
      2 import tensorflow as tf
      3 from tensorflow.python.util import nest
      4 
      5 from autokeras import meta_model

ModuleNotFoundError: No module named 'kerastuner'

when I try pip install keras-tuner

ERROR: Could not find a version that satisfies the requirement tensorflow>=2.0.0-beta1 (from keras-tuner) (from versions: none)
ERROR: No matching distribution found for tensorflow>=2.0.0-beta1 (from keras-tuner)

thanks and happy holidays

**Comment by gabrieldemarmiesse** [comment]
You could install everything manually, even tensorflow with --no-deps but this is a workaround and the issue will be fixed in the future. I already opened a PR for that. 

Happy Christmas to you too!
