### ISSUE TITLE
AutoKeras 1.0 still much slower than 0.4 on Google Colab

### ISSUE THREAD

**Issue by pezdorado** [keras-team/autokeras#847]
I reported this problem before as issue #834. This issue was closed 3 days ago, however I just tested it and the problem doesn't seem to be solved. Because I cannot reopen my old issue I open a new one. To reproduce the problem see the code in #834.

As a side note: doesn't Github send notifications when an issue is closed to the originator of the issue?

**Comment by jhfjhfj1** [comment]
@pezdorado I think the problem is because of the data augmentation. We will try to improve it. Thank you! I reopened the issue #834.
