### ISSUE TITLE
No load_image_dataset function in autokeras 1.0

### ISSUE THREAD

**Issue by taylor4712** [keras-team/autokeras#862]
When I try to use 

from autokeras.image_supervised import ImageClassifier, load_image_dataset
or 
from autokeras.image.image_supervised import load_image_dataset

I get the following error:
ModuleNotFoundError: No module named 'autokeras.image_supervised'

I tried to upload my own dataset to Autokeras 1.0
In Autokeras 0.4 it works fine, in Autokeras 1.0 not.

Thank you for your help

**Comment by sustef94** [comment]
Same problem for me. Also could not find it in a different place

**Comment by haifeng-jin** [comment]
@taylor4712 @sustef94 The API of AutoKeras 1.0 and 0.4 are different. Would you paste your code for reproducing the error? We currently don't have the load_image_dataset function.
