### ISSUE TITLE
 Invalid argument: batch_size must be a scalar

### ISSUE THREAD

**Issue by darkknight9394** [keras-team/autokeras#863]
Just tried running my first mock example and have encountered errors in both 0.4 and 1.1.0 during prediction time where the batch_size is supposed to be a scalar. Can anyone help?

C:\ProgramData\Anaconda3\envs\AutoKeras_test\python.exe C:/Users/User/PycharmProjects/AutoKeras_test/test_automl.py
Using TensorFlow backend.
2.0.0
<module 'autokeras' from 'C:\\Users\\User\\AppData\\Roaming\\Python\\Python37\\site-packages\\autokeras-1.0.0a0-py3.7.egg\\autokeras\\__init__.py'>

Log:
2019-12-22 16:46:31.984048: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at batch_dataset_op.cc:294 : Invalid argument: batch_size must be a scalar
Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/AutoKeras_test/test_automl.py", line 25, in <module>
    y = clf.predict(x_test, y_test)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\autokeras-1.0.0a0-py3.7.egg\autokeras\auto_model.py", line 278, in predict
  File "C:\ProgramData\Anaconda3\envs\AutoKeras_test\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 1038, in batch
    return BatchDataset(self, batch_size, drop_remainder)
  File "C:\ProgramData\Anaconda3\envs\AutoKeras_test\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 3168, in __init__
    **self._flat_structure)
  File "C:\ProgramData\Anaconda3\envs\AutoKeras_test\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py", line 607, in batch_dataset_v2
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: batch_size must be a scalar [Op:BatchDatasetV2]
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.learning_rate
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/alpha/guide/checkpoints#loading_mechanics for details.
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.iter
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.beta_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.decay
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer.learning_rate
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/alpha/guide/checkpoints#loading_mechanics for details.

Process finished with exit code 1

**Comment by darkknight9394** [comment]
import tensorflow as tf

import autokeras as ak
from keras.datasets import mnist
import numpy as numpy
print(tf.__version__)
print(ak)
#tf.executing_eagerly(True)

print(tf.executing_eagerly())


# Prepare the data.
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(x_train.shape + (1,))
x_test = x_test.reshape(x_test.shape + (1,))

# Search and train the classifier.
x_train =x_train[0:5]

x_test =x_test[0:5]
clf = ak.ImageClassifier(max_trials=2)
clf.fit(x_train, y_train,validation_split=0.9,epochs=2)
print("going to predict now")
y = clf.predict(x_test, y_test)

**Comment by abhinit** [comment]
@darkknight9394 can you exactly provide the code you are trying to execute?

**Comment by brzegorz** [comment]
Hi, I also experience that issue with darknight's code, and also with my own with StructuredDataClassifier
