### ISSUE TITLE
AutoKeras for Time-series classification

### ISSUE THREAD

**Issue by andreaAnc** [keras-team/autokeras#866]
Dear everyone, 

Do you know if AutoKeras can be used for (multi-label) classification of time-series?

Thank you,

Andrea

**Comment by alexcombessie** [comment]
Hi,

Haven't tried, but at a quick glance, sounds like RNNBlock + multiple ClassificationHeads would fit your requirements.

Hope it helps,

Alex

**Comment by andreaAnc** [comment]
RNN block works for 1D data? 

Thanks!

**Comment by haifeng-jin** [comment]
We are still working on this module. You can see the interface in autokeras/task.py

**Comment by andreaAnc** [comment]
Thank you for your reply.

Just to be clear, right now is it possible to use 1D data (such as time-series) with autokeras? if yes, which module supports 1D data?

**Comment by haifeng-jin** [comment]
@andreaAnc To use the RNN block you have to reshape it to 2D per instance.
