### ISSUE TITLE
How to split Dataset into test, train and validationset Autokeras 0.4

### ISSUE THREAD

**Issue by taylor4712** [keras-team/autokeras#870]
Hello, 

I am using autokeras 0.4 (because 1.0 does not work in my notebook) and I try to split my dataset into test,train and validation set. I tried: 

`labels = '/content/mypath.csv'
train_path='/content/mypath/'

x, y = load_image_dataset(csv_file_path=labels,
                          images_path=train_path)
x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(x, y, test_size = 0.1)`

But I get the error 

"ValueError: /content/mypath/TRAIN image does not exist"

I tried to create another folder TRAIN and put all the pictures in there, but i does not work either. Any suggestions?

**Comment by haifeng-jin** [comment]
@taylor4712 We have the new 1.0.0 beta version released. You can install it with `pip3 install autokeras==1.0.0b0`.
You can follow this tutorial on splitting the data. https://autokeras.com/tutorial/image_classification/#validation-data
Let us know if it works or not.

Thank you!
