### ISSUE TITLE
TypeError: 'Node' object is not callable

### ISSUE THREAD

**Issue by bb-1357** [keras-team/autokeras#876]
Hi!
When I run codes suppoted on the website(https://autokeras.com/) in  jupyter notebook,
                 clf.fit(x_train, y_train,validation_split=0.12)     got an eror ,then
               -->        self._meta_build(dataset)         
               -->        in _meta_build(self, dataset) outputs=self.outputs, dataset=dataset,seed=self.seed**)
              --->       outputs = nest.flatten([output_blocks(output_node) for output_blocks in outputs]) 
Final display ” for output_blocks in outputs“went wrong,I can’t find the cause of the problem, and I don’t know how to modify the nodes in the network   
Hope someone has met and solved this issue, thanks

**Comment by bb-1357** [comment]
Another tricky problem:TypeError: _build_wrapper() got an unexpected keyword argument 'inputs'

**Comment by zhulingchen** [comment]
> 
> 
> Another tricky problem:TypeError: _build_wrapper() got an unexpected keyword argument 'inputs'

For this problem, please update your `keras-tuner` package to version 1.0.0

**Comment by bb-1357** [comment]
The version I installed is exactly 1.0.0，I‘m sad that the problem still cannot be solved

**Comment by haifeng-jin** [comment]
@bb-1357 Is it autokeras==1.0.0b0 that you use? Please paste the entire notebook scripts, so that we can reproduce the error. thanks

**Comment by bb-1357** [comment]
No, autokeras == 1.0.0a0. My operating environment is tensorflow==2.0.0,torch=1.3.1，and all codes coming from official website,I didn't make any changes
```
`from autokeras import ImageClassifier
from tensorflow.keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
import autokeras as ak
# Initialize the image classifier.
clf = ak.ImageClassifier(max_trials=10) # It tries 10 different models.
split = 50000
x_val = x_train[split:]
y_val = y_train[split:]   
x_train = x_train[:split]  
y_train = y_train[:split]
clf.fit(
    x=x_train, y=y_train, validation_split=0.2
)`
```
**The compiler reported an error**
```
“meta_model.py in <listcomp>(.0)
     53 
     54     outputs = nest.flatten([output_blocks(output_node)
---> 55                             for output_blocks in outputs])
     56     hm = graph.HyperGraph(inputs, outputs, override_hps=hps)
     57     return hm
TypeError: 'Node' object is not callable
```
**if I change "clt.fit"function into**
```
clf.fit(
 x=x_train, y=y_train, epochs=2000, callbacks=None, validation_split=0.2, validation_data=None
)
```
**The compiler reported an error** 
```
meta_model.py in <listcomp>(.0)
     53 
     54     outputs = nest.flatten([output_blocks(output_node)
---> 55                             for output_blocks in outputs])
     56     hm = graph.HyperGraph(inputs, outputs, override_hps=hps)
     57     return hm
 `TypeError: _build_wrapper() got an unexpected keyword argument 'inputs`' 
```
thanks a lot.

**Comment by zhulingchen** [comment]
> 
> 
> The version I installed is exactly 1.0.0，I‘m sad that the problem still cannot be solved

Then try the latest commit of `keras-tuner` from its source codes:

```
git clone https://github.com/keras-team/keras-tuner.git
cd keras-tuner
pip install .
```

**Comment by haifeng-jin** [comment]
@zhulingchen Thanks for the suggestion. Currently, AutoKeras is based on the 1.0.0 version of KerasTuner. If you install the master branch of KerasTuner, I am not sure it would work well since we haven't tested it yet.

@bb-1357
I suggest you install the latest version of AutoKeras with `pip3 install autokeras==1.0.0b0`.
I saw this bug once, I remembered I have fixed it before the b0 release.
Thanks.

**Comment by bb-1357** [comment]
Thank you very much for helping me @haifeng-jin @zhulingchen 
If it ’s just a simple upgrade with latest version autokeras==1.0.0b0 , the same file  still reports an error.
Install  keras-tuner from  source (instead of 'pip install keras-tuner' ) can really solve the problem.
Hope my mistake can help more people who are learning about AutoKeras.
