### ISSUE TITLE
Add get_params methods in the task-oriented classes

### ISSUE THREAD

**Issue by alexcombessie** [keras-team/autokeras#886]
This would enable compatibility with other ML libraries such as scikit-learn and xgboost

**Comment by alexcombessie** [comment]
Hi, 

I am still interested, get_params is an important method which would close the gap with the sklearn API.

**Comment by alexcombessie** [comment]
still interested in this feature!

**Comment by alexcombessie** [comment]
Still interested, as I need this feature for integration into Dataiku DSS.

**Comment by haifeng-jin** [comment]
We still haven't got the chance to work on this feature yet. We are likely to have a `get_config()` which follows the Keras APIs.
