### ISSUE TITLE
Roc curve, other metr

### ISSUE THREAD

**Issue by taylor4712** [keras-team/autokeras#891]
Hey, does anyone tried to plot a ROC curve for autokeras? I tried sklearn.metrics.roc_curve  but it did not work because the size of array is wrong. Maybe someone has an example.

Thank you very much

**Comment by haifeng-jin** [comment]
@taylor4712 How are you passing the roc_curve to AutoKeras?
I am not sure whether we are supporting this feature or not.
Would you please paste the code which produces the error?

Thanks.

**Comment by taylor4712** [comment]
clf = ImageClassifier(verbose = True)
from sklearn.metrics import roc_curve,roc_auc_score
y_test_cat_prob=clf.predict(x_test)
fpr , tpr , thresholds = roc_curve( y_test , y_test_cat_prob)


i used sklearn. I have a multiclass classification, it does not support multiclass format

**Comment by haifeng-jin** [comment]
@taylor4712 You can use the current master branch to export your model using `export_model()` of ImageClassifier. Then, you can use the exported Keras model to output the probs.
