### ISSUE TITLE
Save AutoKeras Model

### ISSUE THREAD

**Issue by Kyrill996** [keras-team/autokeras#912]
Hi,

Once i want to save my AutoKeras Model with the export_model() Function:
```python
ak_classification = ak.StructuredDataClassifier( name="autokeras_model", directory="models", max_trials=2, seed=42)
ak_classification.fit(X_train, y_train, epochs=5, validation_split=0.2)
```

I get following Error:
```python
AttributeError: 'StructuredDataClassifier' object has no attribute 'export_model'
```

Would be happy if somebody could provide me with some help!

**Comment by haifeng-jin** [comment]
@Kyrill996 Would you please confirm your AutoKeras version?
The export model function only exists in the latest version. 1.0.0

**Comment by Kyrill996** [comment]
Sorry for that missing information. That is exactly the version that i am using.

**Comment by haifeng-jin** [comment]
@Kyrill996 We don't have this error.
`Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 19:50:54) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import autokeras as ak
>>> ak.StructuredDataClassifier.export_model
<function AutoModel.export_model at 0x13d6da598>
>>> `

You may try `python3 -m pip install --upgrade autokeras` if you are using python3 as your command for executing the python file.

We are currently not supporting export the structured data classifier unless the final found model is a neural network.
So even you can use that function it might not work as expected for now.
I will add this to the export model tutorial later.
