### ISSUE TITLE
time_limit and metric arguments are no longer available?

### ISSUE THREAD

**Issue by iXanthos** [keras-team/autokeras#920]
Greetings to everyone,

As a part of an evaluation I wanted to try autokeras on multiple different datasets. My data are tabular, so I use `StructuredDataClassifier` and `StructuredDataRegressor`. The problem is that I cannot set a custom evaluation metric, nor set the time_limit of the model.fit function. In the examples I found online, everyone is setting their desired time_limit, but when I try to run a fit function with this parameter, it outputs the error: `Unrecognized` keyword arguments: `{'time_limit': 360}`. Is this functionality removed from the newest version of autokeras? Also, about the metric, I want to use AUC, as the performance metric, but neither the `metric` variable is recognized.

autokeras 1.0
python 3.6.9
OS Ubuntu 18.04

**Comment by haifeng-jin** [comment]
@iXanthos For time_limit, we changed it. We now use max_trials to control the search. It is an argument in the initializer of the classes.
`metrics` is also in the initializer. It has the same usage as the Keras metrics in the compile function.

**Comment by iXanthos** [comment]
@haifeng-jin so is there a way to set a strict time limit? If not, this is a step backwards in my opinion, as it makes autokeras unavailable for quantitative performance evaluation under strict time restrictions (99% of all the published works evaluate a tool or library under some time constraints).
Also, when you talk about the initializer, you mean the `StructuredDataClassifier` call, correct?

Thank you in advance.

**Comment by haifeng-jin** [comment]
@iXanthos Yes, that is correct. The `StructuredDataClassifier` call.

We will do some performance evaluation later for the new version.
It is hard to do a strict time limit, so, for now, we will not focus on this feature.

**Comment by dahlo** [comment]
@haifeng-jin do you have any suggestion on how to limit the time any other way, or a way to save the state of the program every n iterations/time units?

I run my code on a HPC center where i have to book my jobs with a time limit, and jobs are terminated when the timer runs out. It would be a shame if i can't save my model before that happens.

**Comment by haifeng-jin** [comment]
Currently, the is no way to limit the time. However, all the intermediate results and models are saved on disk. You may try to see what's in the folder. Those kids and models are generated by KerasTuner. Thanks.

**Comment by psaks** [comment]
@haifeng-jin 

> @iXanthos Yes, that is correct. The `StructuredDataClassifier` call.
> 
> We will do some performance evaluation later for the new version.
> It is hard to do a strict time limit, so, for now, we will not focus on this feature.

I also find it unfortunate that the time_limit functionality has disappeared. 

Are you saying that the previous time_limit didn't work properly? otherwise, can you elaborate why it is hard to have a strict time limit? 

Is it possible to implement callbacks on the level of trials? Basically, if we can set the trial status to STOPPED in-between trials, then it is possible to do something sensible. Alternatively, is it possible to do one trial at a time? 

Cheers.
