### ISSUE TITLE
3D image classification in auto-keras

### ISSUE THREAD

**Issue by LAX1992** [keras-team/autokeras#927]
The description in ImageClassifier.fit says that the data shape should be 3 or 4 dimensional.So auto-keras 1.0 does not accept 3d image as input, am I right ?But when I google "auto-keras 3d image", it seems like it used to have ImageClassifier3D before. Have you considered put the function back?

**Comment by haifeng-jin** [comment]
@LAX1992 Currently, the ConvBlock does support the 3d images. The ResNetBlock and XceptionBlock does not. You can use AutoModel with ConvBlock to do it. The ResNet and XceptionNet are extending code from KerasTuner. You may submit a issue there to ask if the will support 3d. Thank you.

**Comment by LAX1992** [comment]
I will try it, thank you!!
