### ISSUE TITLE
AttributeError: 'Merge' object has no attribute 'fit_transform'

### ISSUE THREAD

**Issue by vincentluo91** [keras-team/autokeras#931]
Hi everyone,

I got a problem when running the example from autokeras website. It returns "AttributeError: 'Merge' object has no attribute 'fit_transform'". It reports the same error when I do not use Merge(), say only use ConvBlock (output_node1). Any help would be appreciated.

Here is the code:
import autokeras as ak
from tensorflow.keras.datasets import mnist
input_node = ak.ImageInput()
output_node = ak.Normalization()(input_node)
output_node = ak.ImageAugmentation()(output_node)
output_node1 = ak.ConvBlock()(output_node)
output_node2 = ak.ResNetBlock(version='v2')(output_node)
output_node = ak.Merge()([output_node1, output_node2])

auto_model = ak.AutoModel(
    inputs=input_node, 
    outputs=output_node,
    max_trials=10)

(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape) # (60000, 28, 28)
print(y_train.shape) # (60000,)
print(y_train[:3]) # array([7, 2, 1], dtype=uint8)

\# Feed the AutoModel with training data.
auto_model.fit(x_train, y_train)
\# Predict with the best model.
predicted_y = auto_model.predict(x_test)
\# Evaluate the best model with testing data.
print(auto_model.evaluate(x_test, y_test))

The version information and I use GPU:
python --version  Python 3.6.9 .
tf.__version__ '2.1.0'
tf.keras.__version__ '2.2.4-tf'
autokeras-1.0.0.

# Here are all error messages:
AttributeError                            Traceback (most recent call last)
<ipython-input-9-0fc492058b0a> in <module>
     21 
     22 # Feed the AutoModel with training data.
---> 23 auto_model.fit(x_train, y_train)
     24 # Predict with the best model.
     25 predicted_y = auto_model.predict(x_test)

~/software/miniconda3/envs/gpu/lib/python3.6/site-packages/autokeras/auto_model.py in fit(self, x, y, epochs, callbacks, validation_split, validation_data, **kwargs)
    185             y=y,
    186             validation_data=validation_data,
--> 187             validation_split=validation_split)
    188 
    189         # Initialize the hyper_graph.

~/software/miniconda3/envs/gpu/lib/python3.6/site-packages/autokeras/auto_model.py in _prepare_data(self, x, y, validation_data, validation_split)
    260         # TODO: Handle other types of input, zip dataset, tensor, dict.
    261         # Prepare the dataset.
--> 262         dataset = self._process_xy(x, y, fit=True)
    263         if validation_data:
    264             self._split_dataset = False

~/software/miniconda3/envs/gpu/lib/python3.6/site-packages/autokeras/auto_model.py in _process_xy(self, x, y, fit, predict)
    244             for data, head_block in zip(y, self.heads):
    245                 if fit:
--> 246                     data = head_block.fit_transform(data)
    247                 else:
    248                     data = head_block.transform(data)

AttributeError: 'Merge' object has no attribute 'fit_transform'

**Comment by haifeng-jin** [comment]
@vincentluo91 Thank you for the report. We miss a line in the example.
`output_node = ak.ClassificationHead()(output_node)`.
If anyone like, please help us correct it here:
https://github.com/keras-team/autokeras/blob/master/docs/templates/tutorial/customized.md

**Comment by vincentluo91** [comment]
It works. Thanks.
