### ISSUE TITLE
ImageClassifier no longer has final_fit (AttributeError: 'ImageClassifier' object has no attribute 'final_fit')

### ISSUE THREAD

**Issue by seanreynoldscs** [keras-team/autokeras#945]
### Bug Description
---------------------------------------------------------------------------
AttributeError: 'ImageClassifier' object has no attribute 'final_fit'
---------------------------------------------------------------------------

I see examples such as: 
clf = ImageClassifier(verbose=True)
clf.fit(x_train, y_train, time_limit=12 * 60 * 60)
clf.final_fit(x_train, y_train, x_test, y_test, retrain=True)
y = clf.evaluate(x_test, y_test)
print(y)
But when I run something similar I get the error: 
AttributeError                            Traceback (most recent call last)
<ipython-input-8-4e011cd6ccac> in <module>
----> 1 clf.final_fit(trainX, trainY, testX, testY, retrain=True)
      2 keras_model = clf.export_model()

AttributeError: 'ImageClassifier' object has no attribute 'final_fit'

As suggested here: https://github.com/keras-team/autokeras/issues/186 
I have tried adding the activation function and retraining on the data... but to do so I still end up choosing many hyper parameters such as LR and optimizer...
I thought that was sorta the point of Auto ML?

What am I missing?

**Comment by seanreynoldscs** [comment]
Is there a more stable version I should be using? I'm very new to this, I've only been using Sage Maker and Google Cloud AutoML.

**Comment by Mosely** [comment]
Hi, it's my understanding that final_fit() has been removed and its functionality is now included in fit().  I think you can remove that final_fit() line and it should be okay.

**Comment by seanreynoldscs** [comment]
During training I see the results include a couple trials with very good results such as: 
10/10 [==============================] - ETA: 0s - loss: 0.0979 - accuracy: 0.96 - 0s 6ms/step - loss: 0.0501 - accuracy: 0.9869 - val_loss: 0.0636 - val_accuracy: 0.9868

However the last evaluated result is: Epoch 449/1000
13/13 [==============================] - ETA: 0s - loss: 0.6730 - accuracy: 0.62 - ETA: 0s - loss: 0.6965 - accuracy: 0.50 - 0s 11ms/step - loss: 0.6882 - accuracy: 0.5407 - val_loss: 0.6688 - val_accuracy: 0.6184

After calling the fit function when I evaluate the model I get the results that are much closer to the poor results at the end, and dont represent the best results during training: 
print(clf.evaluate(testX, testY))
shows:
4/4 [==============================] - ETA: 0s - loss: 0.7171 - accuracy: 0.40 - 0s 25ms/step - loss: 0.6935 - accuracy: 0.5234
[0.6934990286827087, 0.5234375]

Which seems really crappy considering there was very good convergence during training.
As an aside, the data I'm classifying converges very easy with a simple LeNet or MobileNet design. It's not MNIST, but it is a softball I was tossing AUTOKERAS so that I could evaluate the tool.

**Comment by seanreynoldscs** [comment]
Also when I try to use this model by calling: 
keras_model = clf.export_model()
and 
keras_model.save(modelLocation)

When I try to import this model using:
exposureModel = load_model(exposureModelPath)

I get this error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-c1d97e7cc4ac> in <module>
     13 # load the trained convolutional neural network
     14 print("[INFO] Exposure network...")
---> 15 exposureModel = load_model(exposureModelPath)

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\saving\save.py in load_model(filepath, custom_objects, compile)
    144   if (h5py is not None and (
    145       isinstance(filepath, h5py.File) or h5py.is_hdf5(filepath))):
--> 146     return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
    147 
    148   if isinstance(filepath, six.string_types):

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py in load_model_from_hdf5(filepath, custom_objects, compile)
    166     model_config = json.loads(model_config.decode('utf-8'))
    167     model = model_config_lib.model_from_config(model_config,
--> 168                                                custom_objects=custom_objects)
    169 
    170     # set weights

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\saving\model_config.py in model_from_config(config, custom_objects)
     53                     '`Sequential.from_config(config)`?')
     54   from tensorflow.python.keras.layers import deserialize  # pylint: disable=g-import-not-at-top
---> 55   return deserialize(config, custom_objects=custom_objects)
     56 
     57 

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\layers\serialization.py in deserialize(config, custom_objects)
    104       module_objects=globs,
    105       custom_objects=custom_objects,
--> 106       printable_module_name='layer')

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    301             custom_objects=dict(
    302                 list(_GLOBAL_CUSTOM_OBJECTS.items()) +
--> 303                 list(custom_objects.items())))
    304       with CustomObjectScope(custom_objects):
    305         return cls.from_config(cls_config)

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\network.py in from_config(cls, config, custom_objects)
    935     """
    936     input_tensors, output_tensors, created_layers = reconstruct_from_config(
--> 937         config, custom_objects)
    938     model = cls(inputs=input_tensors, outputs=output_tensors,
    939                 name=config.get('name'))

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\network.py in reconstruct_from_config(config, custom_objects, created_layers)
   1891   # First, we create all layers and enqueue nodes to be processed
   1892   for layer_data in config['layers']:
-> 1893     process_layer(layer_data)
   1894   # Then we process nodes in order of layer depth.
   1895   # Nodes that cannot yet be processed (if the inbound node

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\network.py in process_layer(layer_data)
   1873       from tensorflow.python.keras.layers import deserialize as deserialize_layer  # pylint: disable=g-import-not-at-top
   1874 
-> 1875       layer = deserialize_layer(layer_data, custom_objects=custom_objects)
   1876       created_layers[layer_name] = layer
   1877 

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\layers\serialization.py in deserialize(config, custom_objects)
    104       module_objects=globs,
    105       custom_objects=custom_objects,
--> 106       printable_module_name='layer')

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    290     config = identifier
    291     (cls, cls_config) = class_and_config_for_serialized_keras_object(
--> 292         config, module_objects, custom_objects, printable_module_name)
    293 
    294     if hasattr(cls, 'from_config'):

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py in class_and_config_for_serialized_keras_object(config, module_objects, custom_objects, printable_module_name)
    248     cls = module_objects.get(class_name)
    249     if cls is None:
--> 250       raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
    251 
    252   cls_config = config['config']

ValueError: Unknown layer: Normalization

**Comment by seanreynoldscs** [comment]
Okay this worked for keeping the model trained:
input_node = ak.ImageInput()
output_node = ak.ClassificationHead()
clf = ak.AutoModel(inputs=input_node, outputs=output_node, max_trials=10)

I'm still having trouble loading the model with keras, now I'm getting: 
ValueError: Unknown layer: Sigmoid

I noticed that the last two layers of my trained network are: 
dense (Dense)                (None, 1)                 33        
_________________________________________________________________
classification_head_1 (Sigmo (None, 1)                 0      

I thought it was a little odd that they are both size (None, 1)

**Comment by haifeng-jin** [comment]
@seanreyboldscs 
You will need the following line.
```python
load_model (custom_objects=ak. CUSTOM_OBJECTS)
```
Thanks.

Anyone would like to update it in the documentation to include the load model tutorial in
/docs/templates/tutorial/export.md

?

**Comment by seanreynoldscs** [comment]
Thank you so much, that worked.
So in summary to get everything working for me we did the following:

```
input_node = ak.ImageInput()
output_node = ak.ClassificationHead()
clf = ak.AutoModel(inputs=input_node, outputs=output_node, max_trials=10)
```
to export:
```
model = clf.export_model()
model.save(modelLocation)
```

and when loading: 
`exposureModel = load_model(exposureModelPath, custom_objects=ak. CUSTOM_OBJECTS)
`
