### ISSUE TITLE
StructuredDataRegressor malfunctioning

### ISSUE THREAD

**Issue by maxmarketit** [keras-team/autokeras#959]
Thank you for the great package. I firmly believe autokeras can free many data scientists of

  training models endlessly. But,

  I tried several examples,

  StructuredDataRegressor trains fine, but can't evaluate, predict, nor save the model.

  evaluate and predict takes so long... (StructuredDataClassifier worked okay for evaluate, at least)
  
  I wonder if there is any way I can use predict, and save for StructuredDataRegressor.

**Comment by haifeng-jin** [comment]
@maxmarketit Would you please paste your code to reproduce the error? Thanks

**Comment by maxmarketit** [comment]
I have been trying this in colab...

    %tensorflow_version 2.x  
    import autokeras as ak

    from keras.datasets import boston_housing
    (x_train, y_train), (x_test, y_test) = boston_housing.load_data()

    reg = ak.StructuredDataRegressor(max_trials=3, directory='./boston', seed=10)
    reg.fit(x_train, y_train, epochs=10)

    model = reg.export_model()
    model.predict(x_test)

model.predict takes forever!!!

**Comment by haifeng-jin** [comment]
@maxmarketit This might because of a big issue. I will try it. Thanks.

**Comment by gautambak** [comment]
I am also having this issue. Is there an alternative way to view and save the best model?

**Comment by nithints** [comment]
This is still not working can someone confirm this issue still exists

**Comment by haifeng-jin** [comment]
https://autokeras.com/tutorial/structured_data_regression/
I believe it is solved. You can try this tutorial.

**Comment by maxmarketit** [comment]
I am afraid it does not work still.

The tutorial works fine in my colab,
but the code above still produces errors.

So I change the code to save data into a csv file and do the same thing as the tutorial,
but still `reg.predict()` produces an error(the below)

```
WARNING:tensorflow:Model was constructed with shape (None, 12) for input Tensor("input_1:0", shape=(None, 12), dtype=string), but it was called on an input with incompatible shape (None, 9).
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-35-f2177c0055ff> in <module>()
      1 # Predict with the best model.
----> 2 predicted_y = reg.predict(test_file_path)

12 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    966           except Exception as e:  # pylint:disable=broad-except
    967             if hasattr(e, "ag_error_metadata"):
--> 968               raise e.ag_error_metadata.to_exception(e)
    969             else:
    970               raise

ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1147 predict_function  *
        outputs = self.distribute_strategy.run(
    /usr/local/lib/python3.6/dist-packages/autokeras/keras_layers.py:48 call  *
        split_inputs = tf.split(input_nodes, [1] * len(self.encoding), axis=-1)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py:1962 split  **
        value=value, size_splits=size_splits, axis=axis, num_split=num, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py:9789 split_v
        num_split=num_split, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:744 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py:595 _create_op_internal
        compute_device)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:3327 _create_op_internal
        op_def=op_def)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:1817 __init__
        control_input_ops, op_def)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:1657 _create_c_op
        raise ValueError(str(e))

    ValueError: can't split axis of size 9 into pieces of size [1,1,1,1,1,1,1,1,1,1,1,1] for '{{node model/multi_column_categorical_encoding/split}} = Spl
```

**Comment by ciessielski** [comment]
I have the same error as @maxmarketit. @haifeng-jin do you have any idea why it happens? Might it be connected with tensorflow version?

**Comment by haifeng-jin** [comment]
```python
import autokeras as ak
import numpy as np

from keras.datasets import boston_housing
(x_train, y_train), (x_test, y_test) = boston_housing.load_data()

reg = ak.StructuredDataRegressor(max_trials=3, directory='./boston', seed=10)
reg.fit(x_train, y_train, epochs=10)

model = reg.export_model()
model.predict(x_test.astype(np.unicode))
```
This code works for me.

**Comment by ciessielski** [comment]
Thanks @haifeng-jin. In my case, it was solved by preparing correct shapes for x_train, y_train and x_test while I was reading my data from pandas dataframe.
