### ISSUE TITLE
AutoKeras with tensorflow.dataset gives TypeError: 'PrefetchDataset' object does not support indexing

### ISSUE THREAD

**Issue by seanreynoldscs** [keras-team/autokeras#961]
### Bug Description
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-e8d1a7f824a0> in <module>
      1 # Feed the image classifier with training data.
----> 2 clf.fit(train_ds[0], train_ds[1])

TypeError: 'PrefetchDataset' object does not support indexing

### Reproducing Steps
Following the steps for creating a tf.dataset from: https://www.tensorflow.org/tutorials/load_data/images

I encountered an issue with AutoModel when calling:
clf.fit(train_ds[0], train_ds[1])
and
clf.fit(next(iter(train_ds))[0], next(iter(train_ds))[1])
gives : 
TypeError: Expect the data to ImageInput to be numpy.ndarray or tf.data.Dataset, but got <class 'tensorflow.python.framework.ops.EagerTensor'>.

### Expected Behavior
I expect to be able to use AutoKeras with imagesets that are too large to fit in memory.

**Comment by haifeng-jin** [comment]
@seanreynoldscs  I did not find the tutorial on wrapping ImageNet into tf.data.Dataset. I believe there is a way to do so and without loading it into memory. AutoKeras currently is not supporting tensors as training data.
