### ISSUE TITLE
Not able to load best AutoModel after saving

### ISSUE THREAD

**Issue by picsag** [keras-team/autokeras#966]
Hi everyone!

I am using autokeras functional API on Cifar10 dataset and it ran succesfully saving the best model checkpoint in a model.index file. I am unable to load the model from the checkpoint as it did not save a .h5 file. 

I would need some basic code for loading saved models by autokeras. The documentation does not contain such loading code: https://autokeras.com/tutorial/export/
The automode.export_model() function does not accept parameters (such as a .h5 file name) when using the AutoModel class.

**Comment by picsag** [comment]
I managed to find a compromise by looking into auto_model.py and observing that the AutoModel.export_model() returns a Keras model.
However if an intermediate trial is needed, is still not clear how to load the corresponding model from the saved files (.index and checkpoint).

**Comment by haifeng-jin** [comment]
@picsag Currently, we are not providing this interface. However, I assume you are an advanced user who can dive into the source code. You can do a hacking solution like this:
```python
auto_model.tuner.load_model(trial_id)
```
The trial_id can be found somewhere in the saving directory. (The name of the json file).

**Comment by picsag** [comment]
Hi

Thank you for your reply. I loaded the json from the trial.json file from the trial id folder, 
path = '...path_to_trial_id...'
json_file = open(path, 'r')
loaded_model_json = json_file.read()
json_file.close()

However, I am not able to call 
loaded_model=model_from_json(loaded_model)


![image](https://user-images.githubusercontent.com/39946849/74586486-76acc180-4ff0-11ea-9da4-3130df99134a.png)

The code that you provided does not work with the path or the name of the json file or the loaded_model_json. The error is:
File "...\kerastuner\engine\tuner.py", line 150, in load_model
    model = self.hypermodel.build(trial.hyperparameters)
AttributeError: 'str' object has no attribute 'hyperparameters'

I would be grateful if you could provide a more detailed sample code on how to load an intermediate trial model.

**Comment by haifeng-jin** [comment]
We will see if more people are looking to use this, we will add this in the FAQ section on the website.

**Comment by chychen** [comment]
@picsag 
may I ask you how good of your trained model performed on cifar10?
I only achieve 74% accuracy by default `ak.ImageClassifier`... (script as belows)

```python
from tensorflow.keras.datasets import cifar10
import autokeras as ak

# Prepare the dataset.
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
# Initialize the ImageClassifier.
clf = ak.ImageClassifier()
# Search for the best model.
clf.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=300, batch_size=128)
# Evaluate on the testing data.
print('Accuracy: {accuracy}'.format(
    accuracy=clf.evaluate(x_test, y_test)))
```

if it need a lot of custom config to get higher performance, I will feel this is not handy, comparing to apply resnet18 to get 94%+ accuracy.
