### ISSUE TITLE
loaded_model can not work correctly

### ISSUE THREAD

**Issue by showkeyjar** [keras-team/autokeras#970]
### Bug Description

I use export and save function in document, 
but when I use load_model, then error:

### Reproducing Steps

  * Step 1: 
`
model = clf.export_model()
`
`
model.save('model/keras_model.h5')
`

  * Step 2: 
`
from tensorflow.python.keras.models import load_model
`
`
model = load_model('model/keras_model.h5')
`
**error:**  no class define Normalization

  * Step 3: 
`
import autokeras
`
`
custom_obj = autokeras.CUSTOM_OBJECTS
`
`
custom_obj['Normalization'] = autokeras.hypermodels.Normalization
`
`
model = load_model('model/keras_model.h5',custom_objects=custom_obj)
`
**error:**  unknown parameter 'trainable'

  * Step 4:
so, I checked the source code and found error raised in:
"autokeras.engine.block.py" line 23
and then, I search the kerastuner.HyperModel API
found HyperModel can only accept two parameters: "name", "tunable"
so, I modified the code:

change
`
super().__init__(**kwargs)
`
to
`
if 'trainable' in kwargs:
`
`
    tunable = kwargs.get("trainable")
`
`
    kwargs = {k: v for k, v in kwargs.items() if k!='trainable'}
`
`
    kwargs['tunable'] = tunable
`
`
super().__init__(name=name,tunable=kwargs.get("tunable"))
`

but still raised **error:** 

TypeError: Expect the inputs to layer normalization to be a Node, but got <class 'tensorflow.python.framework.ops.Tensor'>.

in "autokeras\engine\block.py" 61 lines
     59                                 'a Node, but got {type}.'.format(
     60                                     name=self.name,
---> 61                                     type=type(input_node)))

### Expected Behavior

how can I continue?

### Setup Details
Include the details about the versions of:
 - OS type and version:Windows 7
 - Python: 3.6.7
 - autokeras: 1.0.1
 - scikit-learn:0.22.1
 - numpy:1.18.1
 - keras:2.3.1
 - scipy:1.4.1
 - tensorflow:2.1.0
 - pytorch:1.4.0+cu92

**Comment by robbedec** [comment]
I'm experiencing the same problemen.

**Comment by haifeng-jin** [comment]
Normalization is not a custom object. It's a Keras layer. You don't need to add it to the custom object as long as you use tf2.1 or later.

**Comment by showkeyjar** [comment]
I

> Normalization is not a custom object. It's a Keras layer. You don't need to add it to the custom object as long as you use tf2.1 or later.

I try to use keras kayer, and only found keras.layers.BatchNormalization, when I use this class, then system raise error: expect 3 parameters but 4 were given.

**Comment by haifeng-jin** [comment]
https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/preprocessing/Normalization
This is the layer I was talking about.

**Comment by showkeyjar** [comment]
ok, it works, I'll close this issue now.
