### ISSUE TITLE
How can the user provide custom ranges for ConvBlock kernel_size

### ISSUE THREAD

**Issue by picsag** [keras-team/autokeras#971]
Hi

I tried to use ConvBlock by giving it a list of custom kernel sizes, using the parameter kernel_size=[7, 9, 13] for example. It throws an error. 
I observed that inside the ConvBlock class, the hp.Choice('kernel_size', [x, y, z], default=x) is used. 
How can the user provide custom kernel sizes from his code when adding a convolutional layer? Please provide sample code for this, thanks!

**Comment by picsag** [comment]
I tried to find a way to perform this custom kernel sizes by replacing the code inside basic.py from line 195 with the following:
        if isinstance(self.kernel_size, int):
            kernel_size = self.kernel_size
        elif self.kernel_size is None:
            kernel_size = hp.Choice('kernel_size',
                                    [3, 5, 7],
                                    default=self.kernel_size[0])
        else:
            kernel_size = hp.Choice('kernel_size',
                                    self.kernel_size,
                                    default=self.kernel_size[0])

Is there a better or more elegant way to do it using some other classes (HyperParameter ? )?

**Comment by haifeng-jin** [comment]
Currently, fork and modify the codebase would be the only solution. We may support customized hyper parameter as arguments later. Now user can only pass fixed values.
