### ISSUE TITLE
Resume model.fit process after interrupted

### ISSUE THREAD

**Issue by zhulingchen** [keras-team/autokeras#975]
### Feature Description
model.fit usually takes a long time to find the optimal network architecture; if something happened (like server reboot, for instance, or other possible issues), how could model.fit resume its process?

Is it possible to resume from the auto_model directory or are the AutoKeras developers working on that? I did not find the relative APIs for this.

**Comment by haifeng-jin** [comment]
It is in our FAQ in the tutorial, but I haven't error the answer. You can use the overwrite argument of AutoModel. Just run the code again providing the same directory, it will resume.

**Comment by zhulingchen** [comment]
> 
> 
> It is in our FAQ in the tutorial, but I haven't error the answer. You can use the overwrite argument of AutoModel. Just run the code again providing the same directory, it will resume.

Thanks! Is it a feature of 1.0.0 or 1.0.1?

**Comment by haifeng-jin** [comment]
@zhulingchen The resume feature is supported in 1.0.0. We haven't thoroughly tested it yet.
Unfortunately, AutoKeras 1.0.1 and future versions will only support Tensorflow 2.2 and above.
So it doesn't fully function will the preprocessing layers in TF 2.1.

**Comment by zhulingchen** [comment]
> 
> 
> @zhulingchen The resume feature is supported in 1.0.0. We haven't thoroughly tested it yet.
> Unfortunately, AutoKeras 1.0.1 and future versions will only support Tensorflow 2.2 and above.
> So it doesn't fully function will the preprocessing layers in TF 2.1.

But TF 2.2 has not released yet, right?

**Comment by haifeng-jin** [comment]
@zhulingchen It is not released. We coordinated with TF team to know what features will be there. This would save us the efforts to implement those features by ourselves.
