### ISSUE TITLE
can not find the implementation code for the network morphism algorithm

### ISSUE THREAD

**Issue by Neronjust2017** [keras-team/autokeras#981]
Hi,
 I have  read the AUTO-KERAS: EFFICIENT NEURAL ARCHITECTURE SEARCH WITH NETWORK MORPHISM paper, in which said, " In this paper, an efficient neural architecture search with network morphism is proposed, which utilizes Bayesian optimization to guide through the search space by selecting the most promising operations each time ." However, I can not find the implementation code for the network morphism algorithm in this Auoto-keras project. Is it in the "autokeras/tuner" directory? or somewhere else?
Thanks.

**Comment by haifeng-jin** [comment]
Please check the 0.4 version fort the implementation. Thanks

**Comment by Neronjust2017** [comment]
> 
> 
> Please check the 0.4 version fort the implementation. Thanks
Hi, it seems, In the current version, you are using RandomSearch, Hyperband, BayesianOptimization( from kerastuner ) and Greedy as the algorithms. I have a few questions: Why is "network morphism" is no longer available? Compared to the other algorithms, What are the advantages of "Greedy " ?  Is there an article about the"Greedy " algorithm? Thanks.

**Comment by haifeng-jin** [comment]
This is mainly because we updated the framework and didn't have enough people to implement the network morphism for the new framework.
We don't have an article for the greedy yet.
