### ISSUE TITLE
Getting an AttributeError for input_node = ak.Input()

### ISSUE THREAD

**Issue by saikchaitanya** [keras-team/autokeras#989]
### Reproducing Steps
  * Step 1: ... import autokeras as ak
  * Step 2: ... input_nodes = ak.Input()

### Setup Details
Include the details about the versions of:
 - OS type and version:
 - Python: 3.6
 - autokeras: 
 - scikit-learn: 
 - numpy:
 - keras:
 - scipy:
 - tensorflow: 2.1.0
 - pytorch:

**Comment by haifeng-jin** [comment]
Would you also provide the error message and your autokeras version?

Thanks

**Comment by saikchaitanya** [comment]
error message - AttributeError: module 'autokeras' has no attribute 'Input'

Autokeras version = 1.0.1

**Comment by haifeng-jin** [comment]
We really cannot reproduce this error. Which OS are you running it on? Thanks.
It is highly likely you installed new version of autokeras for one interpreter, and used another interpreter to run your program which has the older version of autokeras
