### ISSUE TITLE
How do I reduce the output model size?(AutoKeras1.0.0)

### ISSUE THREAD

**Issue by ericchen1207** [keras-team/autokeras#992]
As I used version 0.3.7 autokeras, the output model size was about 1M, but when I upgraded autokeras to version 1.0.0, the output model size became 3XXM, I don't know what's going on ~

**Comment by haifeng-jin** [comment]
It is mainly because of the search space. Now we are able to search larger but better models. There is no way to decrease the model size in AutoKeras. There may be other libraries has this feature, that you give it a large model, it gives you a smaller one. I am not sure.

Thanks.

**Comment by ericchen1207** [comment]
@haifeng-jin Thanks.
