### ISSUE TITLE
Training stops after several trials

### ISSUE THREAD

**Issue by picsag** [keras-team/autokeras#997]
Hello

I have experienced early termination of the number of trials, for example the training stopped at trial nr. 3, while I gave as parameter "max_trials=190"
How can this be prevented?

**Comment by haifeng-jin** [comment]
Would you please paste your code? I will try to see if I can reproduce the bug.
Thanks.

**Comment by picsag** [comment]
Apparently this hasn't happened with 1.0.2, only in 1.0.1.
Thanks
