### ISSUE TITLE
Cannot load HDF5 model after export

### ISSUE THREAD

**Issue by Kelvin-76** [keras-team/autokeras#999]
I tried the example of Titanic Survival Prediction from your document and export the model with the following code ,although the model is exported I got numpy error.

```
model = clf.export_model()
model.save('titanic.h5')
```
`
Traceback (most recent call last):
  File "titanic.py", line 17, in <module>
    model.save('titanic.h5')
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1008, in save
    signatures, options)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 112, in save_model
    model, filepath, overwrite, include_optimizer)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 109, in save_model_to_hdf5
    save_weights_to_hdf5_group(model_weights_group, model_layers)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 627, in save_weights_to_hdf5_group
    weight_values = K.batch_get_value(weights)
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3270, in batch_get_value
    return [x.numpy() for x in tensors]
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3270, in <listcomp>
    return [x.numpy() for x in tensors]
AttributeError: 'TrackableWeightHandler' object has no attribute 'numpy'
`

When I was trying to load the HDF5 model for prediction , errors occurs

```
model = tf.keras.models.load_model('titanic.h5', custom_objects=ak.CUSTOM_OBJECTS)
```

`Traceback (most recent call last):
  File "load_model.py", line 4, in <module>
    model = tf.keras.models.load_model('titanic.h5', custom_objects=ak.CUSTOM_OBJECTS)
  File "C:\Users\Python\Python37\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "C:\Users\Python\Python37\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 171, in load_model_from_hdf5
    load_weights_from_hdf5_group(f['model_weights'], model.layers)
  File "C:\Users\Python\Python37\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 668, in load_weights_from_hdf5_group
    g = f[name]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\Python\Python37\lib\site-packages\h5py\_hl\group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'dense' doesn't exist)"`

**Comment by bestpredicts** [comment]
same error 
error ifo
```
  File "/home/dy/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 106, in deserialize
    printable_module_name='layer')
  File "/home/dy/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 292, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/home/dy/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 250, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_
```
here is my code 

```
import time, os, re
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib import cm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from tqdm import tqdm

import time, os, re
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import tensorflow as tf



os.environ["AWS_ACCESS_KEY_ID"]="NA55ROX4Y3W1I0P4BYVR"
os.environ["AWS_SECRET_ACCESS_KEY"]="nl3RnsfVW0zTnoJv1ThENDAcoZX6lHcPPG4N7Ne4"
os.environ["S3_ENDPOINT"]="192.168.129.113:7480"
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
os.environ["S3_USE_HTTPS"] = "0"
os.environ["S3_REQUEST_TIMEOUT_MSEC"] = "60000"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
os.environ["S3_VERIFY_SSL"] = "0"
os.environ["JAVA_HOME"] = "/usr/local/java/jdk1.8.0_11"

t_all_beg = time.time()
print('程序启动时间为：',  time.strftime('%H:%M:%S',time.localtime(t_all_beg)) )
import argparse


# -*- coding: utf-8 -*-
# filename: main.py
import sys
import tensorflow as tf 
import os
os.environ["AWS_ACCESS_KEY_ID"]="NA55ROX4Y3W1I0P4BYVR"
os.environ["AWS_SECRET_ACCESS_KEY"]="nl3RnsfVW0zTnoJv1ThENDAcoZX6lHcPPG4N7Ne4"
os.environ["S3_ENDPOINT"]="192.168.129.113:7480"
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
os.environ["S3_USE_HTTPS"] = "0"
os.environ["S3_REQUEST_TIMEOUT_MSEC"] = "60000"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
os.environ["S3_VERIFY_SSL"] = "0"


import os
import math
import codecs
import random
import numpy as np
from glob import glob
from PIL import Image
import cv2
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from tqdm import tqdm
import autokeras as ak
import time
import os
import argparse
import json
import sys
import pandas as  pd 
import shutil


os.environ["CUDA_VISIBLE_DEVICES"] = "0"

DEBUG = True
PRINT = False


import json
import tensorflow  as  tf
import shutil

os.environ["AWS_ACCESS_KEY_ID"]="NA55ROX4Y3W1I0P4BYVR"
os.environ["AWS_SECRET_ACCESS_KEY"]="nl3RnsfVW0zTnoJv1ThENDAcoZX6lHcPPG4N7Ne4"
os.environ["S3_ENDPOINT"]="192.168.129.113:7480"
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
os.environ["S3_USE_HTTPS"] = "0"
os.environ["S3_REQUEST_TIMEOUT_MSEC"] = "60000"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
os.environ["S3_VERIFY_SSL"] = "0"
os.environ["JAVA_HOME"] = "/usr/local/java/jdk1.8.0_11"


DownLoad =True

"""
    上传推理代码公共方法
    params:
    old_path 原始文件夹
    new_path 目标文件夹
"""
def copyFile(old_path,new_path):
    w = tf.io.gfile.walk(old_path)
    print("文件读取完毕")
    new = new_path
    for i in w:
        print("xxxxxxxxxxxxxxx")
        print('i1',i[1])
        for j in i[1]:
            path = i[0].replace(old_path,new)+'/'+j
            print("#####创建文件夹,文件夹路径："+path+" ")
            tf.io.gfile.makedirs(path)
        for k in i[2]:
            file_old_path = i[0]+'/'+k
            print(i[0])
            file_path = i[0].replace(old_path,new)+'/'+k
            print("#####原路径；"+file_old_path+" ####目标文件路径："+file_path)
            tf.io.gfile.copy(file_old_path,file_path,overwrite=True)

def copy_dir(old_path,new_path):
    print(old_path,new_path)
    file_path=tf.io.gfile.glob("".join([old_path,'*.*']))

    print('filepath',len(file_path))
    for s in file_path:
        image_name = s.split('/')[-1]
        print(s)
        tf.io.gfile.copy(s,"".join([new_path,'/',image_name]))




class MyEncoder(json.JSONEncoder):

    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        else:
            return super(MyEncoder, self).default(obj)





def prepare_data(list_of_images,labels):

    x = [] # images as arrays
        
    for idx,image in enumerate(list_of_images):
        try:
            x.append(cv2.resize(cv2.imread(image), (int(args.img_width),int(args.img_height)), interpolation=cv2.INTER_CUBIC))
        except:
            print("cv2 转化图像失败")

    return x





def convert_img_2_input(path):
    X =  prepare_data(path)
    X = np.array(X)
    print(X.shape)
    return X








class AutoPredict:

    def __init__(self,s3_path = "s3://demo-bucket/home/jovyan/work/tf_model/model/"):
        self.dirname, self.filename = os.path.split(os.path.abspath(sys.argv[0]))
        self.local_path = os.path.join(self.dirname,"model_dir/")
        if not os.path.exists(self.local_path):
            print("目录不存在 主动创建目录 %s"%self.local_path)
            os.mkdir(self.local_path)
        else:
            print("删除文件夹 %s"%self.local_path)
            shutil.rmtree(self.local_path)
            os.mkdir(self.local_path)



        print(s3_path)
        print(self.local_path)
        copyFile(s3_path,self.local_path)
        print("模型拷贝成功")
        model = tf.keras.models.load_model(self.local_path+'model.h5',custom_objects=ak.CUSTOM_OBJECTS)
        print("模型初始化成功")
    def  predict(self,img_path="s3://demo-bucket/qxm/a_image_out/ANNO_80/污损塑料_fimg_257.jpg"):
        save_p = self.local_path = os.path.join(self.dirname,"img_dir/")
        copyFile(img_path,save_p+"img.jpg")
        X = convert_img_2_input(save_p+"img.jpg")
        res = self.model.predict(X)
        return res 


                

headers = {'Content-Type': 'application/json'}

if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    ## Required parameters
    parser.add_argument("--model_path", default="s3://demo-bucket/home/jovyan/work/tf_model/model/", type=str, required=False,
                        help="model path ")
    parser.add_argument("--host", default='0.0.0.0', type=str, required=False,
                        help="host ")
    parser.add_argument("--port", default=8085, type=str, required=False,
                        help="port ")                        



    args = parser.parse_args()

    s3_path = args.model_path


    DEBUG = True
    if DEBUG:
        models = AutoPredict(s3_path)
        result = {}
        result['result'] = models.predict()
        print(result)
        



```

**Comment by haifeng-jin** [comment]
Hi, Would you try the latest tf-nightly? It may resolve the issue. Thanks

**Comment by moelliDo** [comment]
Hi, unfortunately the latest tf-nightly raises another error: 

    AttributeError: in user code:

    /home/user/tf-nightly-test/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:499 train_function  *
        outputs = self.distribute_strategy.experimental_run_v2(
    /home/user/tf-nightly-test/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:856 experimental_run_v2  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/user/tf-nightly-test/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2112 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/user/tf-nightly-test/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2470 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/user/tf-nightly-test/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:471 train_step  **
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    /home/user/tf-nightly-test/lib/python3.6/site-packages/tensorflow/python/keras/engine/compile_utils.py:348 update_state
        self._build(y_pred, y_true)
    /home/user/tf-nightly-test/lib/python3.6/site-packages/tensorflow/python/keras/engine/compile_utils.py:267 _build
        self._metrics, y_true, y_pred)
    /home/user/tf-nightly-test/lib/python3.6/site-packages/tensorflow/python/util/nest.py:1118 map_structure_up_to
        **kwargs)
    /home/user/tf-nightly-test/lib/python3.6/site-packages/tensorflow/python/util/nest.py:1214 map_structure_with_tuple_paths_up_to
        *flat_value_lists)]
    /home/user/tf-nightly-test/lib/python3.6/site-packages/tensorflow/python/util/nest.py:1213 <listcomp>
        results = [func(*args, **kwargs) for args in zip(flat_path_list,
    /home/user/tf-nightly-test/lib/python3.6/site-packages/tensorflow/python/util/nest.py:1116 <lambda>
        lambda _, *values: func(*values),  # Discards the path arg.
    /home/user/tf-nightly-test/lib/python3.6/site-packages/tensorflow/python/keras/engine/compile_utils.py:377 _get_metric_objects
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    /home/user/tf-nightly-test/lib/python3.6/site-packages/tensorflow/python/keras/engine/compile_utils.py:377 <listcomp>
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    /home/user/tf-nightly-test/lib/python3.6/site-packages/tensorflow/python/keras/engine/compile_utils.py:398 _get_metric_object
        y_t_rank = len(y_t.shape.as_list())

    AttributeError: 'tuple' object has no attribute 'shape'

Within TF==2.1.0 I used pandas Dataframes as Innput and everything worked fine except for saving a model. Now I transformed these Dataframes into Numpy arrays but the error mentioned above occurs.

**Comment by Nesty92** [comment]
any news ?

**Comment by Kelvin-76** [comment]
I have tested all dev versions of tf-nightly-gpu==2.2.0 in colab including the latest  version(tf-nightly-gpu 2.2.0.dev20200308) , error still exits.

From tf-nightly-gpu==2.2.0.dev20200226 to the latest version(tf-nightly-gpu 2.2.0.dev20200308), it will raise AttributeError: 'tuple' object has no attribute 'shape' error:
````
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:493 train_function  *
        outputs = self.distribute_strategy.experimental_run_v2(
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:856 experimental_run_v2  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2112 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2470 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:465 _train_step  **
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py:348 update_state
        self._build(y_pred, y_true)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py:267 _build
        self._metrics, y_true, y_pred)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py:1118 map_structure_up_to
        **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py:1214 map_structure_with_tuple_paths_up_to
        *flat_value_lists)]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py:1213 <listcomp>
        results = [func(*args, **kwargs) for args in zip(flat_path_list,
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py:1116 <lambda>
        lambda _, *values: func(*values),  # Discards the path arg.
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py:377 _get_metric_objects
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py:377 <listcomp>
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py:398 _get_metric_object
        y_t_rank = len(y_t.shape.as_list())

    AttributeError: 'tuple' object has no attribute 'shape'
````
With tf-nightly-gpu==2.2.0.dev20200218 and before, it will raise AttributeError: 'TrackableWeightHandler' object has no attribute 'numpy' error:
````
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py in save(self, filepath, overwrite, include_optimizer, save_format, signatures, options)
   1002     """
   1003     save.save_model(self, filepath, overwrite, include_optimizer, save_format,
-> 1004                     signatures, options)
   1005 
   1006   def save_weights(self, filepath, overwrite=True, save_format=None):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/save.py in save_model(model, filepath, overwrite, include_optimizer, save_format, signatures, options)
    133           'or using `save_weights`.')
    134     hdf5_format.save_model_to_hdf5(
--> 135         model, filepath, overwrite, include_optimizer)
    136   else:
    137     saved_model_save.save(model, filepath, overwrite, include_optimizer,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py in save_model_to_hdf5(model, filepath, overwrite, include_optimizer)
    107     model_weights_group = f.create_group('model_weights')
    108     model_layers = model.layers
--> 109     save_weights_to_hdf5_group(model_weights_group, model_layers)
    110 
    111     # TODO(b/128683857): Add integration tests between tf.keras and external

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py in save_weights_to_hdf5_group(f, layers)
    627     g = f.create_group(layer.name)
    628     weights = _legacy_weights(layer)
--> 629     weight_values = K.batch_get_value(weights)
    630     weight_names = [w.name.encode('utf8') for w in weights]
    631     save_attributes_to_hdf5_group(g, 'weight_names', weight_names)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py in batch_get_value(tensors)
   3325   """
   3326   if context.executing_eagerly():
-> 3327     return [x.numpy() for x in tensors]
   3328   elif ops.inside_function():  # pylint: disable=protected-access
   3329     raise RuntimeError('Cannot get value inside Tensorflow graph function.')

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py in <listcomp>(.0)
   3325   """
   3326   if context.executing_eagerly():
-> 3327     return [x.numpy() for x in tensors]
   3328   elif ops.inside_function():  # pylint: disable=protected-access
   3329     raise RuntimeError('Cannot get value inside Tensorflow graph function.')

AttributeError: 'TrackableWeightHandler' object has no attribute 'numpy'
````

**Comment by haifeng-jin** [comment]
I also found the latest tf-nightly doesn't solve the issue. We will need to further investigate it. Thanks

**Comment by mattou78400** [comment]
Hello,

Is there any update regarding this topic?

I find myself in the same situation...

Thanks!

(tf 2.1)

**Comment by sword134** [comment]
Whats the status on this? Not being able to load a saved model kind of defeats the purpose of autokeras in the first place...

**Comment by PascalSchimmler** [comment]
@sword134 It was fixed with the update today, here is the code that allows you to save and load: 

```
model.fit(x=x_train, y=y_train, validation_data = (x_val, y_val), validation_split=0, epochs=80)
model = model.tuner.get_best_model()
model.save(os.path.join(f, 'bestModel.h5'))
y_prediction = model.predict(x_test)

modelLoaded = tf.keras.models.load_model(os.path.join(f, 'bestModel.h5'))
y_prediction = modelLoaded.predict(x_test)
```

**Comment by haifeng-jin** [comment]
As I tested, it works now with AutoKeras 1.0.3.

**Comment by Kelvin-76** [comment]
Thank you, it's working fine now.

**Comment by abdulsam** [comment]
> As I tested, it works now with AutoKeras 1.0.3.

I'm getting the same error while loading the model:
`WARNING:tensorflow:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.`

and after `model.fit(x_train, y_train, epoch=20)`
I'm getting the following error:

`ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:533 train_step  **
        y, y_pred, sample_weight, regularization_losses=self.losses)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py:205 __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/losses.py:143 __call__
        losses = self.call(y_true, y_pred)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/losses.py:246 call
        return self.fn(y_true, y_pred, **self._fn_kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/losses.py:1527 categorical_crossentropy
        return K.categorical_crossentropy(y_true, y_pred, from_logits=from_logits)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py:4561 categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py:1117 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (None, 1) and (None, 10) are incompatible`

**Comment by haifeng-jin** [comment]
I think it mainly because of the categorical encoding? would you paste your code?
